### PR TITLE
fix(fms): magnetic variation refactor and bug fixes

### LINKED ISSUE #10515: Autopilot - Aircraft turns to opposite direction first before turning back when inserting DCT TO waypoint
### Simulator

2020

### Aircraft Version

Development (4k)

### Build info

```json
{
    "built": "2026-01-23T09:43:11+00:00",
    "ref": "refs/heads/master",
    "sha": "42242ae580bebc6bc7d2119cac5c98f100cf5272",
    "actor": "flogross89",
    "event_name": "manual",
    "pretty_release_name": "master:42242ae5",
    "version": "a380x-v0.15.0-dev.42242ae"
}
```

### Describe the bug

When inserting DCT to waypoint, the system draws a new route to the waypoint but first by turning the opposite way. This results in the aircraft first turning to opposite direction and then turning back to the intended course.

Reference:
https://youtu.be/dcPr8Rss2PI?si=ulFXyFvn_qTsFa23&t=1112

### Expected behavior

After inserting DCT, the aircraft should turn to the correct direction to intersect with the required course.

### Steps to reproduce

1. Takeoff
2. Insert DCT to a new waypoint, from NAV mode or HDG mode
3. The plane will first turn to the opposite direction.

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

C.Schaffhausen

### PR DESCRIPTION
**Pull request by tracernz**
Fixes #10515

## Summary of Changes

- Adds magvar to procedure legs, airports, and runways in the navigation DB, and with that we can now support true referenced items.
- Adds a new MagVar library that implements the correct magnetic database coverage area (i.e. no magvar in polar regions), and provides convenient methods for working with magvar and converting between true and magnetic.
- Adds magvar to flight plan leg definitions so we always have the correct magvar available. This helps with fixing the immediate bug with DIR TO/HOLD, and also sets us up to fully implement the TRUE NORTH mode in the MCDU and MFD pages in future PRs as we can now easily convert magnetic bearings to true.
- Use the leg definition magvar to generate the LNAV geometry, fixing various bugs including the enroute DIR TO/HOLDs.
- Renames the nav db and leg definition `magneticCourse` property to just `course` as it can also be a true course (and always could be, we just didn't have a way to know before).
- Fixes a variety of magvar and true bearing related issues on the lines touched by the rename.
- Replaces and removes A32NX_Util magvar related functions, and fixes some more bugs.

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Perform a full flight, testing some direct tos, holds, fix info, and PBD waypoints. Ensure the LNAV geometry is correct, and that the DIR TOs perform a smooth turn on activation, with no initial deviation to the other direction.

We will need tests from both aircraft.

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo**, **flybywire-aircraft-a380-842 (4K)** or **flybywire-aircraft-a380-842 (8K)** download link at the bottom of the page

### CODE REVIEW

File: fbw-common/src/systems/shared/src/MagVar.ts [hunk 1]
```diff
@@ -0,0 +1,105 @@
...
+  }
+
+  /**
+   * Checks if database magnetic variation is available for a specific point.
+   * @param lat The latitude of the point in degrees, with negative values south of the equator.
+   * @param lon The longiture of the point in degrees, with negative values west of the equator.
+   * @returns true if the point is within the magnetic database coverage.
+   */
+  public static isAvailable(lat: number, lon: number): boolean {
+    return (lat >= -60.5 && lat <= 73.5) || (lon <= -117.5 && lon >= -87.5 && lat <= 82.5 && lat >= 0);
```
Comment (FozzieHi) [inline fbw-common/src/systems/shared/src/MagVar.ts]: Not sure what the actual database availability is, but `lon <= -117.5 && lon >= -87.5` can never be true.

Comment (tracernz) [reply fbw-common/src/systems/shared/src/MagVar.ts]: Good spot. I think the IRS might have this bug too then...

**Comment by BlueberryKing** [comment]
Does this supersede https://github.com/flybywiresim/aircraft/pull/10339 ?

**Comment by tracernz** [comment]
> Does this supersede #10339 ?

Yeah, I guess it does.

File: fbw-a32nx/src/systems/instruments/src/MCDU/legacy_pages/A320_Neo_CDU_FlightPlanPage.ts [hunk 2]
```diff
@@ -1349,13 +1349,14 @@ function formatTrack(from: FlightPlanLeg, to: { definition: { waypoint: { locati
     return '';
   }
 
-  const magVar = Facilities.getMagVar(from.definition.waypoint.location.lat, from.definition.waypoint.location.long);
+  // FIXME shouldn't it be ppos magvar?
```
Comment (BlueberryKing) [inline fbw-a32nx/src/systems/instruments/src/MCDU/legacy_pages/A320_Neo_CDU_FlightPlanPage.ts:1352]: It probably should be, yes 😄

File: fbw-common/src/wasm/systems/systems/src/navigation/adirs.rs [hunk 3]
```diff
@@ -1951,6 +1951,7 @@ impl InertialReference {
         self.extreme_latitude = !((-60. + hysteresis_sign * 0.5) <= latitude
             && (latitude <= (73. - hysteresis_sign * 0.5)
                 || (latitude <= (82. - hysteresis_sign * 0.5)
+                    && latitude >= 0.
```
Comment (BlueberryKing) [inline fbw-common/src/wasm/systems/systems/src/navigation/adirs.rs:1954]: What does this do?

Comment (tracernz) [reply fbw-common/src/wasm/systems/systems/src/navigation/adirs.rs:1954]: Makes sure we don't apply the north pole cutout in the southern hemisphere.

File: fbw-a32nx/src/systems/instruments/src/MCDU/legacy_pages/A320_Neo_CDU_FlightPlanPage.ts (hunk 2 above)
Comment (tracernz) [reply fbw-a32nx/src/systems/instruments/src/MCDU/legacy_pages/A320_Neo_CDU_FlightPlanPage.ts:1352]: Yeah, it's actually just not the correct track displayed at all. I'll fix that in a future PR.

Comment (tracernz) [reply fbw-a32nx/src/systems/instruments/src/MCDU/legacy_pages/A320_Neo_CDU_FlightPlanPage.ts:1352]: Said PR https://github.com/flybywiresim/aircraft/pull/10548

**Comment by BravoMike99** [comment]
Dev team QA report

Discord Username  : bruno_pt99
Object of testing : #10530 
Aircraft          : A32NX 
Simulator         : 2020
Tier of Testing   : 1
Date              : 17/02/2026
Testing Process: 
Performed a flight starting at LPMA and ending at LPMA.
Tested PBD & FIX INFO based on the RWY 05 VOR APPR. 
Tested holding with the published PILIM holding.
Performed some DIR TO and verified they worked fine.

Testing Results: 
Passed

Media:
Track
DIR TO
HOLD
PBD
image
image
