### PR TITLE
fix(a32nx/fwc): move memos to fwc and fix logic

### LINKED ISSUE #10498: a32nx/FWC: TO config memo does not appear after flight on T.O conf press
### Simulator Version

2020

### Aircraft Version

Development

### Build info

```json
master
```

### Describe the bug

The takeoff memo does not appear on T.O config button press after a flight. It only appears if it is pressed during phase 2.

### Expected behavior

T.O memo should appear if T.O config button is pressed when at least one engine is running (during phase 2 or 9).

### Steps to reproduce

Perform a quick pattern.
Land and press the T.O config button, observe how the T.O memo does not appear.

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

bruno_pt99

### PR DESCRIPTION
**Pull request by tracernz**
Fixes #10498

## Summary of Changes

- Implement takeoff and landing memo logic in the FWC, and delete the old logic.
- Fix some missing memo inhibits.

## Additional context

Discord username (if different from GitHub):

## Testing instructions

In the A32NX start a flight, make sure the takeoff memo appears when either the engines have both been running for 2 minutes or you press TO CONF TEST. Takeoff, and climb to a 4000 feet AGL or so, then setup for a normal landing. Ensure the landing memo appears, land again, and when going below 80 knots, ensure the landing memo goes away, then press TO CONF TEST and ensure the takeoff memo appears. For bonus points you can try the approach with both RAs failed and ensure you still get the landing memo on approach with all gear down.

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo**, **flybywire-aircraft-a380-842 (4K)** or **flybywire-aircraft-a380-842 (8K)** download link at the bottom of the page

### CODE REVIEW

File: fbw-a32nx/src/systems/systems-host/systems/FWC/PseudoFWC.ts [hunk 1]
```diff
@@ -1796,6 +1799,13 @@ export class PseudoFWC {
       mainGearDownlocked &&
       (this.lgciu1DiscreteWord1.bitValueOr(25, false) || this.lgciu2DiscreteWord1.bitValueOr(25, false));
 
+    // ra validity
+    const eitherRaInvalid = this.radioHeight1.isFailureWarning() || this.radioHeight2.isFailureWarning();
+    const bothRaInvalid = this.radioHeight1.isFailureWarning() && this.radioHeight2.isFailureWarning();
+    const bothRaInvalidOrNcd =
+      (this.radioHeight1.isNoComputedData || this.radioHeight1.isFailureWarning()) &&
```
Comment (BravoMike99) [inline fbw-a32nx/src/systems/systems-host/systems/FWC/PseudoFWC.ts]: Looks like it was already there before:
```suggestion
      (this.radioHeight1.isNoComputedData() || this.radioHeight1.isFailureWarning()) &&
```

Comment (tracernz) [reply fbw-a32nx/src/systems/systems-host/systems/FWC/PseudoFWC.ts]: Great catch!

File: fbw-a32nx/docs/a320-simvars.md [hunk 2]
```diff
@@ -25,7 +25,7 @@
     - [Flight Augmentation Computer (FAC)](#flight-augmentation-computer-fac)
   - [Flaps / Slats (ATA 27)](#flaps--slats-ata-27)
   - [Flight Controls (ATA 27)](#flight-controls-ata-27)
-  - [Fuel (ATA 28)](#fuel-ata-28)
+  - [Fuel ATA 28](#fuel-ata-28)
```
Comment (Gurgel100) [inline fbw-a32nx/docs/a320-simvars.md]: Why are you removing the parenthesis? In the other chapters we have them as well.

File: fbw-common/src/wasm/systems/systems/src/navigation/adirs.rs
Comment (Gurgel100) [inline fbw-common/src/wasm/systems/systems/src/navigation/adirs.rs:1]: I just want to mention here that the ADIRS code is beeing reworked quite extensively here: #10454.

File: fbw-a32nx/docs/a320-simvars.md (hunk 2 above)
Comment (tracernz) [reply fbw-a32nx/docs/a320-simvars.md]: That was automatic by the linter. The title in the linked section has no parens.

File: fbw-common/src/wasm/systems/systems/src/navigation/adirs.rs
Comment (tracernz) [reply fbw-common/src/wasm/systems/systems/src/navigation/adirs.rs:1]: That's fine, but I learned long ago that you can't wait for other PRs, and that one actually doesn't address the missing bits added here.

File: fbw-a32nx/docs/a320-simvars.md (hunk 2 above)
Comment (tracernz) [reply fbw-a32nx/docs/a320-simvars.md]: I fixed the fuel section up and the TOC then got automatically put back to the previous state on save by the linter.

File: fbw-common/src/wasm/systems/systems/src/navigation/adirs.rs
Comment (tracernz) [reply fbw-common/src/wasm/systems/systems/src/navigation/adirs.rs:1]: cc @lukecologne for info as you will have to add the VMO/MMO bits to the ADR discrete word.

Comment (lukecologne) [reply fbw-common/src/wasm/systems/systems/src/navigation/adirs.rs:1]: > That's fine, but I learned long ago that you can't wait for other PRs, and that one actually doesn't address the missing bits added here.

I fully agree, especially as this will be, or rather already is, a very large PR, so it will probably take a bit of time to finish and fully review and test.

> cc @lukecologne for info as you will have to add the VMO/MMO bits to the ADR discrete word.

Small correction here, what you are adding is actually incorrect AFAICT, you are hooking up the low speed warning discretes to the VMO/MMO selection discretes. The Low speed warning discretes are represented in ADR discrete word 2 (Label 271). The bit that is used in the FWS is the VMO/MMO selection discrete 2, which is wired to the gear down/ferry flight switch, which sets the VMO to 235kts and MMO to 0.60.
But, you are correct, I have added neither of these, will add them.

Comment (tracernz) [reply fbw-common/src/wasm/systems/systems/src/navigation/adirs.rs:1]: You're dead right. I'll keep the FWC logic but remove the ADR part. The changes might be useful for you to move the speed discretes inside the ADR if you didn't already.

Comment (tracernz) [reply fbw-common/src/wasm/systems/systems/src/navigation/adirs.rs:1]: Done.

**Comment by BravoMike99** [comment]
Dev team QA report

Discord Username  : bruno_pt99
Object of testing : #10501 
Aircraft          : A32NX 
Simulator         : 2020
Tier of Testing   : 1
Date              : 31/01/2026

Testing Process: 
Performed a quick pattern and verified landing memo appeared.
Performed a go around, verified that landing memo disappears after doing so.
Failed both RAs and checked that the landing memo appears upon landing gear down.
Checked that the ldg memo disappears below 80kts during landing.
Checked that the TO memo can be brought up after landing by pressing the T.O CONF button.
T.O memo appears after both engines have been running for 2 minutes or by manually  pressing the button.
Testing Results: 
Passed
