### PR TITLE
fix(a32nx/fws): make cav charge play in sets of 3

### LINKED ISSUE #10239: Voluntary AP disconnect logic
### Simulator Version

2020

### Aircraft Version

Development

### Build info

```json
{
    "built": "2025-07-17T16:23:16+00:00",
    "ref": "refs/heads/master",
    "sha": "d2d4239a8b45597965e1772e5164d3c9a47be860",
    "actor": "Saschl",
    "event_name": "manual",
    "pretty_release_name": "master:d2d4239a",
    "version": "a32nx-v0.14.0-dev.d2d4239"
}
```

### Describe the bug

The current one that just got added in the dev version is a bit bugged, the calvary charge on disconnecting plays 4 times, or sometimes 5 times, instead of 3 like it is supposed to.
https://youtu.be/AK1GENvj0rE?si=n0usAQvrl48NW5cu&t=7935 you can see here that it plays 3 times, and the FO only presses the disconnect button once.

(small side note : master warning light stays solid for the 9 second duration that AP OFF stays on the ECAM, while in the video you can see it flashes 6 or 7 times before disappearing, but doesn't make much of a difference).

https://youtu.be/wka9BQ7_xvo heres a small video showing the current logic in the latest dev version, button pressed once and cavalry charge plays 4 times.

### Expected behavior

Cavalry charge plays 3 times, and master warning light flashes.

### Steps to reproduce

1. Engage AP in the air.
2. Disconnect AP in the air using AP_OFF keybind or the button on the sidestick

### References (optional)

https://youtu.be/wka9BQ7_xvo
https://youtu.be/AK1GENvj0rE?si=YIBEgNrMde7AiNfO&t=7934

### Additional info (optional)

_No response_

### Discord Username (optional)

_No response_

### PR DESCRIPTION
**Pull request by BravoMike99**
Fixes #10239 

## Summary of Changes

Fixes the cav  charge not playing three times in case of voluntary disconnect.
In the involuntary disconnect case, there is a delay before cav charge plays again.

## References

In the issue itself and https://youtu.be/R16fGNxebE4?t=1948

## Additional context

Discord username (if different from GitHub): bruno_pt99

## Testing instructions

Disconnect the autopilot via the side stick button with one or two presses. Check that cav charge sounds three times in both cases.
Disconnect the autopilot via the FCU push button, the cav charge should repeat regularly in sets of 3 like the reference video.
Engage autopilot  and check that the cav charge loop stops.

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo**, **flybywire-aircraft-a380-842 (4K)** or **flybywire-aircraft-a380-842 (8K)** download link at the bottom of the page

### CODE REVIEW

File: fbw-a32nx/src/systems/systems-host/systems/FWC/FwsSoundManager.ts [hunk 1]
```diff
@@ -293,6 +290,10 @@ export class FwsSoundManager {
       this.stopCurrentSound();
     }
     this.soundQueue.delete(soundKey);
+    if (soundKey === this.soundToRepeat) {
```
Comment (FozzieHi) [inline fbw-a32nx/src/systems/systems-host/systems/FWC/FwsSoundManager.ts:293]: This only works if a dequeue is called during a repeat right? If a dequeue is called during the initial play then it will still repeat?

**Comment by ghostxyz990** [comment]
Quality Assurance Trainee Report

Discord Username  : adb_1872
Object of testing : #10600  
Aircraft          : A32NX 
Simulator         : 2020 
Tier of Testing   : 1
Date              : 26/03/2026 

Testing Process: 
Disconnect the autopilot via the side stick button with one or two presses. Check that cav charge sounds three times in both cases.
Disconnect the autopilot via the FCU push button, the cav charge should repeat regularly in sets of 3 like the reference video.
Engage autopilot and check that the cav charge loop stops.

Testing Results: 
Failed  

Negatives:
Cavalry still plays after pressing master warning for disconnecting with the FCU p/b

Conclusions: 


Media:

File: fbw-a32nx/src/systems/systems-host/systems/FWC/FwsSoundManager.ts (hunk 1 above)
Comment (BravoMike99) [reply fbw-a32nx/src/systems/systems-host/systems/FWC/FwsSoundManager.ts:293]: Good point, I changed it now so that the sound to repeat key is set before hand (on playSound).

**Comment by BravoMike99** [comment]
> Quality Assurance Trainee Report
> 
> Discord Username : adb_1872 Object of testing : #10600 Aircraft : A32NX Simulator : 2020 Tier of Testing : 1 Date : 26/03/2026
> 
> Testing Process: Disconnect the autopilot via the side stick button with one or two presses. Check that cav charge sounds three times in both cases. Disconnect the autopilot via the FCU push button, the cav charge should repeat regularly in sets of 3 like the reference video. Engage autopilot and check that the cav charge loop stops.
> 
> Testing Results: Failed
> 
> Negatives: Cavalry still plays after pressing master warning for disconnecting with the FCU p/b
> 
> Conclusions:
> 
> Media:

Fixed, it was not taking into account the pauses for the MC silencing.

**Review by FozzieHi — APPROVED** [review]

**Comment by ghostxyz990** [comment]
Quality Assurance Trainee Report

Discord Username  : adb_1872
Object of testing : #10600  
Aircraft          : A32NX 
Simulator         : 2020 
Tier of Testing   : 1
Date              : 27/03/2026 

Testing Process: 
Disconnect the autopilot via the side stick button with one or two presses. Check that cav charge sounds three times in both cases.
Disconnect the autopilot via the FCU push button, the cav charge should repeat regularly in sets of 3 like the reference video.
Engage autopilot and check that the cav charge loop stops.

Testing Results: 
Passed  

Negatives:


Conclusions: 


Media:
