### PR TITLE
fix(a32nx/fwc): add monitor confirm time and fix flight phase inhibition

### LINKED ISSUE #10246: Master caution warning when loading in cold and dark
### Simulator Version

2020

### Aircraft Version

Development

### Build info

```json
{
    "built": "2025-07-20T14:45:22+00:00",
    "ref": "refs/heads/master",
    "sha": "df511bc2a66dc2983bbe420f199f55c8faac3638",
    "actor": "flogross89",
    "event_name": "manual",
    "pretty_release_name": "master:df511bc2",
    "version": "a32nx-v0.14.0-dev.df511bc"
}
```

### Describe the bug

When loading into an airport, a master caution sound plays continuously. This happens before the aircraft has power. Clicking the master caution button dismisses the alarm, and turning on the batteries and external power will also dismiss the alarm. Nothing shows up in the ecam status, although once when this happened there were a few ecam caution/advisory actions showing. They disappeared after a couple of seconds, but I think they were to do with flight controls.

### Expected behavior

Loading into the game cold/dark does not create a master caution sound.

### Steps to reproduce

1. Select the A32nx as the aircraft
2. Load into a gate
3. Hear master caution sound playing
(I have had this happen at multiple airports, specifically at EGPH and EDDB)

### References (optional)

I have a Steam clip/recording of what happens, however it is failing to export the video. I will add the recording when I can.

### Additional info (optional)

_No response_

### Discord Username (optional)

TazerXI

### PR DESCRIPTION
**Pull request by tracernz**
Fixes #10246

## Summary of Changes

Add the 0.3 second monitor input confirm time for warnings, which fixes the master warning on cold & dark spawn. Fix flight phase inhibition so it doesn't clear warnings that are already active.

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Spawn cold and dark and make sure the master warning CRC sound is not active. Spawn on the runway and set takeoff thrust with the parking brake still on; make sure you get a master warning for CONFIG PARK BRK ON and CRC sound.

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo**, **flybywire-aircraft-a380-842 (4K)** or **flybywire-aircraft-a380-842 (8K)** download link at the bottom of the page

### CODE REVIEW

File: fbw-a32nx/src/systems/systems-host/systems/FWC/PseudoFWC.ts [hunk 1]
```diff
@@ -3150,18 +3163,21 @@ export class PseudoFWC {
...
         (value.side === 'LEFT' && !this.failuresLeft.includes(key) && !recallFailureKeys.includes(key)) ||
         (value.side === 'RIGHT' && !this.failuresRight.includes(key));
 
-      if (value.simVarIsActive.get()) {
+      if (newWarning && value.flightPhaseInhib.some((e) => e === flightPhase)) {
+        continue;
+      }
+
+      // consider monitor input confirm time (0.3 sec)
+      if (value.simVarIsActive.get() && simTime >= (this.ewdFailureActivationTime.get(key) ?? 0) + 0.3) {
```
Comment (lukecologne) [inline fbw-a32nx/src/systems/systems-host/systems/FWC/PseudoFWC.ts]: The 0.3s should be adjustable per warning, since we already have a few warnings that should have it set to 0

**Review by lukecologne — CHANGES_REQUESTED** [review]

File: fbw-a32nx/src/systems/systems-host/systems/FWC/PseudoFWC.ts (hunk 1 above)
Comment (tracernz) [reply fbw-a32nx/src/systems/systems-host/systems/FWC/PseudoFWC.ts]: That's true. I'll add an optional prop for it. If you have the codes that are 0 I can also do them in this PR, but I don't intend to go check every one.

Comment (tracernz) [reply fbw-a32nx/src/systems/systems-host/systems/FWC/PseudoFWC.ts]: I checked your recent PRs and added this to all of those I found relevant.

File: .github/CHANGELOG.md [hunk 2]
```diff
@@ -101,6 +101,7 @@
 1. [A380X/FMS] Added CHECK MIN FUEL AT DEST & DEST EFOB BELOW MIN message with associated amber EFOB color on MFD pages - @BravoMike99 (bruno_pt99)
 1. [A380X] Fixed wing taxi lights appearing black - @heclak (Heclak)
 1. [A380X] Fixed lighting issues in SU3 - @heclak (Heclak)
+1. [A32NX/FWS] Active warnings are no longer cleared when when entering an inhibited flight phase - @tracernz (Mike)
```
Comment (BravoMike99) [inline .github/CHANGELOG.md]: when when 😄

**Review by lukecologne — APPROVED** [review]
LGTM except the changelog thing above 😄

**Comment by borkxo** [comment]
Quality Assurance Trainee Report

Discord Username  : borkxo
Object of testing : #10259
Aircraft          : A32NX
Simulator         : 2024
Tier of Testing   : 1
Date              : 30/07/2025

Testing Process: 
1. Spawned cold & dark on apron - no master warning
2. Spawned on runway, set TOGA thrust with PARK BRK on - CONFIG Park BRK ON ecam memo displayed and CRC Master Warning heard

Testing Results: 
Passed
