### PR TITLE
fix(A380X/MFD): Changed colors of TCAS modes to match correct colors in A380 FCOM

### LINKED ISSUE #10303: TCAS MODE colour
### Simulator

2020

### Aircraft Version

Development (4k)

### Build info

```json
{
    "built": "2025-08-12T21:47:32+00:00",
    "ref": "refs/heads/master",
    "sha": "1bb6433acd797b50ffdef7d3d2b4dffe5d4bd14b",
    "actor": "BravoMike99",
    "event_name": "manual",
    "pretty_release_name": "master:1bb6433a",
    "version": "a380x-v0.14.0-dev.1bb6433"
}
```

### Describe the bug

The color of TCAS modes ABV and BLW should be blue and not green. 

### Expected behavior

NORM is green but ABV and BLW should be blue. FCOM page for reference.

### Steps to reproduce

Turn on TCAS and look at the SURV page and the color of the TCAS modes.

### References (optional)

Image

### Additional info (optional)

_No response_

### Discord Username (optional)

_No response_

### PR DESCRIPTION
**Pull request by fwillard**
Fixes #10303

## Summary of Changes

Changed the display color of the tcas modes on the A380 Surveillance MFD page to match the correct modes from the FCOM

## Screenshots (if necessary)

{60B3C2A8-C4B0-456D-AC45-435D21E6D784}
{D2DAFF79-AE0F-4787-8ABF-6BCD96EAA4B3}
{FCFED429-AB33-4389-996C-088847375CEA}

## References

Examples from the FCOM
477998696-1de5252b-6bdb-425d-a483-cd4935b9254c
478189044-dd7e4d62-6bb9-4978-be18-30d57cb92e86

## Additional context

Discord username (if different from GitHub): 

## Testing instructions

Load up the A380 and turn on TCAS. Toggle through modes on MFD SURV page and verify correct colors are displayed

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo**, **flybywire-aircraft-a380-842 (4K)** or **flybywire-aircraft-a380-842 (8K)** download link at the bottom of the page

### CODE REVIEW

File: fbw-a380x/src/systems/instruments/src/MFD/pages/SURV/MfdSurvControls.tsx [hunk 1]
```diff
@@ -74,8 +74,14 @@ export class MfdSurvControls extends DisplayComponent<MfdSurvControlsProps> {
   );
 
   private readonly tcasTaraSelectedIndex = Subject.create<number | null>(2);
+  private readonly tcasTaraRadioColor = this.tcasTaraSelectedIndex.map((it) =>
```
Comment (flogross89) [inline fbw-a380x/src/systems/instruments/src/MFD/pages/SURV/MfdSurvControls.tsx:77]: push this subscription to ``this.subs``

File: fbw-a380x/src/systems/instruments/src/MFD/pages/SURV/MfdSurvControls.tsx [hunk 2]
```diff
@@ -74,8 +74,14 @@ export class MfdSurvControls extends DisplayComponent<MfdSurvControlsProps> {
...
+    it === 0 ? RadioButtonColor.Green : RadioButtonColor.White,
+  );
 
   private readonly tcasNormAbvBlwSelectedIndex = Subject.create<number | null>(0);
+  private readonly tcasNormAbvBlwRadioColor = this.tcasNormAbvBlwSelectedIndex.map((it) =>
```
Comment (flogross89) [inline fbw-a380x/src/systems/instruments/src/MFD/pages/SURV/MfdSurvControls.tsx:82]: push this subscription to ``this.subs``

**Review by flogross89 — CHANGES_REQUESTED** [review]
Awesome, thanks a lot! Please remember to always push subscriptions to ``this.subs``, so they can be properly destroyed when leaving the page (as we destroy pages which are not active in the MFD).

**Comment by tracernz** [comment]
The one pic I have on hand is with it on standby.
image

File: fbw-a380x/src/systems/instruments/src/MFD/pages/SURV/MfdSurvControls.tsx (hunk 1 above)
Comment (fwillard) [reply fbw-a380x/src/systems/instruments/src/MFD/pages/SURV/MfdSurvControls.tsx:77]: Fixed

File: fbw-a380x/src/systems/instruments/src/MFD/pages/SURV/MfdSurvControls.tsx (hunk 2 above)
Comment (fwillard) [reply fbw-a380x/src/systems/instruments/src/MFD/pages/SURV/MfdSurvControls.tsx:82]: Fixed

**Review by flogross89 — APPROVED** [review]

**Comment by Jonny23787** [comment]
Quality Assurance Tester Report

Discord Username  : jonny_23
Object of testing : #10304
Aircraft          : A380X
Simulator         : 2020
Tier of Testing   : 1
Date              : 30/08/2025

Testing Process: 

1. Toggled through various TCAS modes, confirmed colours matched the references

Testing Results: 
Passed

**Comment by flogross89** [comment]
@fwillard I resolved the changelog merge conflict for you, PR will merge as soon as GitHub workflow is passed
