### PR TITLE
fix(a380x/sd): fuel values displayed in lbs in cruise page

### LINKED ISSUE #10306: Fuel consumption differ on cruise page and engine page
### Simulator

2020

### Aircraft Version

Development (4k)

### Build info

```json
{
    "built": "2025-08-12T21:47:32+00:00",
    "ref": "refs/heads/master",
    "sha": "1bb6433acd797b50ffdef7d3d2b4dffe5d4bd14b",
    "actor": "BravoMike99",
    "event_name": "manual",
    "pretty_release_name": "master:1bb6433a",
    "version": "a380x-v0.14.0-dev.1bb6433"
}
```

### Describe the bug

The fuel burn is different on the cruise page than on the engine page. The fuel page value agrees with the values from the engine page. The cruise page values seems to be the wrong one.

### Expected behavior

The fuel burn values to be the same.

### Steps to reproduce

1. Start the engines
2. Observe the difference

### References (optional)

Image

Image

Image

### Additional info (optional)

_No response_

### Discord Username (optional)

_No response_

### PR DESCRIPTION
**Pull request by BravoMike99**
Fixes #10306 

## Summary of Changes

Fixes regression in cruise SD page where the fuel values were wrongly displayed in LBS.
## Additional context

Discord username (if different from GitHub): bruno_pt99

## Testing instructions

Verify fuel used and fuel flow values displayed on the SD cruise page match the actual values and that they roughly match the fuel SD values.

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo**, **flybywire-aircraft-a380-842 (4K)** or **flybywire-aircraft-a380-842 (8K)** download link at the bottom of the page

### CODE REVIEW

File: fbw-a380x/src/systems/instruments/src/SDv2/Pages/Cruise/CruisePage.tsx [hunk 1]
```diff
@@ -42,15 +44,15 @@ export class CruisePage extends DestroyableComponent<SdPageProps> {
   ];
 
   private readonly enginesFuelUsedDisplay = this.enginesFuelUsed.map((fu) =>
-    fu.map((v) => fuelForDisplay(v, this.usingMetric, 5).toFixed(0)),
+    fu.map((v) => fuelForDisplay(v, this.usingMetric.get(), 1, 5).toFixed(0)),
```
Comment (flogross89) [inline fbw-a380x/src/systems/instruments/src/SDv2/Pages/Cruise/CruisePage.tsx:47]: Maybe we should use a MappedSubject with `fu` and `this.usingMetric` here?

File: fbw-a380x/src/systems/instruments/src/SDv2/Pages/Cruise/CruisePage.tsx [hunk 2]
```diff
@@ -42,15 +44,15 @@ export class CruisePage extends DestroyableComponent<SdPageProps> {
...
   );
   private readonly engineTotalFuelUsedDisplay = MappedSubject.create(
-    (fu) => (parseInt(fu[0]) + parseInt(fu[1]) + parseInt(fu[2]) + parseInt(fu[3])).toFixed(0),
+    (fu) => parseInt(fu[0]) + parseInt(fu[1]) + parseInt(fu[2]) + parseInt(fu[3]),
     ...this.enginesFuelUsedDisplay,
   );
 
   private readonly enginesFuelFlowDisplay = this.enginesFuelFlow.map((fu) =>
-    fu.map((v) => fuelForDisplay(v, this.usingMetric).toFixed(0)),
+    fu.map((v) => fuelForDisplay(v, this.usingMetric.get()).toFixed(0)),
```
Comment (flogross89) [inline fbw-a380x/src/systems/instruments/src/SDv2/Pages/Cruise/CruisePage.tsx:55]: same here

**Review by flogross89 — CHANGES_REQUESTED** [review]

File: fbw-a380x/src/systems/instruments/src/SDv2/Pages/Cruise/CruisePage.tsx [hunk 3]
```diff
@@ -42,15 +44,15 @@ export class CruisePage extends DestroyableComponent<SdPageProps> {
   ];
 
   private readonly enginesFuelUsedDisplay = this.enginesFuelUsed.map((fu) =>
```
Comment (Benjozork) [inline fbw-a380x/src/systems/instruments/src/SDv2/Pages/Cruise/CruisePage.tsx:46]: FYI, `enginesFuelUsed` has leaked subscriptions (the consumer subjects). I can't leave comments on those lines for some reason.

Those subscriptions should be added to be paused / resumed (of applicable) and destroyed with the component.

**Review by Benjozork — DISMISSED** [review]

**Comment by Benjozork** [comment]
Btw, why do we keep both the SD and SDv2 pages around?

**Comment by Jonny23787** [comment]
There is no need, in PR #10185 I have deleted the SD cruise page. It isn't merged yet however.

File: fbw-a380x/src/systems/instruments/src/SDv2/Pages/Cruise/CruisePage.tsx (hunk 3 above)
Comment (BravoMike99) [reply fbw-a380x/src/systems/instruments/src/SDv2/Pages/Cruise/CruisePage.tsx:46]: Is it leaking due to the spread operator? As they are added to the subscription array

File: fbw-a380x/src/systems/instruments/src/SDv2/Pages/Cruise/CruisePage.tsx (hunk 1 above)
Comment (BravoMike99) [reply fbw-a380x/src/systems/instruments/src/SDv2/Pages/Cruise/CruisePage.tsx:47]: I have been trying to get it to work using a mapped subject but it seems to get quite messy with the consumer subject array & the boolean value due to the types, unless you have a proposal in mind?

File: fbw-a380x/src/systems/instruments/src/SD/Pages/Cruise/CruisePage.tsx
Comment (flogross89) [inline fbw-a380x/src/systems/instruments/src/SD/Pages/Cruise/CruisePage.tsx:1]: we could theoretically indeed remove the cruise page from the legacy SD

File: fbw-a380x/src/systems/instruments/src/SDv2/Pages/Cruise/CruisePage.tsx (hunk 1 above)
Comment (flogross89) [reply fbw-a380x/src/systems/instruments/src/SDv2/Pages/Cruise/CruisePage.tsx:47]: Hmm yeah then keep it as is, I was unsure whether using .get() worked here but if it does I'm fine with it.

File: fbw-a380x/src/systems/instruments/src/SD/Pages/Cruise/CruisePage.tsx
Comment (BravoMike99) [reply fbw-a380x/src/systems/instruments/src/SD/Pages/Cruise/CruisePage.tsx:1]: Didn't remove it after Holland's comment due to the mention of one PR but since its not ready yet and you are the second to ask I just removed it

Comment (flogross89) [reply fbw-a380x/src/systems/instruments/src/SD/Pages/Cruise/CruisePage.tsx:1]: I'm indifferent we also could've done it in a separate PR but rather have it out fast :)

**Review by flogross89 — APPROVED** [review]

**Comment by borkxo** [comment]
Quality Assurance Trainee Report

Discord Username  : borkxo
Object of testing : #10327
Aircraft          : A380X
Simulator         : 2024
Tier of Testing   : 1
Date              : 08/10/2025

Testing Process: 
1. Spawned on runway, set aircraft to use metric
2. Climbed to FL180, stayed there for a couple minutes, then descended to FL100 while monitoring FU & FF on SD pages - FF figure matches on CRZ & ENG, while FU on FUEL lags slightly behind CRZ. ALL ENG FF in FUEL roughly matches FF on CRZ & ENG.

Testing Results: 
Passed

**Comment by flogross89** [comment]
@BravoMike99 can we merge this?

File: fbw-a380x/src/systems/instruments/src/SDv2/Pages/Cruise/CruisePage.tsx (hunk 3 above)
Comment (Benjozork) [reply fbw-a380x/src/systems/instruments/src/SDv2/Pages/Cruise/CruisePage.tsx:46]: You are right. I did not see that they were added elsewhere.

MSFS 2024 `msfs-sdk` is much nicer about this lol. Can't wait for it.
