### PR TITLE
fix(a380x/pfd): Fix PFD DU / ND DU brightness knobs

### LINKED ISSUE #9420: Left PFD DU and Left ND DU control on off state of Right PFD DU and Right ND DU.
### Aircraft Version

Stable

### Build info

```json
{
    "built": "2024-11-02T19:03:34+00:00",
    "ref": "refs/tags/v0.12.1",
    "sha": "2776100c286d3723826c62df36dc48207657d937",
    "actor": "Benjozork",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.1",
    "version": "a380x-v0.12.1-rel.2776100"
}
```

### Describe the bug

The Left PFD DU and Left ND DU also control the on and off state of the Right PFD DU and Right ND DU but does not control the brightness.

### Expected behavior

The Left PFD DU and Left ND DU should not control the Right PFD DU and Right ND DU

### Steps to reproduce

Load into A380X
Turn on the plane
Turn Left PFD DU and Left ND DU knob to the off position
Look at Right PFD DU and Right ND DU

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

Awemeter

### PR DESCRIPTION
**Pull request by MichelZ**
Fixes #9420

## Summary of Changes
I have changed the displayUnitID based on the side of the display

## Additional context

Discord username (if different from GitHub): FragKing

## Testing instructions
Turn the left PFD DU knob all the way down and make sure only the left display turns the brightness down.
Do the same on the right same for the right display
Do the same on the left side for the ND DU knob
Do the same on the right side for the ND DU knob

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo**, **flybywire-aircraft-a380-842 (4K)** or **flybywire-aircraft-a380-842 (8K)** download link at the bottom of the page

### CODE REVIEW

File: fbw-a380x/src/systems/instruments/src/ND/instrument.tsx [hunk 1]
```diff
@@ -244,7 +244,7 @@ class NDInstrument implements FsInstrument {
       <div ref={this.topRef}>
         <CdsDisplayUnit
           bus={this.bus}
-          displayUnitId={DisplayUnitID.CaptNd}
+          displayUnitId={this.efisSide == 'L' ? DisplayUnitID.CaptNd : DisplayUnitID.FoNd}
```
Comment (Benjozork) [inline fbw-a380x/src/systems/instruments/src/ND/instrument.tsx:247]: Can we use `getDisplayIndex()` here too to be consistent?

Comment (MichelZ) [reply fbw-a380x/src/systems/instruments/src/ND/instrument.tsx]: Fixed.

**Review by Benjozork — APPROVED** [review]

**Comment by BravoMike99** [comment]
Quality Assurance Tester/Trainee Report

Discord Username  : bruno_pt99 
Object of testing : #9650  
Aircraft          : A380X 
Tier of Testing   : 1
Date              : 14/12/2024 

Testing Process: 
Changed brightness levels of PFD & ND displays on both sides. 
Observed the brightness updates accordingly on the associated display ✔️ 

Testing Results: 
Passed

Media:

image
