### PR TITLE
fix(a380x): Improve engine out behavior in FG and FMS

### LINKED ISSUE #10265: [A380X] Erroneous transition to CLB/OP CLB for OEI of engine 3 or 4
### Simulator

2020

### Aircraft Version

Development (4k)

### Build info

```json
master
```

### Describe the bug

For engine-out scenarios with engine 3 or 4, FG vertical mode transitions from SRS to CLB or OP CLB if engine out occurs during take-off after V1. 

### Expected behavior

Vertical mode should stay in SRS, and not transition to CLB or OP CLB

### Steps to reproduce

Set up a/c for take-off, fail engine 3 or 4 shortly after V1, rotate, continue according to FCTM. 

### References (optional)

https://www.youtube.com/watch?v=jWq2Zc8U1bA

### Additional info (optional)

Found the bug in the AP state machine: Only the conditions for engine 1 and 2 are being checked (carry-over bug from a32nx).
Correct behavior reproduced for engines 1&2

### Discord Username (optional)

floridude

### PR DESCRIPTION
**Pull request by flogross89**
Fixes #10265 

## Summary of Changes

Note to reviewers: Only change for FBW C++ code was adding engines 3&4 to existing code.

- Adds thrust lever 3&4 and engine operative status 3&4 to Autopilot state machine to fix SRS transition
- Adds several EO and batch 7 indications to FMS (title bar, CLEAR EO for PERF page, EO MAX for PERF page)
- Add EO behavior to FMS according to references (out of scope: drift down altitude, proper performance figures for EO MAX)
- Add cost index mode selector dropdown to PERF, INIT, FUEL&LOAD pages

## Screenshots (if necessary)

image

## References

image

## Additional context

Discord username (if different from GitHub): floridude

## Testing instructions

1. Set up aircraft for full flight, can be a short one
2. Take-off, during take-off after/around V1 run fail engine 3 or 4 (up to you), e.g. by switching the engine master switch to off
3. FMA vertical mode should remain in SRS, and **not** switch over to OP CLB or CLB once passing the thrust reduction altitude. 
4. FMS should display "EO" indications (see screenshots), and behave according to the above FCOM reference
5. You should be able to manually clear the EO condition via the FMS/ACTIVE/PERF pages, try that. 
6. Start up the failed engine again, when it runs fail it again --> FMS should display EO condition again
7. Start up the failed engine --> EO indication should disappear. 

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo**, **flybywire-aircraft-a380-842 (4K)** or **flybywire-aircraft-a380-842 (8K)** download link at the bottom of the page

### CODE REVIEW

**Comment by BravoMike99** [comment]
Just a general comment, if the dropdown is added to the PERF pages shouldn't we add it to the INIT page too? 
Captura de ecrã 2025-07-29 092717

File: fbw-a380x/src/systems/instruments/src/MFD/FMC/FmcAircraftInterface.ts [hunk 1]
```diff
@@ -915,6 +923,19 @@ export class FmcAircraftInterface {
...
+
+          // EO handling
+          if (!this.fmgc.isAllEngineOn()) {
+            const verticalMode = this.fmaVerticalMode.get();
+            const greenDotSpeed = this.fmgc.data.greenDotSpeed.get();
+            if ((verticalMode === VerticalMode.OP_CLB || verticalMode === VerticalMode.CLB) && greenDotSpeed) {
+              // New speed target is GDOT (EO-GDOT), but it ramps down by 1kt per second
+              const casWord = ADIRS.getCalibratedAirspeed();
+              const cas = casWord && casWord.isNormalOperation() ? casWord.value : null;
+              speed = cas ? cas - (cas - greenDotSpeed) * (FMS_CYCLE_TIME / 1_000) : greenDotSpeed;
```
Comment (BravoMike99) [inline fbw-a380x/src/systems/instruments/src/MFD/FMC/FmcAircraftInterface.ts:944]: I think we shouldn't check for constraints after. GDOT seems to have prioirty in CLB/OP_CLB

File: fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/MfdFmsPerf.tsx [hunk 2]
```diff
@@ -1679,13 +1722,25 @@ export class MfdFmsPerf extends FmsPage<MfdFmsPerfProps> {
                 {/* CLB */}
                 <div style="display: flex; justify-content: space-between;">
                   <div class="mfd-label-value-container" style="padding: 15px; margin-bottom: 15px;">
+                    <DropdownMenu
```
Comment (BravoMike99) [inline fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/MfdFmsPerf.tsx:1722]: I think the position needs to be slightly adjusted, looks like it should be aligned to the left (sorry for being picky). If then there's other elements which look out of place/have the wrong position in relation to the mode box then we can leave it as is I guess.
image

File: fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/MfdFmsPerf.tsx [hunk 3]
```diff
@@ -2858,6 +2956,22 @@ export class MfdFmsPerf extends FmsPage<MfdFmsPerfProps> {
               <div>
                 <Button label="POS MONITOR" onClick={() => console.log('POS MONITOR')} />
               </div>
+              <div ref={this.clearEoButton} style="margin-right: 5px;">
```
Comment (BravoMike99) [inline fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/MfdFmsPerf.tsx]: Couldn't we affect the visibility directly here in its definition (like the confirmation dialog)? Would make it more explicit that it is being changed.

File: fbw-a380x/src/systems/instruments/src/MFD/FMC/FmcAircraftInterface.ts (hunk 1 above)
Comment (flogross89) [reply fbw-a380x/src/systems/instruments/src/MFD/FMC/FmcAircraftInterface.ts:944]: Look at your ref image below, doesn’t it say MANAGED/SPD CSTR?

Comment (BravoMike99) [reply fbw-a380x/src/systems/instruments/src/MFD/FMC/FmcAircraftInterface.ts:944]: Yes because its in ALT. In open climb/climb the constraints are ignored.

File: fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/MfdFmsPerf.tsx (hunk 3 above)
Comment (flogross89) [reply fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/MfdFmsPerf.tsx]: done

File: fbw-a380x/src/systems/instruments/src/MFD/FMC/FmcAircraftInterface.ts (hunk 1 above)
Comment (flogross89) [reply fbw-a380x/src/systems/instruments/src/MFD/FMC/FmcAircraftInterface.ts:944]: Alright, changed that

File: fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/MfdFmsPerf.tsx (hunk 2 above)
Comment (flogross89) [reply fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/MfdFmsPerf.tsx:1722]: also done

**Review by BravoMike99 — APPROVED** [review]

**Comment by ghostxyz990** [comment]
Quality Assurance Trainee Report

Discord Username  : adb_1872
Object of testing : #10268  
Aircraft          : A380X 
Simulator         : 2020 
Tier of Testing   : 1
Date              : 06/08/2025 

Testing Process: 
1. Spawned on the runway, prepped aircraft and FMS for a short flight.
2. Failed engine 4 after V1, rotated at VR.
3. On passing THR RED height, FMA stayed in SRS as expected.
4. Verified FMS showed EO indications and behaved according to the FCOM screenshot given
5. CLEAR EO button on the perf page worked as expected, EO condition was cleared,
6. Started and failed the same engine number 4 again, EO condition appeared again on the FMS as expected.
7. Started engine number 4 again, EO condition disappeared.

Testing Results: 
Passed  

Negatives:
Slight delay between failing the engine again and the EO condition appearing on the FMS again, although I'm not sure if this is expected.

**Comment by flogross89** [comment]
@ghostxyz990 Thanks a lot for the test! How big was the delay for the second time? The N2 has to go below 20% and you have to be off the ground, so maybe that is why it was sensed a bit late.

**Comment by ghostxyz990** [comment]
Ahh I see, I'd say it was about 25 seconds from master off to EO appearing, if you like I can try again and check the N2 value, but its probably correct in that case.

**Comment by flogross89** [comment]
@ghostxyz990 Thats alright then, it’s somewhere in the ballpark I would assume :-) Once we have a proper FADEC those conditions will be improved anyways
