### PR TITLE
fix(a380x/SD): Hook up door SD page to door status

### LINKED ISSUE #8996: a380x: SD door page indications do not match door state
### Aircraft Version

Development

### Build info

```json
master
```

### Describe the bug

ECAM SD for doors does not seem to reflect the actual doors position, they all stay green all the time.

### Expected behavior

Open doors should show as amber.

### Steps to reproduce

1) Open one door via the EFB such as 1L.
2) Observe the SD door page

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

bruno_pt99

### PR DESCRIPTION
**Pull request by BravoMike99**
Fixes #8996 
## Summary of Changes

Hooks up the door SD page to door status & fixes the positioning of the door open text.
## Additional context

Discord username (if different from GitHub):
bruno_pt99
## Testing instructions

Popup the DOOR SD page on the lower ecam.
Open a main door and a cargo door of your choice through the EFB. The associated door icon should show as amber on the DOOR SD page.
Turn the beacon light on. "S" should appear next to the closed main doors.
Start an engine, once the engine is running a yellow amber text should appear next to the open doors.

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo** or **flybywire-aircraft-a380-842** download link at the bottom of the page

### CODE REVIEW

File: fbw-a380x/src/systems/instruments/src/SD/Pages/Doors/elements/CargoDoor.tsx [hunk 1]
```diff
@@ -1,8 +1,9 @@
+import { useSimVar } from '@flybywiresim/fbw-sdk';
 import { Position, CargoDoorProps } from '@instruments/common/types';
 import React from 'react';
 
-const CargoDoor: React.FC<Position & CargoDoorProps> = ({ x, y, label, width, height, engineRunning }) => {
-  const doorOpen = false;
+const CargoDoor: React.FC<Position & CargoDoorProps> = ({ x, y, label, identifier, width, height, engineRunning }) => {
+  const doorOpen = identifier ? !useSimVar(`L:A32NX_${identifier}_DOOR_CARGO_LOCKED`, 'bool', 1000)[0] : false;
```
Comment (Benjozork) [inline fbw-a380x/src/systems/instruments/src/SD/Pages/Doors/elements/CargoDoor.tsx:6]: **issue:** React hooks should not be called conditionally.

**Review by 2hwk — APPROVED** [review]

**Comment by 2hwk** [comment]
Quality Assurance Report

Discord Username  : 2cas
Object of testing : #9077
Aircraft          : A380X
Tier of Testing   : 1
Date              : 20/10/2024

Testing Process: 

 - [x] Popup the DOOR SD page on the lower ecam.
- [x] Open a main door and a cargo door of your choice through the EFB. The associated door icon should show as amber on the DOOR SD page.
- [x] Manually opened doors in the main cabin deck, associated door is orange in the SD Door page
- [x] Turn the beacon light on. "S" should appear next to the closed main doors.
-[x] Start an engine, once the engine is running a yellow amber text should appear next to the open doors.

Negatives:
 - N/A

Testing Results: 
Passed
