### PR TITLE
fix(a380): Fix T/D prediction in PERF CRZ & add T/D reached

### LINKED ISSUE #8990: a380x/mfd: Perf page ETA format incorrect
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-09-26T14:59:07+00:00",
    "ref": "refs/heads/master",
    "sha": "341b9c3efaa7e452132ed6b994c5772ed3e4a2cd",
    "actor": "crocket63",
    "event_name": "manual",
    "pretty_release_name": "master:341b9c3e",
    "version": "a380x-v0.12.0-dev.341b9c3"
}
```

### Describe the bug

ETA prediction on the PERF CRZ & approach phase are shown in remaining flight time.

### Expected behavior

Eta prediction should be the expected time of arrival after the preflight phase, as long as a valid UTC time is present. Only if no valid clock time is available it should revert to remaining flight time.

### Steps to reproduce

1) Observe the ETA prediction on the PERF CRZ or PERF DES pages during flight.

### References (optional)

FCOM

### Additional info (optional)

_No response_

### Discord Username (optional)

bruno_pt99

### PR DESCRIPTION
**Pull request by BravoMike99**
Fixes #8990

## Summary of Changes

Changes time prediction in PERF page to show the ETA instead of remaining flight time if flight phase is not preflight.
Adds T/D prediction to PERF Cruise page.
Adds T/D Reached message to both PFD and MFD.
PFD code cleanup (remove non applicable messages) & some scratch pad messages were reworded to match a380.
## Screenshots (if necessary)

Pred
TD REACHED

## Additional context

Discord username (if different from GitHub):
bruno_pt99
## Testing instructions

1) Initialize all data in the FMS
2) Observe the ETA in the PERF CRZ or PERF DES pages before takeoff. It should indicate the total flight time. 
3) After takeoff observe the same prediction as 2). It should now indicate the ETA at the destination.
4) Once in cruise flight, verify that the T/D distance and time predictions are available on the MFD on the PERF CRZ Page.
5) While flying in managed speed, don't initiate a descend after passing the T/D. "T/D REACHED" message should appear on both PFD & MFD.
6) Clear the scratchpad message which should make it disappear from both displays.
6.1) Do the same as 5) but initiate a descent instead of manually clearing the message. Once that happens, the message should disappear from both displays.

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo** or **flybywire-aircraft-a380-842** download link at the bottom of the page

### CODE REVIEW

**Review by 2hwk — APPROVED** [review]

File: fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/MfdFmsPerf.tsx [hunk 1]
```diff
@@ -898,10 +899,15 @@ export class MfdFmsPerf extends FmsPage<MfdFmsPerfProps> {
...
           if (destPred?.secondsFromPresent !== undefined) {
-            this.destEta.set(new TimeHHMMFormat().format(destPred.secondsFromPresent / 60)[0] ?? '--:--');
-            this.destEfob.set(this.props.fmcService.master?.fmgc.getDestEFOB(true).toFixed(1) ?? '--.-');
+            destEta = getEtaUtcOrFromPresent(
+              destPred.secondsFromPresent,
+              this.activeFlightPhase.get() == FmgcFlightPhase.Preflight,
+            );
           }
+          this.destEta.set(destEta);
+          this.destEfob.set(this.props.fmcService.master?.fmgc.getDestEFOB(true).toFixed(1) ?? '--.-');
```
Comment (2hwk) [inline fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/MfdFmsPerf.tsx:910]:
```
'--.-'
```

Just checking that this is intentional vs --.--, else LGTM

Comment (BravoMike99) [reply fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/MfdFmsPerf.tsx]: Yes that's fine as it is the fuel on board but I updated it to be '---.-' now here & other pages as they seem to use 3 dashes on the A380 for fuel figures. 
image

**Comment by 2hwk** [comment]
Quality Assurance Tester Report

Discord Username: 2cas
Object of testing: #9284
Aircraft: A380X
Tier of Testing: 1
Date: 13/11/2024 

Testing Process: 
- [x] Initialize all data in the FMS
- [x] Observe the ETA in the PERF CRZ or PERF DES pages before takeoff. It should indicate the total flight time.
- [x] After takeoff observe the same prediction as 2). It should now indicate the ETA at the destination.
- [x] Once in cruise flight, verify that the T/D distance and time predictions are available on the MFD on the PERF CRZ Page.
- [x] While flying in managed speed, don't initiate a descend after passing the T/D. "T/D REACHED" message should appear on both PFD & MFD.
- [x] Clear the scratchpad message which should make it disappear from both displays.
- [x] 6.1) Do the same as 5) but initiate a descent instead of manually clearing the message. Once that happens, the message should disappear from both displays.


Testing Results: 
- QA Passed

Negatives:
- N/A

Conclusions: 
- LGTM
