### PR TITLE
fix(a380x): spawn states - XPDR, switches and payload + misc fixes

### LINKED ISSUE #8936: [A380X] runway.flt preset not fully configured for take-off
### Aircraft Version

Development

### Build info

```json
master
```

### Describe the bug

Make sure that T.O memo is green (fix flaps, signs, and potentially more)
Important for newbie users

### Expected behavior

-

### Steps to reproduce

-

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

floridude

### PR DESCRIPTION
**Pull request by 2hwk**
Fixes #8936

## Summary of Changes

- Spawn on runway with payload, THS, XPDR auto and TCAS set to TARA. 
- Fixes APU Master PB and APU Start PB not having emissive when APU BAT is on.

## Additional context

Discord username (if different from GitHub):

## Testing instructions

- Spawn on any runway and ensure that:
   - XPDR is in AUTO and not STBY
   - TCAS is at TA/RA and NORMAL
   - Default CG% is around 40%
   - THS is in the green area
   - Ground Spoilers are Armed
 
Note: V-Speeds, other PERF related inputs and FMS still have to be initialized by the user. 

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo** or **flybywire-aircraft-a380-842** download link at the bottom of the page

### CODE REVIEW

File: fbw-a380x/src/systems/extras-host/modules/flt_sync/LoadFltStateManager.ts [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+      case FltState.Runway:
+      case FltState.Climb:
+      case FltState.Cruise:
+      case FltState.Approach:
+      case FltState.Final:
+      default:
+        this.bus.getPublisher<MfdSurvEvents>().pub('mfd_xpdr_set_auto', true, true);
+        this.bus.getPublisher<MfdSurvEvents>().pub('tcas_alert_level', TcasMode.TARA, true);
+        break;
+    }
```
Comment (tracernz) [inline fbw-a380x/src/systems/extras-host/modules/flt_sync/LoadFltStateManager.ts:48]: It would be a lot simpler to let each subsytem do this itself rather than publishing bus events from a random location.

File: fbw-a380x/src/systems/instruments/src/MsfsAvionicsCommon/providers/MfdSurvPublisher.ts [hunk 2]
```diff
@@ -6,8 +6,12 @@
...
-    /** (MFD SURV -> RMP) Altitude reporting ON/OFF */
-    mfd_xpdr_set_alt_reporting: boolean,
+  /** (MFD SURV -> RMP) Is AUTO (true) or STBY (false). */
+  mfd_xpdr_set_auto: boolean;
+  /** (MFD SURV -> RMP) Altitude reporting ON/OFF */
+  mfd_xpdr_set_alt_reporting: boolean;
+  /** (MFD SURV -> TCAS) TCAS Alert Level 0 - STBY | 1 - TA ONLY | 2 - TARA */
+  tcas_alert_level: number;
+  /** (MFD SURV -> TCAS) TCAS Alt Select 0 - NORM | 1 - ABV | 2 - BLW */
+  tcas_alt_select: number;
```
Comment (tracernz) [inline fbw-a380x/src/systems/instruments/src/MsfsAvionicsCommon/providers/MfdSurvPublisher.ts:16]: These should at least have `mfd_` prefix to identify the publisher and avoid conflicts.

File: fbw-a380x/src/systems/instruments/src/MFD/pages/SURV/MfdSurvControls.tsx [hunk 3]
```diff
@@ -250,21 +253,23 @@ export class MfdSurvControls extends DisplayComponent<MfdSurvControlsProps> {
               <div class="mfd-surv-controls-tcas-left">
                 <RadioButtonGroup
                   values={['TA/RA', 'TA ONLY', 'STBY']}
+                  onModified={(val) =>
+                    this.props.bus.getPublisher<MfdSurvEvents>().pub('tcas_alert_level', 2 - val, true)
+                  }
                   selectedIndex={this.tcasTaraSelectedIndex}
```
Comment (tracernz) [inline fbw-a380x/src/systems/instruments/src/MFD/pages/SURV/MfdSurvControls.tsx:259]: It would be a lot safer to subscribe to `this.tcasTaraSelectedIndex`, in case it is also mutated by some other means. This has a high chance of being a bug in future.

File: fbw-a380x/src/systems/instruments/src/MFD/pages/SURV/MfdSurvControls.tsx [hunk 4]
```diff
@@ -250,21 +253,23 @@ export class MfdSurvControls extends DisplayComponent<MfdSurvControlsProps> {
...
                   additionalVerticalSpacing={10}
                   color={Subject.create('green')}
-                  valuesDisabled={Subject.create(Array(3).fill(true))}
                 />
               </div>
               <div class="mfd-surv-controls-tcas-right">
                 <RadioButtonGroup
                   values={['NORM', 'ABV', 'BLW']}
                   selectedIndex={this.tcasNormAbvBlwSelectedIndex}
+                  onModified={(val) => this.props.bus.getPublisher<MfdSurvEvents>().pub('tcas_alt_select', val, true)}
```
Comment (tracernz) [inline fbw-a380x/src/systems/instruments/src/MFD/pages/SURV/MfdSurvControls.tsx:269]: As above, but sub to this.tcasNormAbvBlwSelectedIndex.

File: fbw-a380x/src/systems/extras-host/modules/flt_sync/LoadFltStateManager.ts (hunk 1 above)
Comment (2hwk) [reply fbw-a380x/src/systems/extras-host/modules/flt_sync/LoadFltStateManager.ts:48]: I've now moved it into Transponder.ts and LegacyTcasComputer.ts, but, this still isn't perfect. It's not immediately obvious to other devs that this event is being manipulated based on spawn state if you are working on a subsystem that is dependent on the XPDR and TCAS computer (Like the MFD SURV page).

Note that If we wish to support .FLT loading from saves and more advanced state management in the future, it would make sense to revisit this then.

File: fbw-a380x/src/systems/instruments/src/MFD/pages/SURV/MfdSurvControls.tsx (hunk 4 above)
Comment (2hwk) [reply fbw-a380x/src/systems/instruments/src/MFD/pages/SURV/MfdSurvControls.tsx:269]: Should be in the TCAS PR, also there is a bug there that I wasn't able to solve with this change, so it's not done yet.

File: fbw-a380x/src/systems/systems-host/systems/Communications/Transponder.ts [hunk 5]
```diff
@@ -68,6 +68,20 @@ export class Transponder implements Instrument {
...
+          break;
+        case FltState.Taxi:
+        case FltState.Runway:
+        case FltState.Climb:
+        case FltState.Cruise:
+        case FltState.Approach:
+        case FltState.Final:
+        default:
+          this.bus.getPublisher<MfdSurvEvents>().pub('mfd_xpdr_set_auto', true, true);
+          break;
```
Comment (tracernz) [inline fbw-a380x/src/systems/systems-host/systems/Communications/Transponder.ts:83]: You can just use the cold and dark start Lvar for this like all the other systems :P.

Comment (2hwk) [reply fbw-a380x/src/systems/systems-host/systems/Communications/Transponder.ts:83]: That's not as fun! but I'll refactor

**Review by tracernz — APPROVED** [review]

**Comment by flogross89** [comment]
@2hwk Please add test instructions

**Comment by pilotseyea350** [comment]
Quality Assurance Tester Report

Discord Username  : PilotEyesA350 
Object of testing : #8982 
Aircraft          : A380X 
Tier of Testing   : 1
Date              : 16/10/2024

Testing Process: 
1. Spawn at LFPG on runway 26L
2. Verify that XPDR is on STBY
3. Verify that TCAS is in TA/RA and in NORM
4. Check GWCG is around 40% (was 39.6%)
5. Check THS is in green range
6. Check spoilers are armed 

Testing Results: 
Passed 

Negatives:       
N/A

Conclusions: 
N/A

Media:
N/A
