### PR TITLE
fix(a380x/nd): Update ND and VD Range Change Messages

### LINKED ISSUE #9473: ND range change messages are incorrect
### Aircraft Version

Stable

### Build info

```json
N/A
```

### Describe the bug

ND says "RANGE CHANGE"
VD has no message

### Expected behavior

ND should say "ND RANGE CHANGE"
VD should say "VD RANGE CHANGE"

### Steps to reproduce

1. Load up aircraft
2. Change ND range
3. Observe

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

_No response_

### PR DESCRIPTION
**Pull request by MrJigs7**
Fixes #9473 

## Summary of Changes

Updated Range Change flag to use a prop and defined relevant values for both A32NX and A380X
Added CSS class for A380X as ND RANGE CHANGE message is different font size and position
Added VD Range Change message

## Screenshots (if necessary)

A320 Range Change
A320RangeChange
A380 ND Range Change
A380NDRangeChange
A380 VD Range Change
A380VDRangeChange
A320 Mode Change
A320ModeChange
A380 Mode Change
A380NDModeChange

## References

A320RangeChangeReference
A380NDRangeChangeRef1
VDRangeChangeRef1
VDRangeChangeRef2
A380NDModeChangeRef1
A380VDRangeChangeRef3

## Additional context

Discord username (if different from GitHub): MrJigs.

## Testing instructions

1. Load A380X in powered state
2. Change EFIS range setting
3. Observe ND for correct messages displayed on both ND and VD
4. Load A32NX in powered state
5. Observe no changes

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo**, **flybywire-aircraft-a380-842 (4K)** or **flybywire-aircraft-a380-842 (8K)** download link at the bottom of the page

### CODE REVIEW

**Comment by MrJigs7** [comment]
Could someone possibly assist with some guidance on the VD Range Change part of this PR? Currently the text is always visible even though I set a initial defaul value of 0, assuming that would be falsy, before I try to capture the ndRangeSetting change event.

**Comment by BravoMike99** [comment]
> Could someone possibly assist with some guidance on the VD Range Change part of this PR? Currently the text is always visible even though I set a initial defaul value of 0, assuming that would be falsy, before I try to capture the ndRangeSetting change event.

You probably need to use a boolean to drive the visibility of the message and whenever the range is changed, set that to true and after a timeout set it to false. You can take the logic of the message on the ND for some inspiration as it behaves like this.
Btw if you'd like you could also change the MODE change message on this PR, it's ND MODE CHANGE on the A380.

File: fbw-a380x/src/systems/instruments/src/ND/VerticalDisplay.tsx [hunk 1]
```diff
@@ -47,6 +48,8 @@ export class VerticalDisplayDummy extends DisplayComponent<VerticalDisplayProps>
     (r) => a380EfisRangeSettings[r],
   );
 
+  private readonly RangeChangeInProgress = ConsumerSubject.create(this.sub.on('set_range_change').whenChanged(), false);
```
Comment (flogross89) [inline fbw-a380x/src/systems/instruments/src/ND/VerticalDisplay.tsx:51]:
```suggestion
  private readonly rangeChangeInProgress = ConsumerSubject.create(this.sub.on('set_range_change').whenChanged(), false);
```
camelCase please

File: fbw-a380x/src/systems/instruments/src/ND/VerticalDisplay.tsx [hunk 2]
```diff
@@ -189,6 +192,11 @@ export class VerticalDisplayDummy extends DisplayComponent<VerticalDisplayProps>
             FL
           </text>
         </g>
+        <g visibility={this.RangeChangeInProgress.map((it) => (it ? 'visible' : 'hidden'))}>
```
Comment (flogross89) [inline fbw-a380x/src/systems/instruments/src/ND/VerticalDisplay.tsx:195]:
```suggestion
        <g visibility={this.rangeChangeInProgress.map((it) => (it ? 'visible' : 'hidden'))}>
```

File: fbw-a380x/src/systems/instruments/src/ND/style.scss [hunk 3]
```diff
@@ -34,3 +34,8 @@
 .a380xInvisible {
   display: none;
 }
+
+.a380xModeRangeChange {
```
Comment (flogross89) [inline fbw-a380x/src/systems/instruments/src/ND/style.scss:38]: We should avoid aircraft-type specific CSS class names. You can use e.g. `.mode-range-change`, and define them differently in the respective aircraft's style.scss. 
This means you would also have to add that class to the a32nx style.scss

**Review by flogross89 — CHANGES_REQUESTED** [review]
Thanks for the PR! And apologies for the late review.

File: fbw-a380x/src/systems/instruments/src/ND/VerticalDisplay.tsx (hunk 1 above)
Comment (MrJigs7) [reply fbw-a380x/src/systems/instruments/src/ND/VerticalDisplay.tsx]: Fixed

File: fbw-a380x/src/systems/instruments/src/ND/VerticalDisplay.tsx (hunk 2 above)
Comment (MrJigs7) [reply fbw-a380x/src/systems/instruments/src/ND/VerticalDisplay.tsx]: Fixed

File: fbw-a380x/src/systems/instruments/src/ND/style.scss (hunk 3 above)
Comment (MrJigs7) [reply fbw-a380x/src/systems/instruments/src/ND/style.scss]: Updated to use non-aircraft specific class, thanks!

**Review by flogross89 — APPROVED** [review]
Thanks! Please resolve the conflict and then we can start QA :)

**Comment by MrJigs7** [comment]
> Thanks! Please resolve the conflict and then we can start QA :)

Done :)

**Comment by utkrishtm** [comment]
Quality Assurance Trainee Report

Discord Username  : utkrishtm
Object of testing : #9739
Aircraft          : A32NX/A380X
Tier of Testing   : 1
Date              : 11/02/2025

Testing Process: 
	- Loaded up into the sim with the powered config from efb. Aligned the IRS and move the range selectors and mode selectors

A380X:
	- The range selector looks fine. 
	- I could not get the message for ND MODE CHANGE all the time, as all modes which also changed the range, became ND RANGE CHANGE.
		- I was able to get the ND MODE CHANGE once by putting the range at 10 in PLAN mode and then change the mode to ARC

A32NX:
	- Everything works as expected, except the items listed in the negative section.


Testing Results: 
Not Passed

Negatives:      
A380X: 
- There should be a way to distinguish between mode and range. If mode is getting change the message should be ND MODE CHANGE even if the mode changes the range. 
- When changing from NAV to VOR and then VOR to LS no ND MODE CHANGE message. Also no message from LS to VOR. VOR to NAV, message does come.

A32NX:
- When changing from NAV to VOR and then VOR to LS no ND MODE CHANGE message. Also no message from LS to VOR. VOR to NAV, message does come.

- Not sure if these behaviors are realistic. If they are do let me know, I will pass this.

**Comment by utkrishtm** [comment]
https://youtu.be/yGlS2QBuX7s?si=nHt5mxE7kYzi_IYP&t=3663

This video has a lot of mode changes throughout, a good resource.

In this video you can see once he changes from ARC to PLAN, it shows ND MODE CHANGE. In A380X, it shows ND RANGE CHANGE instead.

**Comment by MrJigs7** [comment]
Thanks for the test and feedback :) I haven't changed anything on this PR in relation to the MODE CHANGE\RANGE CHANGE priorities. I've only updated the message content that is shown. The way it is currently implemented in master, range change has priority over mode change so I am not sure if any change there would be in scope of this issue. @flogross89  Any thoughts on this?

**Comment by tracernz** [comment]
On A320, rose LS and VOR do not display these messages, as there's no map to wait for.

**Comment by utkrishtm** [comment]
> On A320, rose LS and VOR do not display these messages, as there's no map to wait for.

This makes sense. So from VOR to NAV showing MODE CHANGE is correct so that is cleared. 
Based on the videos, Mode and Range should be different and Range should not be given priority over Mode. Once that is fixed, I can pass this one. 

Also, if the MAP NOT AVAIL needs to be a separate PR, please do let me know. Thanks

**Comment by BravoMike99** [comment]
> > On A320, rose LS and VOR do not display these messages, as there's no map to wait for.
> 
> This makes sense. So from VOR to NAV showing MODE CHANGE is correct so that is cleared. Based on the videos, Mode and Range should be different and Range should not be given priority over Mode. Once that is fixed, I can pass this one.
> 
> Also, if the MAP NOT AVAIL needs to be a separate PR, please do let me know. Thanks

The map not avail should be on a separate pr/request yep. Regarding the mode change I'm personally not sure since its also an issue on master and not something which this PR originally intended to fix.

**Comment by utkrishtm** [comment]
> > > On A320, rose LS and VOR do not display these messages, as there's no map to wait for.
> > 
> > 
> > This makes sense. So from VOR to NAV showing MODE CHANGE is correct so that is cleared. Based on the videos, Mode and Range should be different and Range should not be given priority over Mode. Once that is fixed, I can pass this one.
> > Also, if the MAP NOT AVAIL needs to be a separate PR, please do let me know. Thanks
> 
> The map not avail should be on a separate pr/request yep. Regarding the mode change I'm personally not sure since its also an issue on master and not something which this PR originally intended to fix.

Gotcha, I will make requests for both of them and take it from there. Thanks!

**Comment by utkrishtm** [comment]
Quality Assurance Trainee Report

Discord Username : utkrishtm
Object of testing : https://github.com/flybywiresim/aircraft/pull/9739
Aircraft : A32NX/A380X
Tier of Testing : 1
Date : 13/02/2025

Testing Process:
- Loaded up into the sim with the powered config from efb. Aligned the IRS and move the range selectors and mode selectors

A380X:
- Everything works as expected

A32NX:
- Everything works as expected

Testing Results:
Passed

**Comment by MrJigs7** [comment]
Regarding the mode change message, and the general implementation of all ND messages. I spoke with Tracer via Discord and he mentioned that he has raised with the dev team about how the ND messages are implemented as currently they are nearly all in common which may not be the best approach. In any case, any changes will be outside the scope of this issue

**Comment by BravoMike99** [comment]
> > > > On A320, rose LS and VOR do not display these messages, as there's no map to wait for.
> > > 
> > > 
> > > This makes sense. So from VOR to NAV showing MODE CHANGE is correct so that is cleared. Based on the videos, Mode and Range should be different and Range should not be given priority over Mode. Once that is fixed, I can pass this one.
> > > Also, if the MAP NOT AVAIL needs to be a separate PR, please do let me know. Thanks
> > 
> > 
> > The map not avail should be on a separate pr/request yep. Regarding the mode change I'm personally not sure since its also an issue on master and not something which this PR originally intended to fix.
> 
> Gotcha, I will make requests for both of them and take it from there. I will pass this then. Thanks!

I have now created entries for both 👍

**Comment by MrJigs7** [comment]
Fixed conflicts

File: fbw-common/src/systems/instruments/src/ND/ND.tsx [hunk 4]
```diff
@@ -453,8 +461,13 @@ export class NDComponent<T extends number> extends DisplayComponent<NDProps<T>>
               HDG
             </Flag>
 
-            <Flag visible={this.rangeChangeInProgress} x={384} y={320} class="Green FontIntermediate">
-              RANGE CHANGE
+            <Flag
+              visible={this.rangeChangeInProgress}
+              x={384}
+              y={320}
+              class="Green FontIntermediate a380xModeRangeChange"
```
Comment (BravoMike99) [inline fbw-common/src/systems/instruments/src/ND/ND.tsx:468]: I think you forgot to update the class name here after the renaming

**Review by BravoMike99 — CHANGES_REQUESTED** [review]

File: fbw-common/src/systems/instruments/src/ND/ND.tsx (hunk 4 above)
Comment (MrJigs7) [reply fbw-common/src/systems/instruments/src/ND/ND.tsx:468]: Oops will fix that shortly, thanks!

Comment (MrJigs7) [reply fbw-common/src/systems/instruments/src/ND/ND.tsx]: Fixed

Comment (BravoMike99) [reply fbw-common/src/systems/instruments/src/ND/ND.tsx]: Thanks. I have tested it locally and verified all is working well 👍

**Review by BravoMike99 — APPROVED** [review]
