### PR TITLE
fix(efb): EFB fuel fill button color spill

### LINKED ISSUE #8079: EFB fuel fill button color spill
### Aircraft Version

Experimental

### Build info

```json
{
    "built": "2023-06-06T08:54:20+00:00",
    "ref": "refs/heads/experimental",
    "sha": "0cb783fe69121e40bd44b64ebbe1c28015c9c553",
    "actor": "Saschl",
    "event_name": "manual",
    "pretty_release_name": "experimental:0cb783fe",
    "version": "v0.10.0-exp.0cb783f"
}
```

### Describe the bug

image

### Expected behavior

Not have the spill on the outline

### Steps to reproduce

1. Start fresh flight
2. Open EFB
3. Go to fuel page

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

alepouna

### PR DESCRIPTION
**Pull request by MicahBCode**
Fixes #8079 

## Summary of Changes

Fixes the background overflow in the Fuel Page of the EFB.

## Screenshots (if necessary)

Before:
image

After:
image

## Additional context

Discord username (if different from GitHub): Micah (micahbcode)

## Testing instructions

1. Start new flight
2. Goto EFB -> Ground -> Fuel
3. Check there is no overflow of the refueling start-/stop

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

File: fbw-a32nx/src/systems/instruments/src/EFB/Ground/Pages/FuelPage.tsx [hunk 1]
```diff
@@ -442,7 +442,7 @@ export const FuelPage = () => {
                     </div>
 
                     <div
-                        className={`flex justify-center items-center w-20 ${formatRefuelStatusClass()} bg-current`}
+                        className={`flex justify-center items-center w-20  ${formatRefuelStatusClass()} bg-current`}
```
Comment (Benjozork) [inline fbw-a32nx/src/systems/instruments/src/EFB/Ground/Pages/FuelPage.tsx:445]: Looks unintentional

**Review by Benjozork — CHANGES_REQUESTED** [review]

File: fbw-a32nx/src/systems/instruments/src/EFB/Ground/Pages/FuelPage.tsx (hunk 1 above)
Comment (MicahBCode) [reply fbw-a32nx/src/systems/instruments/src/EFB/Ground/Pages/FuelPage.tsx:445]: Yep, that was unintentional 😶‍🌫️  Thanks!

**Review by Benjozork — APPROVED** [review]
