### PR TITLE
fix(a380x/vd): Use FCU EIS discrete word for baro mode

### LINKED ISSUE #10357: [A380X][VD] Baro Ref change doesn't change altitude labels
### Simulator

2020

### Aircraft Version

Development (4k)

### Build info

```json
master
```

### Describe the bug

When changing from STD to QNH or vice versa, the altitude band labels should change accordingly. They don't.
Need to adapt to the new baro ref var from tracer's recent PR. 

### Expected behavior

Labels should read FL for STD, and altitudes for QNH

### Steps to reproduce

Change baro ref 

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

floridude

### PR DESCRIPTION
**Pull request by flogross89**
Fixes #10357

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Verify that #10357 is fixed: 
Load into aircraft, change from QNH to STD, observe VD altitude labels go from altitude to FL on **both** sides. 

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo**, **flybywire-aircraft-a380-842 (4K)** or **flybywire-aircraft-a380-842 (8K)** download link at the bottom of the page

### CODE REVIEW

File: fbw-a380x/src/systems/instruments/src/ND/VerticalDisplay/VerticalDisplay.tsx [hunk 1]
```diff
@@ -60,7 +61,8 @@ export class VerticalDisplay extends DisplayComponent<VerticalDisplayProps> {
       AesuBusEvents &
       FGVars &
       FcuSimVars &
-      MfdSurvEvents
+      MfdSurvEvents &
+      A380XFcuBusEvents
```
Comment (tracernz) [inline fbw-a380x/src/systems/instruments/src/ND/VerticalDisplay/VerticalDisplay.tsx]: Would be nice to always keep these alphabetical for readability and reduced chance of git conflicts for the more commonly changed ones.

**Comment by alexr4339** [comment]
Quality Assurance Tester Report

Discord Username  : alexdnzdmb 
Object of testing : #10360 
Aircraft          : A380X 
Simulator         : 2024 (SU4) 
Tier of Testing   : 1
Date              : 10/10/2025 

Testing Process: 
Verify that https://github.com/flybywiresim/aircraft/issues/10357 is fixed:
Load into aircraft, change from QNH to STD, observe VD altitude labels go from altitude to FL on both sides.

Testing Results: 
Not Passed  

Negatives:       
Labels never change to FL and observed that the planes altitude on the VSD changes in STD mode when changing the preset baro.

Conclusions: 


Media:
image
image

**Comment by flogross89** [comment]
@alexr4339 I'm very sorry, I forgot to add a publisher and didn't test it myself because I thought the change was so small (it's always those...). I just pushed the fixes, appreciate another test. This time, I really tested it in sim.

File: fbw-a380x/src/systems/instruments/src/ND/VerticalDisplay/VerticalDisplay.tsx (hunk 1 above)
Comment (flogross89) [reply fbw-a380x/src/systems/instruments/src/ND/VerticalDisplay/VerticalDisplay.tsx]: Roger, I reordered them.

File: .github/CHANGELOG.md [hunk 2]
```diff
@@ -148,6 +150,8 @@
 1. [FMS] Fix fuel predictions in the FMS not matching the engine model - @BlueberryKing (BlueberryKing)
 1. [A380X/PFD] Fix selected altitude not white when ROLLOUT engaged - @BravoMike99(bruno_pt99)
 1. [A380X/PFD] Fix green ARS indication appearing before flaps are in CONF 1+F - @BravoMike99(bruno_pt99)
+1. [A380X/OIT] Add systems info page for approach and landing capability equipment monitoring - @flogross89 (floridude)
+1. [A380X/VD] Fix VD altitude band not responding to QNH/STD baro ref changes - @flogross89 (floridude)
```
Comment (BravoMike99) [inline .github/CHANGELOG.md]: Do we need the change-log for this? The issue was not present in the previous stable I believe as the altimeter changes happened after that.

Comment (tracernz) [reply .github/CHANGELOG.md]: Good point. Should not be there.

Comment (flogross89) [reply .github/CHANGELOG.md]: Fair point, removed that line.

**Comment by heclak** [comment]
Quality Assurance Developer Report

Discord Username  : Heclak 
Object of testing : #10360 
Aircraft          : A380X 
Simulator         : 2020 
Tier of Testing   : 1
Date              : 14/10/2025 

Testing Process: 
 
Load into aircraft, change from QNH to STD, observe VD altitude labels go from altitude to FL on both sides.

Testing Results: 
Passed  

Media:

FlightSimulator_2025-10-14-11-10-15-1563
FlightSimulator_2025-10-14-11-10-18-1564

**Comment by heclak** [comment]
Quality Assurance Developer Report

Discord Username  : Heclak 
Object of testing : #10360 
Aircraft          : A380X 
Simulator         : 2024 
Tier of Testing   : 1
Date              : 14/10/2025 

Testing Process: 
 
Load into aircraft, change from QNH to STD, observe VD altitude labels go from altitude to FL on both sides.

Testing Results: 
Passed  

Media:


FlightSimulator2024_2025-10-14-11-18-13-1565
FlightSimulator2024_2025-10-14-11-18-19-1566
