### PR TITLE
fix(a380/nd): Fixed TCAS message position and add TCAS STBY

### LINKED ISSUE #9054: A380X/ND: ND TCAS messages not centered
### Aircraft Version

Development

### Build info

```json
master
```

### Describe the bug

The ND TCAS messages are not centered and are offset to the left like the A32NX.

### Expected behavior

ND TCAS messages should be centered as there's no ATSAW support on the A380. In addition, there should also be a "TCAS STBY" message.

### Steps to reproduce

Fail the TCAS or set it to TA ONLY.

### References (optional)

https://youtu.be/GspxOmtreIQ?t=46
https://www.youtube.com/shorts/5f9TiunFZyg
https://youtu.be/qcXQKQukxkI?t=248

### Additional info (optional)

_No response_

### Discord Username (optional)

bruno_pt99

### PR DESCRIPTION
**Pull request by MrJigs7**
Fixes #9054 

## Summary of Changes
Updated logic on dynamic class for TCAS messages
Added class to adjust text position for A380 TCAS Messages
Added TCAS STBY display
Added class to hide in A32NX

## Screenshots (if necessary)

TCASFail
TcasFail2
TCASStby
TCASTAOnly

## References

TCASFailRef
TCASStbyRef
TCASTAOnlyRef

Other video references on issue #9054 

## Additional context

I've added the TCAS STBY in using CSS classes but if the preference would be to do it via a prop I can change it

Discord username (if different from GitHub):MrJigs.

## Testing instructions

1. Start A380X cold and dark
2. Power aircraft, align IRS and enable XPDR
3. Check TCAS STBY flag shown as initial message
4. Check through various TCAS modes and correct flag is shown on ND with correct positioning
5. Fail TCAS and check flag is shown on ND with correct positioning
6. Load A32NX and observe no changes

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo**, **flybywire-aircraft-a380-842 (4K)** or **flybywire-aircraft-a380-842 (8K)** download link at the bottom of the page

### CODE REVIEW

**Comment by tracernz** [comment]
We should think about whether it makes sense for these messages to actually just be part of the aircraft rather than the fbw-common part of the ND, as they differ in many ways, and having them in fbw-common makes it harder to fix them up to use the proper ARINC429 words in the A32NX for example.

File: fbw-common/src/systems/instruments/src/ND/TcasWxrMessages.tsx [hunk 1]
```diff
@@ -66,19 +72,32 @@ export class TcasWxrMessages extends DisplayComponent<TcasWXMessagesProps> {
...
+          this.rectClass.set('Grey BackgroundFill');
         } else if (taOnly) {
-          this.leftMessage.set({ text: 'TA ONLY', color: 'White' });
+          this.leftMessage.set({ text: 'TA ONLY' });
+          this.textClass.set('White TCASMessage');
+          this.rectClass.set('Grey BackgroundFill');
+        } else if (mode === 0) {
+          this.leftMessage.set({ text: 'TCAS STBY' });
+          this.textClass.set('White TCASMessage TCASStby');
+          this.rectClass.set('Grey BackgroundFill TCASStby');
```
Comment (tracernz) [inline fbw-common/src/systems/instruments/src/ND/TcasWxrMessages.tsx:93]: Classes should be either a SetSubject, or an object in inline in the JSX (preferred declarative approach).

File: fbw-a380x/src/systems/instruments/src/ND/style.scss [hunk 2]
```diff
@@ -34,3 +34,9 @@
 .a380xInvisible {
   display: none;
 }
+
+.TCASMessage {
+  text-align: center;
+  text-anchor: middle;
+  transform: translateX(214px) translateY(0)
+}
```
Comment (tracernz) [inline fbw-a380x/src/systems/instruments/src/ND/style.scss:42]:
```suggestion
}

```

File: fbw-a380x/src/systems/instruments/src/ND/style.scss [hunk 3]
```diff
@@ -34,3 +34,9 @@
 .a380xInvisible {
   display: none;
 }
+
+.TCASMessage {
```
Comment (tracernz) [inline fbw-a380x/src/systems/instruments/src/ND/style.scss:38]:
```suggestion
.TcasMessage {
```

File: fbw-a32nx/src/systems/instruments/src/ND/style.scss [hunk 4]
```diff
@@ -21,3 +21,7 @@
   background: $display-background;
   fill: rgb(4,4,5);
 }
+
+.TCASStby {
```
Comment (tracernz) [inline fbw-a32nx/src/systems/instruments/src/ND/style.scss:25]:
```suggestion
.TcasStandbyMessage {
```
We prefer title case, with a special exception for 2 chars only.

**Comment by MrJigs7** [comment]
Made requested changes

**Review by tracernz — APPROVED** [review]

**Comment by utkrishtm** [comment]
Is this for A32NX as well or just A380X now? Please update the testing instructions as needed.

**Comment by MrJigs7** [comment]
> Is this for A32NX as well or just A380X now? Please update the testing instructions as needed.

testing instructions step 6 already references that there should be no changes seen in the A32NX. The code changes do affect both.

**Comment by utkrishtm** [comment]
> > Is this for A32NX as well or just A380X now? Please update the testing instructions as needed.
> 
> testing instructions step 6 already references that there should be no changes seen in the A32NX. The code changes do affect both.

The reason why I asked was the A32NX label was removed so just making sure.

**Comment by utkrishtm** [comment]
Quality Assurance Trainee Report

Discord Username  : utkrishtm
Object of testing : #9782 
Aircraft          : A380X 
Tier of Testing   : 1
Date              : 02/09/2025

Testing Process: 
- Checked TCAS in all modes
- Checked the TCAS message in all ND modes as well. 
- Failed IRS alignment to check the correct TCAS message on ND.

- Did load the A32NX as instructed, observed no changes. LGTM

Testing Results: 
Passed
