### PR TITLE
fix: ground track bug out of bounds

### LINKED ISSUE #8337: [PFD] TRK Diamond displayed off the scale
### Aircraft Version

Development

### Build info

```json
{
    "built": "2023-12-21T22:17:59+00:00",
    "ref": "refs/heads/master",
    "sha": "de25ee7e325402e2ad8f4eb8e923c6cc0f478863",
    "actor": "tracernz",
    "event_name": "manual",
    "pretty_release_name": "master:de25ee7e",
    "version": "v0.12.0-dev.de25ee7"
}
```

### Describe the bug

Actual Track Symbol (small green diamond) is displayed off the scale.

image

### Expected behavior

The symbol shall be contained within the heading reference

### Steps to reproduce

1. Get a drift angle bigger than the HDG scale

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

Bernardo R

### PR DESCRIPTION
**Pull request by Saschl**
Fixes #8337

## Summary of Changes

Will hide the ground track bug if it is out of bounds, instead of drawing it in places where it should not be.

## Additional context

Discord username (if different from GitHub):

## Testing instructions

1. Setup a very high cross wind and play with erratic rudder inputs to make the ground track bug on the PFD go out of bounds. When it reaches the edges of the heading tape, it should disappear and not be drawn outside of the tape.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Review by Benjozork — APPROVED** [review]

File: fbw-a32nx/src/systems/instruments/src/PFD/HeadingIndicator.tsx [hunk 1]
```diff
@@ -207,27 +207,49 @@ interface GroundTrackBugProps {
...
-                this.trackIndicator.instance.style.transform = `translate3d(${offset}px, 0px, 0px)`;
+        this.groundTrack.setConsumer(sub.on('track').withArinc429Precision(3));
+
+        this.isVisibleSub.sub((isVisible) => {
+            if (isVisible) {
+                this.style.set({ display: '' });
+                this.transformSub.resume();
             } else {
-                this.trackIndicator.instance.style.display = 'none';
+                this.style.set({ display: 'none' });
```
Comment (tracernz) [inline fbw-a32nx/src/systems/instruments/src/PFD/HeadingIndicator.tsx:240]: You could set the style object inline in the JSX with subscribables for each prop to save allocating a new object each time.

Comment (Saschl) [reply fbw-a32nx/src/systems/instruments/src/PFD/HeadingIndicator.tsx:240]: Sounds good, will apply

**Review by tracernz — APPROVED** [review]

**Comment by Popespice** [comment]
Quality Assurance Tester Report

Discord          : Popespice
Object of testing: #8344 
Tier of Testing  : 1
Date             : 06012024

Testing Process: 
1. Log into MSFS
2. Load into any airport
3. Go through normal startup (ADIRS, FPLAN, etc.)
4. Take Off
5. Observe during takeoff and flight  ground track bug stays in-bounds

Negatives:       
N/A

Testing Results: 
Passed

Conclusions: 
Working as expected

Media:       
N/A
