### PR TITLE
fix(a380x): Bugfixes for SD status area (ISA, ZFWCG) & THR RED on FMS PERF page, RADIO alt handling

### LINKED ISSUE #9114: [A380X] - APPR PERF decision height boxes wrong input logic
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-10-21T09:22:54+00:00",
    "ref": "refs/heads/master",
    "sha": "909ed7fe239e7d31f5f7e69c1cfa9a744a7a6a43",
    "actor": "Saschl",
    "event_name": "manual",
    "pretty_release_name": "master:909ed7fe",
    "version": "a380x-v0.12.0-dev.909ed7f"
}
```

### Describe the bug

The following issues are present in relation to the input logic of the minima fields on the PERF APPR page.

1. `NONE`, `NO`, `NODH`, `NO DH` are not accepted as valid entries for RADIO on the PERF APPR page. It also does not allow spaces, which is necessary to support `NO DH` as input.
2. RADIO accepts 0 which should be out of range
3. Both BARO and RADIO can be filled out at the same time

### Expected behavior

1. All above listed inputs should be accepted as valid entries.
2. The RADIO field should not accept values <1
3. Both fields should never be filled out at the same time.

### Steps to reproduce

1. Try to enter the above listed strings into the RADIO field.
2. Try to enter 0 as decision height
3. Try to fill out both fields without clearing the other first.

### References (optional)

image

### Additional info (optional)

_No response_

### Discord Username (optional)

examplewastaken

### LINKED ISSUE #9910: [A380X] NO DH Sometimes Shown When Not Desired
### Simulator

2020

### Aircraft Version

Stable (8k)

### Build info

```json
master
```

### Describe the bug

NO DH is sometimes shown when not desired.

### Expected behavior

Current thoughts are same as A320/30/40/50 => needs an explicit NONE/NO/NODH/NO DH entry in the radio field, but A380 FCOM does say something different...

### Steps to reproduce

Enter baro mins or nothing and go within 250 NM of dest in cruise phase. The NO DH flag is transmitted by the FMS and will be visible on the PFD.

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

_No response_

### LINKED ISSUE #10166: ISA deviation not visible on SD in STD
### Simulator

2020

### Aircraft Version

Development (4k)

### Build info

```json
{
    "built": "2025-06-20T16:20:01+00:00",
    "ref": "refs/heads/master",
    "sha": "2f8489f00acdaa188ff7da3ee74a00962a83e016",
    "actor": "flogross89",
    "event_name": "manual",
    "pretty_release_name": "master:2f8489f0",
    "version": "a380x-v0.14.0-dev.2f8489f"
}
```

### Describe the bug

ISA deviation is not displayed on the SD when in STD. This is due to the XMLVAR_BARO1_Mode variable not being written at anymore.

### Expected behavior

ISA to appear once in STD mode.

### Steps to reproduce

Set baro reference in STD, observe how ISA does not appear.

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

bruno_pt99

### LINKED ISSUE #10195: SD permanent data displays GW and GWCG before ZFWCG
### Simulator

2020

### Aircraft Version

Development (4k)

### Build info

```json
{
    "built": "2025-06-29T13:44:26+00:00",
    "ref": "refs/heads/master",
    "sha": "d61e243d6c8cb3d8ec1f3a0119f84f111d70421e",
    "actor": "becas22",
    "event_name": "manual",
    "pretty_release_name": "master:d61e243d",
    "version": "a380x-v0.14.0-dev.d61e243"
}
```

### Describe the bug

GW and GWCG are displayed with just ZFW entry

Image

### Expected behavior

According to FCOM, GW and GWCG need ZFW and ZFWCG entry

Image

### Steps to reproduce

1. Insert citypair, FL and CI
2. Insert ZFW
3. Check SD permanent data

### References (optional)

DSC-31-CDS-40-10

### Additional info (optional)

_No response_

### Discord Username (optional)

_No response_

### LINKED ISSUE #10224: Minimums displayed as soon as entered
### Simulator

2020

### Aircraft Version

Development (4k)

### Build info

```json
{
    "built": "2025-07-11T23:00:12+00:00",
    "ref": "refs/heads/master",
    "sha": "71edaf35587ac54cbec8eabe1f4a13a2588553c2",
    "actor": "becas22",
    "event_name": "manual",
    "pretty_release_name": "master:71edaf35",
    "version": "a380x-v0.14.0-dev.71edaf3"
}
```

### Describe the bug

The minimum decision height gets displayed long before reaching 250nm from the destination.

Image

### Expected behavior

The decision height should get displayed when in cruise and closer than 250nm to the destination.

Image

### Steps to reproduce

1. Go into cruise mode
2. Enter either baro or radio minimums

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

_No response_

### LINKED ISSUE #10260: THR RED field on T.O page is dashed while ACCEL is filled
### Simulator

2020

### Aircraft Version

Development (4k)

### Build info

```json
{
    "built": "2025-07-26T06:33:29+00:00",
    "ref": "refs/heads/master",
    "sha": "557d5dd43b7b3b96d3956a72b0458947b638d0a1",
    "actor": "tracernz",
    "event_name": "manual",
    "pretty_release_name": "master:557d5dd4",
    "version": "a380x-v0.14.0-dev.557d5dd"
}
```

### Describe the bug

THR RED on T.O page is dashed. ACCEL is filled as expected.

### Expected behavior

THR RED shows a number and not -----

### Steps to reproduce

1. Start from cold and dark and perform the power up like normal.
2. Check the T.O page

### References (optional)

Image

### Additional info (optional)

_No response_

### Discord Username (optional)

_No response_

### PR DESCRIPTION
**Pull request by flogross89**
Fixes #10260 
Fixes #10166
Fixes #10195 
Fixes #10224 
Fixes #9910 
Fixes #9114 

## Additional context

Discord username (if different from GitHub): floridude

## Testing instructions

Please confirm that all of the above issues are fixed :) 
#10166 also to be tested on A32NX, the rest only on A380X.

Proposed flow: 
A380X: 

1. Load route from SimBrief, verify that THR RED field on PERF pages are filled out correctly
2. Fill in ZFW in FMS FUEL&LOAD, SD status area should show cyan dashes for GW and GW CG. Fill in ZFW CG --> GW and GW CG should show green values
3. Take-off, reach CRZ phase, fill in approach details (destination should be more than 250nm away)
4. Try out several variations of BARO and RADIO values, "NO DH", "NODH", "NONE" and "NO" should be valid values. PFD FMA should however not display these, since we're too far away.
5. Change DEST to an airport less than 250nm away, fill in APPR info again, DH (RADIO/BARO) should be displayed on FMA
6. Change left altimeter from STD to QNH and back --> Only when altimeter is set to STD, ISA should be displayed in SD status area

A32NX: 
1. Change left altimeter from STD to QNH and back --> Only when altimeter is set to STD, ISA should be displayed in SD status area

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo**, **flybywire-aircraft-a380-842 (4K)** or **flybywire-aircraft-a380-842 (8K)** download link at the bottom of the page

### CODE REVIEW

File: fbw-a32nx/src/systems/instruments/src/SD/StatusArea/StatusArea.tsx [hunk 1]
```diff
@@ -73,8 +73,8 @@ export const StatusArea = () => {
   });
 
   useEffect(() => {
-    const baroMode = SimVar.GetSimVarValue('L:XMLVAR_Baro1_Mode', 'number');
-    const isInStdMode = baroMode !== 0 && baroMode !== 1;
+    const baroMode = SimVar.GetSimVarValue('L:A32NX_FCU_EFIS_L_DISPLAY_BARO_MODE', 'number');
+    const isInStdMode = baroMode === 0; // 0 = STD, 1 = QNH, 2 = QFE
```
Comment (tracernz) [inline fbw-a32nx/src/systems/instruments/src/SD/StatusArea/StatusArea.tsx]: Should be `bitValueOr(28, false)` from `L:A32NX_FCU_LEFT_EIS_DISCRETE_WORD_2` or  `L:A32NX_FCU_RIGHT_EIS_DISCRETE_WORD_2`.

File: fbw-a380x/src/systems/instruments/src/SDv2/StatusArea.tsx [hunk 2]
```diff
@@ -35,15 +35,18 @@ const getCurrentHHMMSS = (seconds: number) => {
...
 
   private readonly tat = Arinc429LocalVarConsumerSubject.create(this.sub.on('tat'));
 
   private readonly zp = Arinc429LocalVarConsumerSubject.create(this.sub.on('altitude'));
 
-  private readonly baroMode = ConsumerSubject.create(this.sub.on('baroMode'), 'STD');
+  private readonly fcuEisDiscreteWord2 = Arinc429LocalVarConsumerSubject.create(
+    this.sub.on('a380x_fcu_eis_discrete_word_2_left'),
+  );
+  isStd = this.fcuEisDiscreteWord2.get().bitValueOr(28, true);
```
Comment (tracernz) [inline fbw-a380x/src/systems/instruments/src/SDv2/StatusArea.tsx]: Please add access modifiers (private readonly).

File: fbw-a380x/src/systems/instruments/src/PFD/FMA.tsx [hunk 3]
```diff
@@ -1668,54 +1675,99 @@ class D1D2Cell extends ShowForSecondsComponent<CellProps> {
...
+  );
+
+  onAfterRender(node: VNode): void {
+    super.onAfterRender(node);
+
+    const sub = this.props.bus.getArincSubscriber<PFDSimvars & Arinc429Values>();
+
+    sub.on('fmEisDiscreteWord2Raw').handle(this.fmEisDiscrete2.setWord.bind(this.fmEisDiscrete2));
+    sub.on('fmMdaRaw').handle(this.mda.setWord.bind(this.mda));
+    sub.on('fmDhRaw').handle(this.dh.setWord.bind(this.dh));
```
Comment (tracernz) [inline fbw-a380x/src/systems/instruments/src/PFD/FMA.tsx]: You can use Arinc429LocalVarConsumerSubject instead.

File: fbw-a380x/src/systems/instruments/src/SDv2/StatusArea.tsx (hunk 2 above)
Comment (flogross89) [reply fbw-a380x/src/systems/instruments/src/SDv2/StatusArea.tsx]: ouch, this was actually a left over of an unused variable. removed.

File: fbw-a32nx/src/systems/instruments/src/SD/StatusArea/StatusArea.tsx (hunk 1 above)
Comment (flogross89) [reply fbw-a32nx/src/systems/instruments/src/SD/StatusArea/StatusArea.tsx]: changed.

Comment (tracernz) [reply fbw-a32nx/src/systems/instruments/src/SD/StatusArea/StatusArea.tsx]: I am thinking it should be either left or right in STD, but no hard ref for that.

File: fbw-a380x/src/systems/instruments/src/PFD/FMA.tsx (hunk 3 above)
Comment (flogross89) [reply fbw-a380x/src/systems/instruments/src/PFD/FMA.tsx]: I copied the pattern over from the a32nx and didn't choose to refactor it. But it makes sense. I changed it for both a/c. We could actually copy over D3Cell to fbw-common/PFD in the future.

File: fbw-a32nx/src/systems/instruments/src/SD/StatusArea/StatusArea.tsx (hunk 1 above)
Comment (flogross89) [reply fbw-a32nx/src/systems/instruments/src/SD/StatusArea/StatusArea.tsx]: Ah, that's what you mean. I thought some FCDC might take care of that, but I'll add both and the OR logic

Comment (flogross89) [reply fbw-a32nx/src/systems/instruments/src/SD/StatusArea/StatusArea.tsx]: done

Comment (tracernz) [reply fbw-a32nx/src/systems/instruments/src/SD/StatusArea/StatusArea.tsx]: It's only left!
image
image

Comment (flogross89) [reply fbw-a32nx/src/systems/instruments/src/SD/StatusArea/StatusArea.tsx]: changed back to left

**Comment by borkxo** [comment]
Quality Assurance Trainee Report

Discord Username  : borkxo
Object of testing : #10271 
Aircraft          : A32NX,A380X
Simulator         : 2024
Tier of Testing   : 1
Date              : 04/08/2025

Testing Process: 
A380X
1. Imported & inserted Simbrief FPLN
2. Verified THR RED field is filled out in PERF T.O. and CLB pages in FMS 1&2
3. Filled in ZFW, verified that the SD status area shows cyan dashes for GW & GWCG.
4. Filled in ZFWCG, SD status area now shows the GW & GWCG in green
5. Reached cruise, filled out approach details for airport >250 NM away
6. Tried various Baro and Radio minimums, verified that they did not show up on the FMA
7. Changed destination airport to <250NM, filled out approach details, minimums now display on FMA
8. Changed destination airport to ~300NM, filled out approach details, minimums display once airport is <250NM away
9. Changed left altimeter to QNH, verified ISA is not displayed on SD. Changed it back to STD, ISA now displayed on SD

A32NX
1. Changed left altimeter to STD, verified ISA is displayed on SD. Changed it back to QNH, ISA is no longer displayed
2. Changed right altimeter to STD, no ISA displayed on SD

Testing Results: 
Passed
