### PR TITLE
fix(a380x/fms): Fix mach crossover altitude & T/O perf characteristic speeds

### LINKED ISSUE #9741: MFD: Characteristic speeds hardcoded on PERF TO
### Aircraft Version

Stable

### Build info

```json
master
```

### Describe the bug

F, S & greendot speed are hardcoded to 141, 159 & 190kt respectively on the PERF TO page.
image

### Expected behavior

Speeds to be accurate to the current weight. 

### Steps to reproduce

Open the MFD PERF page and change the weights of the aircraft.

### References (optional)

_No response_

### Additional info (optional)

PERF APPR takes the expected LW into account
image

### Discord Username (optional)

bruno_pt99

### LINKED ISSUE #9764: Speed does not always transition from climb speed to cruise Mach
### Simulator

2020

### Aircraft Version

Development (4k)

### Build info

```json
"built": "2025-01-01T10:39:42+00:00",
    "ref": "refs/heads/master",
    "sha": "a0c9ddd95133343f7b5413a834fe207ba747691c",
    "actor": "tracernz",
    "event_name": "manual",
    "pretty_release_name": "master:a0c9ddd9",
    "version": "a380x-v0.13.0-dev.a0c9ddd"
```

### Describe the bug

Climb speed does not transition to cruise Mach when cruise altitude is reached.  Screenshot shows that cruise speed in the FMS Perf page is M0.85. Airplane is in managed speed mode, but the speed target is still the climb speed of 290 KCAS.
Screenshot 2025-01-15 153524
Not shown is that the managed climb speed/Mach combination was 290/M0.84. M 0.84 is not reached at 290 KCAS until higher than the FL340 cruise altitude I was using, so the speed never switched to Mach during the climb. This may have led to the climb speed remaining at 290 KCAS during the cruise. (As a check, I then climb to FL360 and the target speed did switch to 0.85 Mach.)

### Expected behavior

Managed speed target to transition to managed cruise speed/Mach regardless of whether the climb Mach transition altitude is reached.

### Steps to reproduce

Climb to FL 340. Observe that the managed target speed remains the target climb speed of 290 KCAS instead of transitioning to the cruise Mach of 0.85.

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

_No response_

### PR DESCRIPTION
**Pull request by flogross89**
Fixes #9764 
Fixes #9741 

## Summary of Changes

- Also update characteristic speeds when ADR CAS data NCD (i.e. low speed/standstill)
- Remove CI-dependent cruise speed calculation, not mature enough
- Fix speed/mach switchover
- Fix FMS/PERF page formatting: `---` when no value for speeds

## Additional context

Discord username (if different from GitHub):

## Testing instructions

1. Set up FMS with CRZ ALT > FL310, confirm #9764 doesn't occur anymore (i.e. managed speed is switching to correct mach speed above FL300)
2. Confirm that characteristic speeds on T.O PERF page show correct speeds, depending on weight

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo**, **flybywire-aircraft-a380-842 (4K)** or **flybywire-aircraft-a380-842 (8K)** download link at the bottom of the page

### CODE REVIEW

File: fbw-a380x/src/systems/instruments/src/MFD/FMC/FmcAircraftInterface.ts [hunk 1]
```diff
@@ -1612,10 +1611,20 @@ export class FmcAircraftInterface {
...
+    const sat = ADIRS.getStaticAirTemperature();
     const alt = ADIRS.getBaroCorrectedAltitude();
-    const vM = SimVar.GetGameVarValue('FROM MACH TO KIAS', 'number', m);
-    return alt && alt.isNormalOperation() && alt.value > 20_000 && v > vM ? [vM, true] : [v, false];
+
+    if (sat !== undefined && sat.isNormalOperation() && alt !== undefined && alt.isNormalOperation()) {
+      const vM = MathUtils.convertMachToKCas(
+        m,
+        MathUtils.convertCtoK(sat.value),
+        SimVar.GetSimVarValue('AMBIENT PRESSURE', 'millibar'),
```
Comment (tracernz) [inline fbw-a380x/src/systems/instruments/src/MFD/FMC/FmcAircraftInterface.ts:1622]: Should use the ADR corrected average static pressure. You can use that instead of alt for the validity checks too. I'm not sure that baro-corrected alt ever made sense here, as the speed of sound does not depend on that.

File: fbw-a380x/src/systems/instruments/src/MFD/FMC/FmcAircraftInterface.ts [hunk 2]
```diff
@@ -1612,10 +1611,20 @@ export class FmcAircraftInterface {
...
   }
 
-  getManagedTargets(v: number, m: number) {
+  getManagedTargets(v: number, m: number): [number, boolean] {
+    const sat = ADIRS.getStaticAirTemperature();
     const alt = ADIRS.getBaroCorrectedAltitude();
-    const vM = SimVar.GetGameVarValue('FROM MACH TO KIAS', 'number', m);
-    return alt && alt.isNormalOperation() && alt.value > 20_000 && v > vM ? [vM, true] : [v, false];
+
+    if (sat !== undefined && sat.isNormalOperation() && alt !== undefined && alt.isNormalOperation()) {
```
Comment (tracernz) [inline fbw-a380x/src/systems/instruments/src/MFD/FMC/FmcAircraftInterface.ts:1618]: Functional test is also a valid SSM.

File: fbw-a380x/src/systems/instruments/src/MFD/FMC/FmcAircraftInterface.ts [hunk 3]
```diff
@@ -1612,10 +1611,20 @@ export class FmcAircraftInterface {
...
+      const vM = MathUtils.convertMachToKCas(
+        m,
+        MathUtils.convertCtoK(sat.value),
+        SimVar.GetSimVarValue('AMBIENT PRESSURE', 'millibar'),
+      );
+      return alt.value > 20_000 && v > vM ? [vM, true] : [v, false];
```
Comment (tracernz) [inline fbw-a380x/src/systems/instruments/src/MFD/FMC/FmcAircraftInterface.ts:1624]: Shouldn't need the alt check.

File: fbw-common/src/systems/shared/src/MathUtils.ts [hunk 4]
```diff
@@ -322,6 +322,17 @@ export class MathUtils {
...
   }
 
+  /**
+   * Convert Mach to Calibrated Air Speed
+   * @param kcas velocity true air speed
+   * @param oat Kelvin
+   * @param pressure current pressure hpa
+   * @returns Calibrated Air Speed
+   */
+  public static convertKCasToMach(kcas: number, oat: number, pressure: number): number {
```
Comment (tracernz) [inline fbw-common/src/systems/shared/src/MathUtils.ts:332]: Seems to be unused, and doesn't have tests.

Comment (flogross89) [reply fbw-common/src/systems/shared/src/MathUtils.ts:332]: thought I needed it, didn't. Removed it.

File: fbw-a380x/src/systems/instruments/src/MFD/FMC/FmcAircraftInterface.ts (hunk 2 above)
Comment (flogross89) [reply fbw-a380x/src/systems/instruments/src/MFD/FMC/FmcAircraftInterface.ts:1618]: changed

File: fbw-a380x/src/systems/instruments/src/MFD/FMC/FmcAircraftInterface.ts (hunk 1 above)
Comment (flogross89) [reply fbw-a380x/src/systems/instruments/src/MFD/FMC/FmcAircraftInterface.ts:1622]: ok, changed. Not sure where the 20000 ft came from, thought I read it in a reference somewhere but couldn't find it, so I deleted it. Don't know about the temperature either, but that's what the formula needs.

File: fbw-a380x/src/systems/instruments/src/MFD/FMC/FmcAircraftInterface.ts (hunk 3 above)
Comment (flogross89) [reply fbw-a380x/src/systems/instruments/src/MFD/FMC/FmcAircraftInterface.ts:1624]: deleted

**Review by tracernz — APPROVED** [review]
Nice!

**Comment by Jaronics** [comment]
Quality Assurance Trainee Report

Discord Username  : Jaronics 
Object of testing : #9769  
Aircraft          : A380X 
Tier of Testing   : 1
Date              : 18/01/2025 

Testing Process: 
1. Loaded a flight with a cruising altitude at FL380
2. T.O page shows speeds corresponding to the weight
3. Aircraft transitions to MACH

Testing Results: 
Passed 

Negatives:       
None


Conclusions: 
None


Media:

Screenshot 2025-01-18 094846
Screenshot 2025-01-18 104800
