### PR TITLE
fix(a380/mfd): RTE RSV, AMI defaults, trip fuel, FOB & ETA in fuel and load

### LINKED ISSUE #9342: ETA Disagree Flight Plan vs. Fuel Page
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-10-31T15:54:41+00:00",
    "ref": "refs/tags/v0.12.0",
    "sha": "2fe89113291f2478347dde0dc3228b55dc924f74",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.0",
    "version": "a380x-v0.12.0-rel.2fe8911"
}
```

### Describe the bug

1 Hour Difference in Flightplan Page vs Fuel & Load Page.
Screenshot 2024-11-02_

### Expected behavior

Times should match

### Steps to reproduce

Happened today on the launch event omdb to eham

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

ZORG

### PR DESCRIPTION
**Pull request by BravoMike99**
Fixes #9342 

## Summary of Changes

Fixes destination ETA being displayed in local time and not UTC time.
Adds flight time prediction to MFD during preflight phase.
Fixes trip fuel (non preflight) & trip time missing.
Fixes FOB value on the top of the page. 
Enables RTE RSV input fields.
Updates AMI defaults for A380 (taxi fuel & reserve max)

## Screenshots (if necessary)

PreFlight
FuelLoad3
RTE RSV2
RTE RSV

## Additional context

Discord username (if different from GitHub):
bruno_pt99
## Testing instructions

Start the airplane with engines off and program a flight plan.
Fill the FUEL & Load page during preflight:
1) "TIME" should be displayed on the bottom of the page above the destination airport and the estimate shows the expected flight time.
2) Trip time should be visible next to the trip fuel value
3) Enter an absolute value in the RTE RSV field. The percentage field should become dashed. Once the deleted, the percentage value appears with a value of 5% and the absolute value corresponds to that percentage of the trip fuel.
4) Change the percentage manually and verify that the absolute value is recalculated based on the entered percentage.

Perform a normal takeoff & observe the fuel & load page once in the air:
1) RTE RSV fields should show 0.0 and the inputs disabled.
2) Prediction at the bottom of the page to the destination is now in ETA rather than flight time & header shows "UTC"
3) FOB value matches what is sensed by the aircraft on the top of the page
4) Trip fuel (Expected fuel required between present time ) & trip time (remaining flight time) fields are filled with data and are in line with the FMS predictions .
5) Extra fuel field corresponds to Destination EFOB - MIN DEST FUEL.

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo**, **flybywire-aircraft-a380-842 (4K)** or **flybywire-aircraft-a380-842 (8K)** download link at the bottom of the page

### CODE REVIEW

File: fbw-a380x/src/systems/instruments/src/MFD/shared/utils.ts [hunk 1]
```diff
@@ -3,8 +3,8 @@
 
 import { Approach, ApproachType } from '@flybywiresim/fbw-sdk';
 
-export function getEtaFromUtcOrPresent(seconds: number | null, fromPresent: boolean) {
-  if (seconds === null) {
+export function getEtaFromUtcOrPresent(seconds: number | null | undefined, fromPresent: boolean) {
+  if (seconds === null || seconds === undefined) {
```
Comment (2hwk) [inline fbw-a380x/src/systems/instruments/src/MFD/shared/utils.ts:7]:
```suggestion
  if (!seconds && seconds !== 0) {
```

May also be useful to check for `NaN` and `""`

**Review by 2hwk — CHANGES_REQUESTED** [review]

File: fbw-a380x/src/systems/instruments/src/MFD/shared/utils.ts (hunk 1 above)
Comment (2hwk) [reply fbw-a380x/src/systems/instruments/src/MFD/shared/utils.ts:7]: Or perhaps gracefully handle these cases and error log it as these should never be thrown.

**Review by 2hwk — APPROVED** [review]

**Comment by heclak** [comment]
@BravoMike99 do you need help testing this? There are some conflicts blocking the build.

**Comment by tracernz** [comment]
You can probably make a better summary in the title by removing the redundant “fixes”. The title is what we will see after this is squash merged.

**Comment by Jaronics** [comment]
Quality Assurance Trainee Report

Discord Username  : Jaronics 
Object of testing : #9540  
Aircraft          : A380X 
Tier of Testing   : 1
Date              : 12/01/2025 

Testing Process: 

On the ground:
1. Set up the FMC
2. Checked that the route time is displayed correctly
3. RTE RSV field takes absolute value and percentage becomes dashed
4. When inputting a percentage, the RTE RSV gets recalculated properly

In the air:
1. RTE RSV fields are disabled and show 0.0
2. Time at the bottom shows UTC and corresponds with the ETA on the FPLN page
3. FOB value matches with sensed fuel
4. TRIP fuel and time are in line with FMS predictions
5. EXTRA FUEL corresponds to EFOB - MIN DEST FUEL
 

Testing Results: 
Passed  

Negatives:       
None

Conclusions: 
None

Media:
None
