### PR TITLE
fix(a380x): OANS authentication + VD improvements

### LINKED ISSUE #8227: Terr on ND elevation values incorrect in ROSE mode
### Aircraft Version

Development

### Build info

```json
{
    "built": "2023-09-22T09:37:54+00:00",
    "ref": "refs/heads/master",
    "sha": "c31b180ef291f26252b57cfab9be92e98e256754",
    "actor": "mjuhe",
    "event_name": "manual",
    "pretty_release_name": "master:c31b180e",
    "version": "v0.11.0-dev.c31b180"
}
```

### Describe the bug

Minimum and maximum elevation values of terrain seem to be stuck at 000 and 001 regardless of the terrain situation when ROSE mode is selected on the ND.
TERR
TERR2

### Expected behavior

Elevation values displayed on the ND should reflect the terrain situation.

### Steps to reproduce

1) Have simbridge running and turn on terr on ND
2) Switch between ROSE and ARC ND modes

### References (optional)

_No response_

### Additional info (optional)

At lower altitudes the issue is more obvious when there is terrain displayed as green or red, while the elevation remains green (001 & 000)

### Discord Username (optional)

bruno_pt99

### PR DESCRIPTION
**Pull request by flogross89**
Fixes #8227  with new SimBridge version linked below (tested via this PR)

## Summary of Changes

- Show "NOT AVAIL" in OANS, if not available due to auth issues
- Re-loads automatically on auth change, or manually via SWAP button
- Hide aircraft symbol and off-screen direction indicator when no airport loaded
- Changes color of VD dummy to white (less irritating)
- Improves some things in the VD
- Removes amber messages from SD mailbox (dark for normal operation)

## Additional context

Discord username (if different from GitHub):

## Testing instructions

For all of these tests, please use an experimental SimBridge version:
https://www.swisstransfer.com/d/8a6117a8-b14b-4ed6-83d1-3a33c60e1a14

**A32NX:** Test for no regressions on the ND instrument:
1. Current latitude and longitude are updated as expected (i.e. map in all modes except PLAN moves with the aircraft)
2. ROSE LS and ROSE VOR pages look as before, i.e. no unexpected black clipping
3. TERR on ND peaks mode works: When in ARC or ROSE modes, lower right of ND (below "TERR" should display min and max altitude of terrain in the current range). Must not show 000/001 when in mountain areas

**A380X:** Test all of the changes above
1. If Navigraph is unlinked via the EFB, OANS should show an amber "NOT AVAIL"
2. If Navigraph auth is changed via the EFB, the OANS should automatically reload
4. When no airport is loaded in the OANS, aircraft symbol and off-screen direction indicator should be hidden
5. VerticalDisplay should show information with white lines if ADIRS aligned, less information with red lines if not aligned
6. VD should show altitude band, consistent with terrain information
7. SD mailbox shouldn't show any amber messages anymore

Please note: The bright ND background is not fixed here, but in another PR (#8901 )

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo** or **flybywire-aircraft-a380-842** download link at the bottom of the page

### CODE REVIEW

File: fbw-a380x/src/systems/instruments/src/ND/NDSimvarPublisher.tsx [hunk 1]
```diff
@@ -34,11 +36,13 @@ export enum NDVars {
   ilsCourse = 'L:A32NX_FM_LS_COURSE',
   selectedHeading = 'L:A32NX_FCU_HEADING_SELECTED',
   showSelectedHeading = 'L:A320_FCU_SHOW_SELECTED_HEADING',
-  pposLat = 'PLANE LATITUDE', // TODO replace with fm position
-  pposLong = 'PLANE LONGITUDE', // TODO replace with fm position
+  pposLat = 'PLANE LATITUDE', // FIXME replace with fm position
+  pposLong = 'PLANE LONGITUDE', // FIXME replace with fm position
+  pposAlt = 'PLANE ALTITUDE', // FIXME replace with fm position
```
Comment (tracernz) [inline fbw-a380x/src/systems/instruments/src/ND/NDSimvarPublisher.tsx:41]: This seems dubious? We already have the ADR altitude topics.

File: fbw-a380x/src/systems/instruments/src/ND/OansControlPanel.tsx [hunk 2]
```diff
@@ -649,7 +642,10 @@ export class OansControlPanel extends DisplayComponent<OansProps> {
                         BTV MANUAL CONTROL / FALLBACK
                       </div>
                     </div>
-                    <div class="oans-cp-map-data-btv-rwy-length">
+                    <div
+                      class="oans-cp-map-data-btv-rwy-length"
+                      style={{ visibility: this.fmsDataStore.landingRunway.map((rwy) => (rwy ? 'inherit' : 'hidden')) }}
```
Comment (tracernz) [inline fbw-a380x/src/systems/instruments/src/ND/OansControlPanel.tsx:647]: Make this MappedSubject a class prop rather than 3 instances of the exact same subject.

File: fbw-a380x/src/systems/instruments/src/ND/OansControlPanel.tsx [hunk 3]
```diff
@@ -823,16 +830,24 @@ export class OansControlPanel extends DisplayComponent<OansProps> {
...
+                      disabled={this.navigraphAvailable}
+                      onClick={() => {
+                        this.amdbClient
+                          .searchForAirports('')
+                          .then((airports) => {
+                            this.store.airports.set(airports);
+                            this.navigraphAvailable.set(true);
+                          })
+                          .catch(() => this.navigraphAvailable.set(false));
+                      }}
```
Comment (tracernz) [inline fbw-a380x/src/systems/instruments/src/ND/OansControlPanel.tsx:842]: It would be nicer to move non-trivial logic into a proper method rather than an inline function.

File: fbw-a380x/src/systems/instruments/src/ND/OansControlPanel.tsx [hunk 4]
```diff
@@ -179,23 +191,13 @@ export class OansControlPanel extends DisplayComponent<OansProps> {
       this.activeDatabase.set(`${from.getDay()}${months[from.getMonth()]}-${to.getDay()}${months[to.getMonth()]}`);
     });
 
-    const date = SimVar.GetGameVarValue('FLIGHT NAVDATA DATE RANGE', 'string');
-    if (date) {
-      this.secondDatabase.set(this.calculateSecDate(date));
-    }
+    NXDataStore.subscribe('NAVIGRAPH_ACCESS_TOKEN', () => this.loadOansDb());
+    this.loadOansDb();
```
[the remark this answers is not in the document]
Comment (flogross89) [reply fbw-a380x/src/systems/instruments/src/ND/OansControlPanel.tsx:195]: That's handy!

File: fbw-a380x/src/systems/instruments/src/ND/OansControlPanel.tsx (hunk 2 above)
Comment (flogross89) [reply fbw-a380x/src/systems/instruments/src/ND/OansControlPanel.tsx:647]: Makes sense, fixed in next commit

File: fbw-a380x/src/systems/instruments/src/ND/NDSimvarPublisher.tsx (hunk 1 above)
Comment (flogross89) [reply fbw-a380x/src/systems/instruments/src/ND/NDSimvarPublisher.tsx:41]: I thought I would keep it consistent with the pposLat&Lon, but I saw that those were also not used anymore. So I removed them (the ADR lat&lon are also used in the ND), and replaced pposAlt with ADR's baroCorrectedAltitude

File: fbw-a380x/src/systems/instruments/src/ND/NDSimvarPublisher.tsx [hunk 5]
```diff
@@ -34,11 +33,10 @@ export enum NDVars {
   ilsCourse = 'L:A32NX_FM_LS_COURSE',
   selectedHeading = 'L:A32NX_FCU_HEADING_SELECTED',
   showSelectedHeading = 'L:A320_FCU_SHOW_SELECTED_HEADING',
-  pposLat = 'PLANE LATITUDE', // TODO replace with fm position
-  pposLong = 'PLANE LONGITUDE', // TODO replace with fm position
   absoluteTime = 'E:ABSOLUTE TIME',
   kccuOnL = 'L:A32NX_KCCU_L_KBD_ON_OFF',
   kccuOnR = 'L:A32NX_KCCU_R_KBD_ON_OFF',
+  baroMode = 'KOHLSMAN SETTING STD',
```
Comment (tracernz) [inline fbw-a380x/src/systems/instruments/src/ND/NDSimvarPublisher.tsx:39]: The PFD uses Simplane for this via `SimplaneValueProvider`, which calls Simplane, and that ultimately reads from the LVAR `L:XMLVAR_Baro1_Mode` and does the following.
```js
if (val == 0)
                return "QFE";
            else if (val == 1)
                return "QNH";
            else
                return "STD";
```
We should probably not invent something new here that might get unexpectedly broken and won't show up when we search to rip all this out (already mostly done on the A320 in the FMGC PR).

File: fbw-common/src/systems/instruments/src/ND/pages/rose/RoseLSPage.tsx [hunk 6]
```diff
@@ -87,6 +87,23 @@ export class RoseLSPage<T extends number> extends RoseMode<T, RoseLsProps<T>> {
...
+          name="rose-mode-bottom-right-map-area"
+          d="M591,768 L591,626 L648,562 L723,562 L723,0 L768,0 L768,768 L591,769"
+          class="nd-inverted-map-area"
+        />
+        <path
+          name="rose-mode-top-map-area"
+          d="M45,0 L45,155, L282,155 a250,250 0 0 1 204,0 L723,155 L723,0 L45,0"
+          class="nd-inverted-map-area"
+        />
+
```
Comment (tracernz) [inline fbw-common/src/systems/instruments/src/ND/pages/rose/RoseLSPage.tsx:106]: Aren't these different between A320 and A380 so they can't go in fbw-common?

**Review by tracernz — COMMENTED** [review]
We will need a lot more specific test instructions with the changes affecting the A32NX being added.

File: fbw-common/src/systems/instruments/src/ND/pages/rose/RoseLSPage.tsx (hunk 6 above)
Comment (flogross89) [reply fbw-common/src/systems/instruments/src/ND/pages/rose/RoseLSPage.tsx:106]: For ROSE NAV, they are already there. The left and right info area are currently the same for A32NX and A380X. Even though you won't notice them in the A32NX (because the TERR doesn't go that far down), it doesn't hurt to have them here

**Comment by flogross89** [comment]
> We will need a lot more specific test instructions with the changes affecting the A32NX being added.

Yep, working on that

File: fbw-a380x/src/systems/instruments/src/ND/NDSimvarPublisher.tsx (hunk 5 above)
Comment (flogross89) [reply fbw-a380x/src/systems/instruments/src/ND/NDSimvarPublisher.tsx:39]: Ah, I thought SimplaneValueProvider was some old pattern we should avoid. I moved it to MsfsAvCommon, and also use it for the ND now.

File: fbw-common/src/systems/instruments/src/ND/pages/rose/RoseLSPage.tsx (hunk 6 above)
Comment (tracernz) [reply fbw-common/src/systems/instruments/src/ND/pages/rose/RoseLSPage.tsx:106]: The mask at the top is different though. The A380 mask extends above the rose, whereas the A320 has a cutout extending below the top of the rose except the area inside it.

Comment (flogross89) [reply fbw-common/src/systems/instruments/src/ND/pages/rose/RoseLSPage.tsx:106]: Yes, but removing the mask alone won't fix it, since SimBridge also somewhere has a mask on its own (which doesn't align with the ND roses so it doesn't look clean.
For now, until we can fix the SimBridge mask I prefer to have the top mask for both a/c

File: fbw-a380x/src/systems/instruments/src/ND/NDSimvarPublisher.tsx (hunk 5 above)
Comment (tracernz) [reply fbw-a380x/src/systems/instruments/src/ND/NDSimvarPublisher.tsx]: It's preferable to use the same old pattern rather than introducing another pattern that's not right :D.

**Review by tracernz — APPROVED** [review]

**Comment by nebj00la** [comment]
Quality Assurance Trainee Report

Discord Username  : nebj00la
Object of testing : #8876
Aircraft          : A32NX
Tier of Testing   : 2
Date              : 15/09/2024

Testing Process: 

1. Loaded experimental SimBridge.
2. Loaded flight plan from KPVD->KBOS.
3. Verified ARC page follows aircraft normally.
4. Verified VOR page operates as expected.
5. Verified LS page operates as expected.
6. Verified TERR on ND peaks mode works as expected in mountainous area. Both ARC and various ROSE modes validated.

Testing Results: 
Passed

Media:

**Comment by Letreivchen** [comment]
Quality Assurance Tester Report

Discord Username  : Letreiv
Object of testing : #8876  
Aircraft          : A380X 
Tier of Testing   : 1
Date              : 17/09/2024 

Testing Process: 
 
1)checked that If Navigraph is unlinked via the EFB, OANS does not show an amber "NOT AVAIL"
4)checked that VerticalDisplay does not show information with white lines if ADIRS aligned, less information with red lines if not aligned
5)checked that VD does not show altitude band, consistent with terrain information
6)checked that SD mailbox does not show any amber messages anymore


Testing Results: 
Passed  

Negatives:       

unable to test 2) and 3) due to insufficient .env file

Conclusions: 

Passed since 2) and 3) were successfully tested in exp
