### PR TITLE
fix(a32nx/fadec): Fix FADEC's output being incorrectly overridden by MCDU flex temp

### LINKED ISSUE #9826: Thrust FMA shows MAN FLX instead of MAN MCT during climb/cruise.
### Simulator Version

2020

### Aircraft Version

Development

### Build info

```json
{
    "built": "2025-01-30T13:21:35+00:00",
    "ref": "refs/heads/master",
    "sha": "702d5eb3bdf24e94ed9edf0c45ea23a3ee8c0a0c",
    "actor": "flogross89",
    "event_name": "manual",
    "pretty_release_name": "master:702d5eb3",
    "version": "a32nx-v0.13.0-dev.702d5eb"
}
```

### Describe the bug

When you push the thrust levers up to the flex detent, the FMA should show MAN MCT but instead it shows MAN FLEX, and this is after the levers have been pulled back to climb at the reduction height.  Further, the upper ECAM shows the engine thrust setting as MCT.

### Expected behavior

When I pushed the levers up to the flex detent, the FMA should show MAN MCT.

### Steps to reproduce

1. Takeoff with any flex temperature.
2. Pull levers back to climb at the reduction height.
3. During the climb, push the levers up the flex again.
4.  FMA shows MAN FLX #

### References (optional)

Image

### Additional info (optional)

_No response_

### Discord Username (optional)

_No response_

### PR DESCRIPTION
**Pull request by FozzieHi**
Fixes #9826

## Summary of Changes

It seems like a bit of legacy code was left behind and we were incorrectly overriding the FADEC's output to use the flex temperature entered into the MCDU instead of just using the FADEC's output now that it is simulated correctly.

## Additional context

Discord username (if different from GitHub): fozzie

## Testing instructions

1. Takeoff with a flex temp and a `MAN FLX` FMA.
2. At acceleration altitude, engage the auto thrust by going into the CLB detent.
3. Go back to the FLX/MCT detent, check that a `MAN MCT` FMA displays instead of a `MAN FLX` one.

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo**, **flybywire-aircraft-a380-842 (4K)** or **flybywire-aircraft-a380-842 (8K)** download link at the bottom of the page

### CODE REVIEW

File: fbw-a32nx/src/wasm/fbw_a320/src/FlyByWireInterface.cpp [hunk 1]
```diff
@@ -2734,6 +2714,10 @@ bool FlyByWireInterface::updateFadec(double sampleTime, int fadecIndex) {
 
   idEcuMaintenanceWord6[fadecIndex]->set(Arinc429Utils::toSimVar(fadecBusOutputs[fadecIndex].ecu_maintenance_word_6));
 
+  if (clientDataEnabled) {
```
Comment (FozzieHi) [inline fbw-a32nx/src/wasm/fbw_a320/src/FlyByWireInterface.cpp]: I'm not 100% sure if we still need this as I'm not familiar with this part of the code. We're doing this above:
```cpp
simConnectInterface.setClientDataFadecData(fadecInputs[fadecIndex].in.data);
simConnectInterface.setClientDataFadecInput(fadecInputs[fadecIndex].in.input);
```

Does this mean that this part of the code is no longer needed?

Comment (FozzieHi) [reply fbw-a32nx/src/wasm/fbw_a320/src/FlyByWireInterface.cpp]: Actually, that's setting the input right? So I'm guessing it is?

Comment (lukecologne) [reply fbw-a32nx/src/wasm/fbw_a320/src/FlyByWireInterface.cpp]: Yep, the code above is for setting the input to the FADEC, this is for setting the output of the FADEC when any other simulink model is active

Comment (lukecologne) [inline fbw-a32nx/src/wasm/fbw_a320/src/FlyByWireInterface.cpp]: `clientDataEnabled` is probably broader than needed, as it will enable pushing the bus outputs when any of the models is activated in simulink, although currently only the FMGC uses the FADEC bus AFAIK. So it might be better to manually check for if the FMGC client data is enabled

**Review by lukecologne — APPROVED** [review]
Really good catch! Just one small comment, otherwise good to go

File: fbw-a32nx/src/wasm/fbw_a320/src/FlyByWireInterface.cpp (hunk 1 above)
Comment (FozzieHi) [reply fbw-a32nx/src/wasm/fbw_a320/src/FlyByWireInterface.cpp]: `if (clientDataEnabled) {` is checked in quite a lot of updates, including RA, LGCIU, ADIRS, SFCC, ILS etc. Would those not have the same issue? Worth tackling in a different PR?

Comment (lukecologne) [reply fbw-a32nx/src/wasm/fbw_a320/src/FlyByWireInterface.cpp]: Yes, but these are used by two or more computers (except for ILS I guess), and they are all external to the FBW systems, so they are not internally simulated. But yeah this is not a huge issue, just for efficiency when running the models externally

Comment (FozzieHi) [reply fbw-a32nx/src/wasm/fbw_a320/src/FlyByWireInterface.cpp]: Committed now, is this what you were thinking?

Comment (lukecologne) [reply fbw-a32nx/src/wasm/fbw_a320/src/FlyByWireInterface.cpp]: Yep, exactly

**Comment by BravoMike99** [comment]
Dev team QA report

Discord Username  : bruno_pt99
Object of testing : #10532
Aircraft          : A32NX
Simulator         : 2020
Tier of Testing   : 1
Date              : 06/02/2026

Testing Process: 
Checked that MAN FLEX engages as usual.
After acceleration height, brought the thrust levers to CLB and then FLX/MCT. Verified MAN MCT appears on FMA.
Testing Results: 
Passed
