### PR TITLE
fix(mcdu): ND resets to departure when entering approach

### LINKED ISSUE #10559: MCDU F-PLAN Navigation Display Approach input issue
### Simulator Version

2020

### Aircraft Version

Stable

### Build info

```json
{
    "built": "2025-12-01T13:39:00+00:00",
    "ref": "refs/tags/v0.14.0",
    "sha": "703d758bc52e7f63e9c1557c6fbbf86ec0725f36",
    "actor": "flogross89",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.14.0",
    "version": "a32nx-v0.14.0-rel.703d758"
}
```

### Describe the bug

When entering the approach to the destination airport in the MCDU, the ND resets to the departure airport.

version 0.14.0
Image

### Expected behavior

Navigation display should stay on the last selected waypoint.
The pilot must see what he enters into the MCDU as temporary until he confirms the selection!

version 0.11.1
Image

### Steps to reproduce

Import or enter any flight plan into the MCDU (you can enter a SID procedure). On the MCDU F-Plan, scroll through the waypoints. The ND will display the corresponding position on the flight plan.

When selecting the destination airport for entering the approach procedure, the ND resets to the departure position.

This bug has been present since version 0.12.0.

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

_No response_

### PR DESCRIPTION
**Pull request by Ditoo29**
Fixes #10559

## Summary of Changes
Fixed the Navigation Display resetting to the departure airport when clicking the destination on the MCDU F-PLAN page and when selecting approach procedures.

- Added destination-specific return callback that reopens F-PLAN at destination offset (using sentinel `-1`)
- Added `setPlanCentre` calls after opening LAT REV for destination clicks to prevent unload handler override
- Added `focusPlanEndOnNd` helper to centre ND on plan end after approach/STAR/VIA selection
- Changed temporary F-PLAN INSERT to open at destination/end instead of departure (offset `-1` → `destinationAirportOffset`)

## Screenshots (if necessary)
https://github.com/user-attachments/assets/d339cb48-cd1f-4c9e-9e6f-a980f2290ba0

## References
Bug was reproducible since v0.12.0 as reported in #10559. Fix aligns with expected A320 FMS behaviour where the ND should remain centred on the destination/approach area when entering procedures.

Video references showing expected behaviour:
- https://youtu.be/kKhIENzsb0c?t=754
- https://youtu.be/TqLF8ySn7ok?t=601

## Additional context
Two files changed:
- `A320_Neo_CDU_FlightPlanPage.ts` — destination return callback + re-applied ND centre in both DEST paths
- `A320_Neo_CDU_AvailableArrivalsPage.ts` — centralized ND focus helper + calls after approach/STAR/VIA/INSERT actions

## Testing Instructions
1. Load a flight plan with at least 5 waypoints (e.g. LPPT → EGLL)
2. Open F-PLAN and scroll to show destination
3. Press DEST LSK — verify ND stays on destination
4. Press RETURN — verify F-PLAN reopens at destination
5. Select ARRIVAL > any ILS approach — verify ND immediately centres on destination/approach area
6. Select any STAR — verify ND stays centred on destination/approach
7. Press INSERT* — verify ND stays at end when FPLN closes

Discord username (if different from GitHub): dito29

### CODE REVIEW

**Comment by Benjozork** [comment]
Do we have references for the ND centering on selected procedures?

**Comment by Ditoo29** [comment]
> Do we have references for the ND centering on selected procedures?

I couldn’t find anything in the FCOMs that explicitly describes this exact issue, but from the general logic of the system it follows that the ND F‑PLAN view should be tied to the MCDU’s “invisible search bar” state—that is, which waypoints are currently visible in the F‑PLAN at any given moment.

Inserting an arrival in the MCDU should only update the flight‑plan structure and phase; it should not alter that visibility state, so the ND F‑PLAN should not jump back to the departure or reset its centering, but instead preserve the current waypoint view unless the pilot explicitly changes the ND mode or range.

**Comment by BravoMike99** [comment]
> > Do we have references for the ND centering on selected procedures?
> 
> I couldn’t find anything in the FCOMs that explicitly describes this exact issue, but from the general logic of the system it follows that the ND F‑PLAN view should be tied to the MCDU’s “invisible search bar” state—that is, which waypoints are currently visible in the F‑PLAN at any given moment.
> 
> Inserting an arrival in the MCDU should only update the flight‑plan structure and phase; it should not alter that visibility state, so the ND F‑PLAN should not jump back to the departure or reset its centering, but instead preserve the current waypoint view unless the pilot explicitly changes the ND mode or range.

Here should be a ref, it's as you describe right? https://youtu.be/kKhIENzsb0c?t=754

**Comment by Ditoo29** [comment]
> > > Do we have references for the ND centering on selected procedures?
> > 
> > 
> > I couldn’t find anything in the FCOMs that explicitly describes this exact issue, but from the general logic of the system it follows that the ND F‑PLAN view should be tied to the MCDU’s “invisible search bar” state—that is, which waypoints are currently visible in the F‑PLAN at any given moment.
> > Inserting an arrival in the MCDU should only update the flight‑plan structure and phase; it should not alter that visibility state, so the ND F‑PLAN should not jump back to the departure or reset its centering, but instead preserve the current waypoint view unless the pilot explicitly changes the ND mode or range.
> 
> Here should be a ref, it's as you describe right? https://youtu.be/kKhIENzsb0c?t=754

Hello, 
Exactly! As the captain inserts the arrival, you can see the FPLN on the ND stays on the selected waypoint it was before instead of resetting to the beginning of the FPLN. 
As for the temporary FPLN placement, the captain in the video is very fast choosing the arrival, and doesn't allow the temporary plan to be seen, but should follow the same logic!
This video aligns with what I implemented.
Thank you very much

**Comment by BravoMike99** [comment]
> > > > Do we have references for the ND centering on selected procedures?
> > > 
> > > 
> > > I couldn’t find anything in the FCOMs that explicitly describes this exact issue, but from the general logic of the system it follows that the ND F‑PLAN view should be tied to the MCDU’s “invisible search bar” state—that is, which waypoints are currently visible in the F‑PLAN at any given moment.
> > > Inserting an arrival in the MCDU should only update the flight‑plan structure and phase; it should not alter that visibility state, so the ND F‑PLAN should not jump back to the departure or reset its centering, but instead preserve the current waypoint view unless the pilot explicitly changes the ND mode or range.
> > 
> > 
> > Here should be a ref, it's as you describe right? https://youtu.be/kKhIENzsb0c?t=754
> 
> Hello, Exactly! As the captain inserts the arrival, you can see the FPLN on the ND stays on the selected waypoint it was before instead of resetting to the beginning of the FPLN. As for the temporary FPLN placement, the captain in the video is very fast choosing the arrival, and doesn't allow the temporary plan to be seen, but should follow the same logic! This video aligns with what I implemented. Thank you very much

Found a better one I think https://youtu.be/TqLF8ySn7ok?t=601 Looks like it jumps to the end of flight-plan?

**Comment by Ditoo29** [comment]
> > > > > Do we have references for the ND centering on selected procedures?
> > > > 
> > > > 
> > > > I couldn’t find anything in the FCOMs that explicitly describes this exact issue, but from the general logic of the system it follows that the ND F‑PLAN view should be tied to the MCDU’s “invisible search bar” state—that is, which waypoints are currently visible in the F‑PLAN at any given moment.
> > > > Inserting an arrival in the MCDU should only update the flight‑plan structure and phase; it should not alter that visibility state, so the ND F‑PLAN should not jump back to the departure or reset its centering, but instead preserve the current waypoint view unless the pilot explicitly changes the ND mode or range.
> > > 
> > > 
> > > Here should be a ref, it's as you describe right? https://youtu.be/kKhIENzsb0c?t=754
> > 
> > 
> > Hello, Exactly! As the captain inserts the arrival, you can see the FPLN on the ND stays on the selected waypoint it was before instead of resetting to the beginning of the FPLN. As for the temporary FPLN placement, the captain in the video is very fast choosing the arrival, and doesn't allow the temporary plan to be seen, but should follow the same logic! This video aligns with what I implemented. Thank you very much
> 
> Found a better one I think https://youtu.be/TqLF8ySn7ok?t=601 Looks like it jumps to the end of flight-plan?

Yes you are right, I think I need to adjust this then. I will let you know.

**Comment by Ditoo29** [comment]
I decided to start from scratch, and force pushed a clean reset closing the PR, sorry @BravoMike99. I'm still working on this, and will let you know once its finished, I will update the description.

**Comment by Ditoo29** [comment]
@BravoMike99 It's ready for review, added your videos as references, and made a video showing how its working with my fix. Thanks!

File: fbw-a32nx/src/systems/instruments/src/MCDU/legacy_pages/A320_Neo_CDU_AvailableArrivalsPage.ts [hunk 1]
```diff
@@ -820,4 +825,26 @@ export class CDUAvailableArrivalsPage {
...
     return false;
   }
+
+  private static focusPlanEndOnNd(
+    mcdu: LegacyFmsPageInterface,
+    forPlan = FlightPlanIndex.Active,
+    inAlternate = false,
+  ): void {
+    const parentPlan =
+      forPlan === FlightPlanIndex.Active ? mcdu.flightPlanService.activeOrTemporary : mcdu.getFlightPlan(forPlan);
```
Comment (BravoMike99) [inline fbw-a32nx/src/systems/instruments/src/MCDU/legacy_pages/A320_Neo_CDU_AvailableArrivalsPage.ts]: You should be able to call getFlightPlan directly as it does the check you just did here (FMCMainDisplay L349).

File: fbw-a32nx/src/systems/instruments/src/MCDU/legacy_pages/A320_Neo_CDU_AvailableArrivalsPage.ts [hunk 2]
```diff
@@ -820,4 +825,26 @@ export class CDUAvailableArrivalsPage {
...
+
+    if (!parentPlan) {
+      return;
+    }
+
+    const focusedPlan = inAlternate ? parentPlan.alternateFlightPlan : parentPlan;
+    const focusLegIndex =
+      typeof focusedPlan.destinationLegIndex === 'number' && focusedPlan.destinationLegIndex >= 0
```
Comment (BravoMike99) [inline fbw-a32nx/src/systems/instruments/src/MCDU/legacy_pages/A320_Neo_CDU_AvailableArrivalsPage.ts]: Do we need to check the type? It should always be number from what I can see

File: fbw-a32nx/src/systems/instruments/src/MCDU/legacy_pages/A320_Neo_CDU_FlightPlanPage.ts [hunk 3]
```diff
@@ -577,7 +583,12 @@ export class CDUFlightPlanPage {
             () => mcdu.getDelaySwitchPage(),
             (value, scratchpadCallback) => {
               if (value === '') {
+                mcdu.returnPageCallback = () => {
+                  CDUFlightPlanPage.ShowPage(mcdu, -1, forPlan);
+                };
```
Comment (BravoMike99) [inline fbw-a32nx/src/systems/instruments/src/MCDU/legacy_pages/A320_Neo_CDU_FlightPlanPage.ts]: I think you want to replace the line 59 with this instead as the page callback only needs to be set once, not per LSK

File: fbw-a32nx/src/systems/instruments/src/MCDU/legacy_pages/A320_Neo_CDU_FlightPlanPage.ts [hunk 4]
```diff
@@ -38,6 +38,8 @@ const Time = Object.freeze({
 
 export class CDUFlightPlanPage {
   static ShowPage(mcdu: LegacyFmsPageInterface, offset = 0, forPlan = 0) {
+    const focusDestinationOnOpen = offset < 0;
```
Comment (BravoMike99) [inline fbw-a32nx/src/systems/instruments/src/MCDU/legacy_pages/A320_Neo_CDU_FlightPlanPage.ts]: Perhaps you could add jsdoc to the showPage method to specify that negative values on the offset will force the destination.

**Review by BravoMike99 — CHANGES_REQUESTED** [review]
Just some small things

File: fbw-a32nx/src/systems/instruments/src/MCDU/legacy_pages/A320_Neo_CDU_FlightPlanPage.ts (hunk 4 above)
Comment (tracernz) [reply fbw-a32nx/src/systems/instruments/src/MCDU/legacy_pages/A320_Neo_CDU_FlightPlanPage.ts]: I think rather than having special values that can't be enforced by the type system it should be better to just have a helper that finds the destination index and then calls ShowPage.

**Comment by Ditoo29** [comment]
Hey @BravoMike99 all comments were fixed. Already squashed the commits. It's ready for review once again

**Comment by FoxtrotSierra6829** [comment]
Hey, please don't squash pushed commits in PRs unless there is a specific reason to do it ( if it helps better understand the PR). Our merge strategy is strictly squash and merge, so normally retaining the information can be beneficial and it reduces the need to delete the branch to be able to check it out again for the people who have already checked it out

File: fbw-a32nx/src/systems/instruments/src/MCDU/legacy_pages/A320_Neo_CDU_FlightPlanPage.ts [hunk 5]
```diff
@@ -577,7 +585,12 @@ export class CDUFlightPlanPage {
             () => mcdu.getDelaySwitchPage(),
             (value, scratchpadCallback) => {
               if (value === '') {
+                mcdu.returnPageCallback = () => {
```
Comment (BravoMike99) [inline fbw-a32nx/src/systems/instruments/src/MCDU/legacy_pages/A320_Neo_CDU_FlightPlanPage.ts]: I think you forgot to remove this one? Apart from that LGTM.

**Comment by Ditoo29** [comment]
@BravoMike99 took care of the last thing you had to say. Let me know

**Review by BravoMike99 — APPROVED** [review]
Obrigado 😄

File: .github/CHANGELOG.md [hunk 6]
```diff
@@ -1881,3 +1881,4 @@
 1. [EFB] Restructured APIs and made Navigraph Auth a reusable component - @MicahBCode (Mischa Binder)
 1. [ECAM] Added F units to CRZ and COND pages for Cabin temps. Currently tied to kg/lbs option in EFB -Patrick Macken  (@PatM on Discord)
 1. [A32NX/FCU] Fixed bug where the FCU selected altitude would immediately switch to 1000s on selecting the 1000ft inteval knob - @elliot747 (Elliot)
+1. [A32NX/MCDU] Fixed bug where the ND resets to the departure airport when selecting the destination for approach entry - @Ditoo29 (dito29 on discord)
```
Comment (BravoMike99) [inline .github/CHANGELOG.md]: The change-log seems to be in the wrong place but as it doesn't affect QA we can move on as long as it is fixed prior to merge.

Comment (Ditoo29) [reply .github/CHANGELOG.md]: Not sure if I understood, in the wrong place?

Comment (BravoMike99) [reply .github/CHANGELOG.md]: Yeah. It should be at the end of the 0.15 section of the changelog. (around line 105 in this case). Basically it goes top down with the newest version being at the top.

Comment (Ditoo29) [reply .github/CHANGELOG.md]: Oh I see, Im currently not home, but will change this soon and let you know

**Comment by Faneboom15** [comment]
Quality Assurance Trainee Report

Discord Username  : faneboom15 
Object of testing : #10594 
Aircraft          : A32NX 
Simulator         : 2020 
Tier of Testing   : 1
Date              : 06/04/2026 

Testing Process: 
 
Loaded flightplan with 10 waypoints from simbrief into aoc init and init A page.
Opened F-PLN page and confirmed waypoints are there
Switched ND to plan and then scrolled down to dest in F-PLN page, ND shows dest airport.
Pressed DEST LSK and verified ND stays on dest.
Pressed RETURN, flight plan reopens 1-2 waypoints before destination, dest airport is still visible within 20NM of the said waypoint that it is centered on.
Selected arrival, added ILS approach and STAR without TRANS/VIA, ND was centered in the dest/approach area the whole time.
Inserted arrival in F-PLN, ND is staying on the end/dest area.

Testing Results: 
Passed

File: .github/CHANGELOG.md (hunk 6 above)
Comment (Ditoo29) [reply .github/CHANGELOG.md]: All done :D
