### PR TITLE
fix: nd bugs and paths

### LINKED ISSUE #8438: Needles on ND have disappeared
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-01-20T23:45:41+00:00",
    "ref": "refs/heads/master",
    "sha": "d70bd6c8d838aaa41319596ce13ee7f7ede5c1c9",
    "actor": "frankkopp",
    "event_name": "manual",
    "pretty_release_name": "master:d70bd6c8",
    "version": "v0.12.0-dev.d70bd6c"
}
```

### Describe the bug

no more NDB needles displayed on the ND

### Expected behavior

information of nd well write  in left down corner ND, but no needle

### Steps to reproduce

near LFBD for BD adf (ndb)

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

_No response_

### LINKED ISSUE #8445: ND: VOR bearing pointer appears on top of DME & Chrono
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-01-25T02:53:25+00:00",
    "ref": "refs/heads/master",
    "sha": "cf1e4f4a3cebd96c68cdc4e82f6a1a6d875403ef",
    "actor": "Benjozork",
    "event_name": "manual",
    "pretty_release_name": "master:cf1e4f4a",
    "version": "v0.12.0-dev.cf1e4f4"
}
```

### Describe the bug

VOR Bearing pointer appears drawn on top of the VOR indications & chrono at the bottom of the ND. 
image
ND2

### Expected behavior

VOR bearing pointer should "stay behind" the VOR info & chrono.

### Steps to reproduce

Position yourself in such a way in relation to a VOR station so that the bearing pointer appears on the bottom area of the ND

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

bruno_pt99

### LINKED ISSUE #8449: Heading bug appears on ND after pressing TRK/FPA while in NAV mode
### Aircraft Version

Development

### Build info

```json
{
    "built": "2024-01-27T23:22:37+00:00",
    "ref": "refs/heads/master",
    "sha": "f79d82e6dc4ce68dd54aa6c095a9a28c132b9754",
    "actor": "aguther",
    "event_name": "manual",
    "pretty_release_name": "master:f79d82e6",
    "version": "v0.12.0-dev.f79d82e"
}
```

### Describe the bug

Pressing TRK/FPA button on the FCU while "NAV" mode is engaged causes the heading bug to appear on the Navigation Display.

https://github.com/flybywiresim/aircraft/assets/119708186/2e8336ba-e4e6-4e70-a340-9f8b5a27343f

### Expected behavior

ND bug not to appear since navigation is a managed mode.

### Steps to reproduce

Press TRK/FPA button on the FCU while "NAV" mode is engaged

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

bruno_pt99

### PR DESCRIPTION
**Pull request by Saschl**
Fixes #8445 
Fixes #8449 
Fixes #8438 

## Summary of Changes

Some further regressions and bugs in NDv2 that have been reported.

Namely:
ADF needles never showing after a C&D start
ADF and VOR needles not having a clip mask
Selected heading bug being shown in managed heading mode when switching to TRK/FPA and vice versa

## Additional context

Discord username (if different from GitHub):

## Testing instructions

1. ADF needles never showing after a C&D start
  1. Spawn C&D, tune a valid NDB (e.g. KEK or 403.0). Make sure the ADF needles appear on the ND when the ADIRS are not aligned and also after alignment). 
 1. Ensure the VOR and ADF needles never overlay the chrono/radio information on the ND (mainly lower left corner)

1. Selected heading bug being shown in managed heading mode when switching to TRK/FPA and vice versa
 1. Try the reproduction steps from https://github.com/flybywiresim/aircraft/issues/8449 and make sure the selected heading bug does not show (you must be airborne).

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

File: fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FCU/A320_Neo_FCU.js [hunk 1]
```diff
@@ -830,10 +830,13 @@ class A320_Neo_FCU_Heading extends A320_Neo_FCU_Component {
     }
 
     onTRKModeChanged(_newValue) {
-        if (_newValue) {
-            this.selectedValue = this.calculateTrackForHeading(this.selectedValue);
-        } else {
-            this.selectedValue = this.calculateHeadingForTrack(this.selectedValue);
+        // do not alter if we're in managed heading
```
Comment (tracernz) [inline fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FCU/A320_Neo_FCU.js:833]: What if a heading is pre-selected and you swap the ref mode?

File: fbw-common/src/systems/instruments/src/ND/shared/RadioNavInfo.tsx [hunk 2]
```diff
@@ -231,6 +230,10 @@ class AdfInfo extends DisplayComponent<{ bus: EventBus, index: 1 | 2, visible: S
         this.adfFrequency,
     );
 
+    private readonly visibilitySub = MappedSubject.create(
```
Comment (tracernz) [inline fbw-common/src/systems/instruments/src/ND/shared/RadioNavInfo.tsx:233]: `isVisible` is a bit nicer and more descriptive than `visibilitySub`. Hungarian notation is bad too 😛 .

File: fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FCU/A320_Neo_FCU.js (hunk 1 above)
Comment (Saschl) [reply fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FCU/A320_Neo_FCU.js]: Yeah this might not work.. used the same approach now as the PFD by using the dedicated simvar. Probably not how the real thing works but at least it's aligned now.

Comment (lukecologne) [reply fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FCU/A320_Neo_FCU.js]: I don't know if this exactly what was meant here, but the way the real thing works is that it sets the current selected hdg to the current actual trk, if the actual hdg was was within 5° of the selected hdg. If not, the value will stay the same. This applies no matter if a managed or a selected mode was engaged, as long as there is a value displayed and not dashes

Comment (Saschl) [reply fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FCU/A320_Neo_FCU.js]: Yeah I have reverted the change, not sure if the behaviour you described is implemented in the FCU currently, but that would rather be part of another PR (or even better, the new FCU eventually)

Comment (lukecologne) [reply fbw-a32nx/src/base/flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/FCU/A320_Neo_FCU.js]: No, the current FCU just magically knows the wind and always just calculates the corresponding HDG/TRK. The new FCU does it like I described

**Review by tracernz — APPROVED** [review]

**Comment by tylerclt** [comment]
Quality Assurance Trainee Report

Discord: tylerb780#3594
Object of testing: #8453
Tier of Testing: 1
Date: 08/02/2024

Testing Process: 
1. Loaded in Cold and Dark at KBHM at the ramp.
2. Powered Aircraft On. 
3. Tuned to the MCDEN NDB (224.0) to verify the navaid identification.
4. Verified there was no clip mask between the VOR/ADF and no overlay on the chrono when selected. (Tested on both ND’s)
5. Selected TRK/FPA mode while on the ground while in managed heading to see if the heading bug would display itself. 
6. Once airborne, I put the aircraft into managed heading and began to select TRK/FPA. This caused the heading bug to reappear even though the aircraft was still in managed heading. 

Negatives:       
The heading bug still reappears once put into TRK/FPA mode in the managed heading

Testing Results: 
Not Passed

Conclusions: 
No issues with the VOR/NDB tuning. 
No noticeable clip mask with the VOR and ADF needles

Media:

**Comment by tylerclt** [comment]
Quality Assurance Trainee Report

Discord: tylerb780#3594
Object of testing: #8453 
Tier of Testing: 1
Date: (15/02/2024)

Testing Process: 
1. Loaded in Cold and Dark at KBHM at the ramp.
2. Powered Aircraft On.
3. Tuned to the MCDEN NDB (224.0) to verify the navaid identification.
4. Verified there was no clip mask between the VOR/ADF and no overlay on the chrono when selected. (Tested on both ND’s)
5. Once airborne, the aircraft was put into managed heading mode. I then selected TRK/FPA and then I returned it to normal heading mode. 
6. Verified that there were no issues 

Negatives:       
N/A

Testing Results: 
Passed

Conclusions: 
Testing passed! 

Media:
