### PR TITLE
fix(380x/mfd): enter dest data message not clearing automatically

### LINKED ISSUE #9836: The label ENTER TEST DATA on the APPR tab
### Simulator

2020

### Aircraft Version

Development (4k)

### Build info

```json
{
    "built": "2025-02-06T13:48:07+00:00",
    "ref": "refs/heads/master",
    "sha": "9cfc51f7e4fbb230f017d205567a598626c928eb",
    "actor": "tracernz",
    "event_name": "manual",
    "pretty_release_name": "master:9cfc51f7",
    "version": "a380x-v0.13.0-dev.9cfc51f"
}
```

### Describe the bug

On the "APPR" tab, the "ENTER DEST DATA" message does not disappear after entering all the necessary landing data. It used to disappear on its own.
Image

### Expected behavior

On the "APPR" tab, the "ENTER DEST DATA" message should disappear, signaling that all the landing data has been entered correctly.

### Steps to reproduce

Before boarding, open the "APPR" tab. 
Fill in all the necessary information for boarding. 
The label is still displayed in yellow. It can only be cleaned manually.

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

Dron

### PR DESCRIPTION
**Pull request by BravoMike99**
Fixes #9836 

## Summary of Changes

Fixes destination data message not automatically clearing after the required data is inserted.
## Additional context

Discord username (if different from GitHub):
bruno_pt99
## Testing instructions

A380X:
Program a flight plan of your choice and be at less than 180NM from the destination in the cruise phase without any data entered on the PERF APPR page. Verify "ENTER DEST DATA" amber message appears.
Insert Wind, QNH & temperature on the PERF APPR page and verify the message automatically disappears after doing so. 
A32NX (regression testing):  
Verify you can update & clear the winds in the approach performance page and that the VAPP is updated accordingly. 
Check that ENTER DEST DATA message works (same instructions as the a380x ones)

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo**, **flybywire-aircraft-a380-842 (4K)** or **flybywire-aircraft-a380-842 (8K)** download link at the bottom of the page

### CODE REVIEW

File: fbw-a32nx/src/systems/instruments/src/MCDU/legacy/A32NX_FMCMainDisplay.ts [hunk 1]
```diff
@@ -5100,12 +5101,12 @@ export abstract class FMCMainDisplay implements FmsDataInterface, FmsDisplayInte
...
   }
 
-  public getApproachWind() {
+  public getApproachWind(): FmcWindVector | null {
     const activePlan = this.currFlightPlanService.active;
     const destination = activePlan.destinationAirport;
 
-    if (!destination || !destination.location || !isFinite(this.perfApprWindHeading)) {
-      return { direction: 0, speed: 0 };
+    if (!destination || !destination.location || this.perfApprWindHeading == null || this.perfApprWindSpeed == null) {
```
Comment (tracernz) [inline fbw-a32nx/src/systems/instruments/src/MCDU/legacy/A32NX_FMCMainDisplay.ts:5108]:
```suggestion
    if (!destination || !destination.location || this.perfApprWindHeading === null || this.perfApprWindSpeed === null) {
```

File: fbw-a32nx/src/systems/instruments/src/MCDU/legacy/A32NX_FMCMainDisplay.ts [hunk 2]
```diff
@@ -4391,7 +4392,7 @@ export abstract class FMCMainDisplay implements FmsDataInterface, FmsDisplayInte
   }
 
   public updateTowerHeadwind() {
-    if (isFinite(this.perfApprWindSpeed) && isFinite(this.perfApprWindHeading)) {
+    if (this.perfApprWindHeading != null && this.perfApprWindSpeed != null) {
```
Comment (tracernz) [inline fbw-a32nx/src/systems/instruments/src/MCDU/legacy/A32NX_FMCMainDisplay.ts:4395]:
```suggestion
    if (this.perfApprWindHeading !== null && this.perfApprWindSpeed !== null) {
```

File: fbw-a32nx/src/systems/instruments/src/MCDU/legacy/A32NX_FMCMainDisplay.ts [hunk 3]
```diff
@@ -4040,7 +4041,7 @@ export abstract class FMCMainDisplay implements FmsDataInterface, FmsDisplayInte
    */
   private getVAppGsMini() {
     let vAppTarget = this.getVApp();
-    if (isFinite(this.perfApprWindSpeed) && isFinite(this.perfApprWindHeading)) {
+    if (this.perfApprWindSpeed !== null && this.perfApprWindHeading != null) {
```
Comment (tracernz) [inline fbw-a32nx/src/systems/instruments/src/MCDU/legacy/A32NX_FMCMainDisplay.ts:4044]:
```suggestion
    if (this.perfApprWindSpeed !== null && this.perfApprWindHeading !== null) {
```

File: fbw-a32nx/src/systems/instruments/src/MCDU/legacy/A32NX_FMCMainDisplay.ts [hunk 4]
```diff
@@ -2033,8 +2034,8 @@ export abstract class FMCMainDisplay implements FmsDataInterface, FmsDisplayInte
       return (
         isFinite(this.perfApprQNH) &&
         isFinite(this.perfApprTemp) &&
-        isFinite(this.perfApprWindHeading) &&
-        isFinite(this.perfApprWindSpeed)
+        this.perfApprWindHeading != null &&
+        this.perfApprWindSpeed != null
```
Comment (tracernz) [inline fbw-a32nx/src/systems/instruments/src/MCDU/legacy/A32NX_FMCMainDisplay.ts:2038]:
```suggestion
        this.perfApprWindHeading !== null &&
        this.perfApprWindSpeed !== null
```

File: fbw-a32nx/src/systems/instruments/src/MCDU/legacy/A32NX_FMCMainDisplay.ts [hunk 5]
```diff
@@ -1515,7 +1516,7 @@ export abstract class FMCMainDisplay implements FmsDataInterface, FmsDisplayInte
       weight = this.zeroFuelWeight + Math.max(0, (vnavPrediction.estimatedFuelOnBoard * 0.4535934) / 1000);
     }
     // if pilot has set approach wind in MCDU we use it, otherwise fall back to current measured wind
-    if (isFinite(this.perfApprWindSpeed) && isFinite(this.perfApprWindHeading)) {
+    if (this.perfApprWindSpeed != null && this.perfApprWindHeading != null) {
```
Comment (tracernz) [inline fbw-a32nx/src/systems/instruments/src/MCDU/legacy/A32NX_FMCMainDisplay.ts:1519]:
```suggestion
    if (this.perfApprWindSpeed !== null && this.perfApprWindHeading !== null) {
```

File: fbw-a32nx/src/systems/instruments/src/MCDU/legacy_pages/A320_Neo_CDU_PerformancePage.ts [hunk 6]
```diff
@@ -924,11 +924,11 @@ export class CDUPerformancePage {
       }
     };
     let magWindHeadingCell = '[\xa0]';
-    if (isFinite(mcdu.perfApprWindHeading)) {
+    if (mcdu.perfApprWindHeading != null) {
```
Comment (tracernz) [inline fbw-a32nx/src/systems/instruments/src/MCDU/legacy_pages/A320_Neo_CDU_PerformancePage.ts:927]:
```suggestion
    if (mcdu.perfApprWindHeading !== null) {
```

File: fbw-a32nx/src/systems/instruments/src/MCDU/legacy_pages/A320_Neo_CDU_PerformancePage.ts [hunk 7]
```diff
@@ -924,11 +924,11 @@ export class CDUPerformancePage {
...
       magWindHeadingCell = ('' + mcdu.perfApprWindHeading.toFixed(0)).padStart(3, '0');
     }
     let magWindSpeedCell = '[\xa0]';
-    if (isFinite(mcdu.perfApprWindSpeed)) {
+    if (mcdu.perfApprWindSpeed != null) {
```
Comment (tracernz) [inline fbw-a32nx/src/systems/instruments/src/MCDU/legacy_pages/A320_Neo_CDU_PerformancePage.ts:931]:
```suggestion
    if (mcdu.perfApprWindSpeed !== null) {
```

File: fbw-a380x/src/systems/instruments/src/MFD/FMC/FlightManagementComputer.ts [hunk 8]
```diff
@@ -205,6 +205,15 @@ export class FlightManagementComputer implements FmcInterface {
 
   private wasReset = false;
 
+  private readonly destDataEntered = MappedSubject.create(
+    ([qnh, temperature, wind]) => qnh !== null && temperature != null && wind !== null,
```
Comment (tracernz) [inline fbw-a380x/src/systems/instruments/src/MFD/FMC/FlightManagementComputer.ts:209]:
```suggestion
    ([qnh, temperature, wind]) => qnh !== null && temperature !== null && wind !== null,
```

File: fbw-a380x/src/systems/instruments/src/MFD/FMC/FmcAircraftInterface.ts [hunk 9]
```diff
@@ -979,7 +979,7 @@ export class FmcAircraftInterface {
     let towerHeadwind = 0;
     const appWind = this.fmgc.data.approachWind.get();
     const destRwy = this.fmgc.getDestinationRunway();
-    if (appWind && Number.isFinite(appWind.speed) && Number.isFinite(appWind.direction)) {
+    if (appWind) {
```
Comment (tracernz) [inline fbw-a380x/src/systems/instruments/src/MFD/FMC/FmcAircraftInterface.ts:982]:
```suggestion
    if (appWind !== null) {
```

File: fbw-a380x/src/systems/instruments/src/MFD/FMC/FmcAircraftInterface.ts [hunk 10]
```diff
@@ -1196,7 +1196,7 @@ export class FmcAircraftInterface {
     // if pilot has set approach wind in MCDU we use it, otherwise fall back to current measured wind
     const appWind = this.fmgc.data.approachWind.get();
     let towerHeadwind = 0;
-    if (appWind && Number.isFinite(appWind.speed) && Number.isFinite(appWind.direction)) {
+    if (appWind) {
```
Comment (tracernz) [inline fbw-a380x/src/systems/instruments/src/MFD/FMC/FmcAircraftInterface.ts:1199]:
```suggestion
    if (appWind !== null) {
```

File: fbw-a380x/src/systems/instruments/src/MFD/FMC/fmgc.ts [hunk 11]
```diff
@@ -232,7 +232,15 @@ export class FmgcData {
 
   public readonly approachSpeed = Subject.create<Knots | null>(null);
 
-  public readonly approachWind = Subject.create<FmcWindVector | null>(null);
+  public readonly approachWindDirection = Subject.create<number | null>(null);
+
+  public readonly approachWindSpeed = Subject.create<number | null>(null);
+
+  public readonly approachWind: MappedSubject<number[], FmcWindVector | null> = MappedSubject.create(
+    ([direction, speed]) => (direction != null && speed !== null ? { direction: direction, speed: speed } : null),
```
Comment (tracernz) [inline fbw-a380x/src/systems/instruments/src/MFD/FMC/fmgc.ts:240]:
```suggestion
    ([direction, speed]) => (direction !== null && speed !== null ? { direction: direction, speed: speed } : null),
```

**Review by tracernz — COMMENTED** [review]
Nice. Just some nits for strict type safety.

**Comment by BravoMike99** [comment]
> Nice. Just some nits for strict type safety.

Thanks, should be sorted now if I didn't miss any.

**Review by tracernz — APPROVED** [review]

**Comment by utkrishtm** [comment]
Hey quick question. For the A380X, is the VAPP supposed to be adjusted based on the APPR wind speeds?

**Comment by utkrishtm** [comment]
Quality Assurance Trainee Report

Discord Username  : utkrishtm
Object of testing : #9896
Aircraft          : A380X
Tier of Testing   : 1
Date              : 08/04/2025

Testing Process: 
A380X:
OTHH - OMDB 277 NM 
Cruise Phase started 230NM away from OMDB
Once I clicked the altitude button to enter DESCENT Phase 110NM away from OMDB, I got the message for "Enter Dest Data". Until I clicked the altitude button there was no message. The message does disappear after putting in the information. The VAPP does update accordingly to the winds speed.

Not sure if that message behavior is correct. I thought it should automatically appear before TOD. But it only appeared once I entered the DESCENT Phase

A32NX (regression testing):
OTHH - OMDB 277 NM 
works as intended. The message comes on its own and VAPP is updated based on the wind speeds

Testing Results: 
Passed

Media:
No Amber Message

**Comment by Jonny23787** [comment]
Quality Assurance Trainee Report

Discord Username  : jonny_23
Object of testing : #9896 
Aircraft          : A32NX/A380X
Tier of Testing   : 1
Date              : 21/05/2025 

Testing Process: 

1. Performed full flight in A380X, was less than 180NM from the destination without any data entered on the PERF APPR page. Verified "ENTER DEST DATA" amber message appeared.
2. Inserted Wind, QNH & temperature on the PERF APPR page and verified the message automatically disappeared.
3. Repeated steps 1 and 2 in A32NX, confirmed it worked the same.


Testing Results: 
Passed

Negatives:       
Some small issues however @BravoMike99 knows about them and they will be fixed later.
