### PR TITLE
fix(a380x/sd): BLEED: crossbleed indications, ENG BLEED OFF fault; APU BLEED pressure for engine start

### LINKED ISSUE #9981: [A380X] Engine starter pressure abnormally low before starting engine
### Simulator

2020

### Aircraft Version

Stable (8k)

### Build info

```json
master
```

### Describe the bug

When selecting the ENG START selector to IGN START, the engine starter pressure displayed on the SD ENG page, lower part, seems abnormally low (~14 PSI). Only when starting the engine start process by switching the engine master switch to on, the engine starter pressure rises above 35 PSI

Image

### Expected behavior

Engine starter pressure should be in a normal range even before the ENG START selector is turned to IGN START. 

Image

### Steps to reproduce

see above

### References (optional)

https://youtu.be/AI8yFhuEa4Q?si=C_e7KBvTMqvb1tkk&t=960

### Additional info (optional)

_No response_

### Discord Username (optional)

floridude

### PR DESCRIPTION
**Pull request by flogross89**
Fixes #9981 

## Summary of Changes

- Draw crossbleed lines when crossbleed open
- Add GND HP inlet indication when on ground and below 50kts CAS
- Fix APU bleed pressure
- Add FWS abnormal sensed proc.: APU BLEED FAULT when outside APU BLEED operational envelope
- Add FWS abnormal sensed proc.: ENG 1/2/3/4 BLEED OFF

## Screenshots (if necessary)

Packs on, APU bleed on:
image

Packs off, APU bleed on: 
image

Pack 1 off: 
image

Pack 2 off: 
image

## Additional context

Discord username (if different from GitHub):

## Testing instructions

1. Start cold&dark at gate, start up APU
2. Enable APU bleed
3. Start all engines using APU bleed, either in pairs (1+2, 3+4) or single
4. Take-off, climb above 22500ft, turn on APU and APU BLEED, "APU BLEED FAULT" should be displayed on EWD (together with master caution + chime)
5. Turn off engine bleeds one by one, respective "ENG x BLEED OFF" should be displayed on EWD (together with master caution + chime)

Verify that indications on SD BLEED for all steps match the above and seem plausible. 
Additionally, bleed pressure for engine starts (on SD ENG) should be > 20 PSI, the indication should be green during and prior to engine start

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo**, **flybywire-aircraft-a380-842 (4K)** or **flybywire-aircraft-a380-842 (8K)** download link at the bottom of the page

### CODE REVIEW

File: fbw-a380x/src/systems/systems-host/systems/FlightWarningSystem/FwsCore.ts [hunk 1]
```diff
@@ -2198,6 +2211,16 @@ export class FwsCore {
     this.apuAvail.set(SimVar.GetSimVarValue('L:A32NX_OVHD_APU_START_PB_IS_AVAILABLE', 'bool'));
     this.apuBleedValveOpen.set(SimVar.GetSimVarValue('L:A32NX_APU_BLEED_AIR_VALVE_OPEN', 'bool'));
 
+    this.apuBleedPbOn.set(SimVar.GetSimVarValue('L:A32NX_OVHD_PNEU_APU_BLEED_PB_IS_ON', SimVarValueType.Bool));
+    const machBelow56 = this.machSelectedFromAdr.get() < 0.56;
+    const apuWithinEnvelope = this.adrPressureAltitude.get() < 22_500 && (machBelow56 || this.allEngFault.get());
+    this.apuBleedPbOnOver22500ft.set(this.apuBleedPbOn.get() && !apuWithinEnvelope);
+
+    this.eng1BleedOff.set(!SimVar.GetSimVarValue('A:BLEED AIR ENGINE:1', SimVarValueType.Bool));
```
Comment (BravoMike99) [inline fbw-a380x/src/systems/systems-host/systems/FlightWarningSystem/FwsCore.ts:2219]: Should also check if the associated engine is running.

Comment (flogross89) [reply fbw-a380x/src/systems/systems-host/systems/FlightWarningSystem/FwsCore.ts:2219]: indeed, thanks for the find

File: fbw-a380x/src/systems/instruments/src/SD/Pages/Bleed/elements/BleedCrossbleed.tsx [hunk 2]
```diff
@@ -35,6 +42,22 @@ const BleedCrossbleed: FC = () => {
         position={rhCrossBleedValveOpen ? 'H' : 'V'}
         sdacDatum={sdacDatum}
       />
+      <path
+        className={`${allCrossBleedValveOpen && isPack1Operative ? 'Show' : 'Hide'} Line Green NoFill`}
```
Comment (BravoMike99) [inline fbw-a380x/src/systems/instruments/src/SD/Pages/Bleed/elements/BleedCrossbleed.tsx:46]: I don't think these should depend on the associated pack being operative from the FCOM diagrams or is there no way to know if there's bleed air flowing that way?

File: fbw-a380x/src/systems/systems-host/systems/FlightWarningSystem/FwsCore.ts [hunk 3]
```diff
@@ -2198,6 +2211,24 @@ export class FwsCore {
     this.apuAvail.set(SimVar.GetSimVarValue('L:A32NX_OVHD_APU_START_PB_IS_AVAILABLE', 'bool'));
     this.apuBleedValveOpen.set(SimVar.GetSimVarValue('L:A32NX_APU_BLEED_AIR_VALVE_OPEN', 'bool'));
 
+    this.apuBleedPbOn.set(SimVar.GetSimVarValue('L:A32NX_OVHD_PNEU_APU_BLEED_PB_IS_ON', SimVarValueType.Bool));
+    const machBelow56 = this.machSelectedFromAdr.get() < 0.56;
+    const apuWithinEnvelope = this.adrPressureAltitude.get() < 22_500 && (machBelow56 || this.allEngFault.get());
+    this.apuBleedPbOnOver22500ft.set(this.apuBleedPbOn.get() && !apuWithinEnvelope);
+
+    this.eng1BleedAbnormalOff.set(
+      this.engine1Running.get() && !SimVar.GetSimVarValue('A:BLEED AIR ENGINE:1', SimVarValueType.Bool),
```
Comment (BravoMike99) [inline fbw-a380x/src/systems/systems-host/systems/FlightWarningSystem/FwsCore.ts:2220]: We should probably change these eventually to OVHD_PNEU_ENG_*index*_BLEED_PB_IS_AUTO and in the xml but that can be left for future work.

Comment (flogross89) [reply fbw-a380x/src/systems/systems-host/systems/FlightWarningSystem/FwsCore.ts:2220]: Indeed, currently we don't have a way to differentiate between manual OFF and FAULT... But it seems that would be some more adaptions on the bleed system, should be solved in Rust. So I'll leave it out of scope for this PR, and add a FIXME.

File: fbw-a380x/src/systems/instruments/src/SD/Pages/Bleed/elements/BleedCrossbleed.tsx (hunk 2 above)
Comment (flogross89) [reply fbw-a380x/src/systems/instruments/src/SD/Pages/Bleed/elements/BleedCrossbleed.tsx:46]: Tricky, don't know the bleed system that well. But you're right, packs are the wrong dependency. I'll have a look at some SimVars

Comment (flogross89) [reply fbw-a380x/src/systems/instruments/src/SD/Pages/Bleed/elements/BleedCrossbleed.tsx:46]: After some checking, it seems it's not transparent there's actually bleed air flowing, we can just somehow estimate that by looking at valves. Also, by having 4 pack flow valves, 3 crossbleed valves and 5 possible bleed sources there's a lot of possible combinations. For now I'll assume all flow valves from one pack are operative, and all three crossbleed valves operate the same way. But I'll change to checking the pack flow valves instead of the pack status

File: fbw-a380x/src/systems/systems-host/systems/FlightWarningSystem/FwsCore.ts [hunk 4]
```diff
@@ -2198,6 +2211,30 @@ export class FwsCore {
     this.apuAvail.set(SimVar.GetSimVarValue('L:A32NX_OVHD_APU_START_PB_IS_AVAILABLE', 'bool'));
     this.apuBleedValveOpen.set(SimVar.GetSimVarValue('L:A32NX_APU_BLEED_AIR_VALVE_OPEN', 'bool'));
 
+    this.apuBleedPbOn.set(SimVar.GetSimVarValue('L:A32NX_OVHD_PNEU_APU_BLEED_PB_IS_ON', SimVarValueType.Bool));
+    const machBelow56 = this.machSelectedFromAdr.get() < 0.56;
+    const apuWithinEnvelope = this.adrPressureAltitude.get() < 22_500 && (machBelow56 || this.allEngFault.get());
+    this.apuBleedPbOnOver22500ft.set(this.apuBleedPbOn.get() && !apuWithinEnvelope);
+
+    // FIXME should be OVHD_PNEU_ENG_index_BLEED_PB_IS_AUTO to fetch the push button status separately from the bleed status
```
Comment (BravoMike99) [inline fbw-a380x/src/systems/systems-host/systems/FlightWarningSystem/FwsCore.ts:2219]: I guess this comment is no longer needed? Apart from that looks good

Comment (flogross89) [reply fbw-a380x/src/systems/systems-host/systems/FlightWarningSystem/FwsCore.ts:2219]: missed that, thanks!

File: fbw-a380x/src/systems/systems-host/systems/FlightWarningSystem/FwsCore.ts (hunk 3 above)
Comment (flogross89) [reply fbw-a380x/src/systems/systems-host/systems/FlightWarningSystem/FwsCore.ts]: see other convo, resolved

**Review by BravoMike99 — APPROVED** [review]

**Comment by Jonny23787** [comment]
Quality Assurance Trainee Report

Discord Username  : jonny_23
Object of testing : #9980 
Aircraft          : A380X
Tier of Testing   : 1
Date              : 13/04/2025 

Testing Process: 

1. Loaded aircraft at gate, started APU, started engines using APU bleed.
2. Climbed to 25000ft, started APU and bleed, ECAM warning appeared.
3. Switched ENG X bleed off, ECAM warning appeared for respective engine.

Testing Results: 
Not Passed

Negatives:       

1. PSI during engine start up dipped below 30 PSI to 29 PSI for a split second for engine 3 once engine 1 and 2 had started, engines 3 and 4 were being started simultaneously.
2. Master warning and chime could not be seen or heard when the APU BLEED or ENG X BLEED OFF faults appeared.
3. (See screenshot) When the APU BLEED FAULT appeared, the APU BLEED: OFF step had already been ticked off, even though the APU BLEED was still on.

Conclusions: 
Not passed, do not merge

Media:
Screenshot 2025-04-13 090344

**Comment by flogross89** [comment]
@Jonny23787 Thanks!
1. The 30 PSI threshold is arbitrary, I'd regard that as passed neverthelesse. It was 0 before, now it's a believable pressure. I'll change the test description
2. & 3. Two small errors I made, I just fixed them and pushed the commits. Ready for a re-test if you have the time.

**Comment by Jonny23787** [comment]
Quality Assurance Trainee Report

Discord Username  : jonny_23
Object of testing : #9980 
Aircraft          : A380X
Tier of Testing   : 1
Date              : 13/04/2025 

Testing Process: 

1. Loaded at gate, started APU selected APU BLEED.
2. Tried multiple pack and bleed combinations, confirmed they matched screenshots provided.
3. Started engines, confirmed PSI was above 20.
4. Climbed to 25000ft, switched APU and APU bleed on, confirmed fault appeared along with chime and master warning.
5. Tested by @flogross89. 

Testing Results: 
Passed
