### PR TITLE
fix(a380/flaps): fixed A380 FPPU angles

### LINKED ISSUE #10183: A380 flaps/slats angles
### Aircraft Version

Development

### Description

The current A380 slats and flaps angles are wrong. Also, the SFCC ARINC labels are different from the A320: changes to these has a knock on effect on the avionics reading these labels.

### References (optional)

_No response_

### Additional info (optional)

```rust
// Current (wrong) code
const FLAP_FPPU_TO_SURFACE_ANGLE_BREAKPTS: [f64; 12] = [0., 35.66, 69.32, 89.7, 105.29, 120.22, 145.51, 168.35, 189.87, 210.69, 231.25, 251.97,];
const FLAP_FPPU_TO_SURFACE_ANGLE_DEGREES: [f64; 12] = [0., 1.3, 2.5, 5., 7.5, 10., 15., 20., 25., 30., 35., 40.];
const SLAT_FPPU_TO_SURFACE_ANGLE_BREAKPTS: [f64; 12] = [0., 66.83, 167.08, 222.27, 272.27, 334.16, 334.16, 334.16, 334.16, 334.16, 334.16, 334.16,];
const SLAT_FPPU_TO_SURFACE_ANGLE_DEGREES: [f64; 12] = [0., 5.4, 13.5, 18., 22., 27., 27., 27., 27., 27., 27., 27.];


// Correct code
const FLAP_FPPU_TO_SURFACE_ANGLE_BREAKPTS: [f64; 12] = [0., 122.2, 215.68, 259.28, 279.84, 297.59, 338.99, 338.99, 338.99, 338.99, 338.99, 338.99,];
const FLAP_FPPU_TO_SURFACE_ANGLE_DEGREES: [f64; 12] = [0., 0., 8., 17., 22., 26., 33., 33., 33., 33., 33., 33.];
const SLAT_FPPU_TO_SURFACE_ANGLE_BREAKPTS: [f64; 12] = [0., 286.48, 327.39, 327.39, 327.39, 327.39, 327.39, 327.39, 327.39, 327.39, 327.39, 327.39,];
const SLAT_FPPU_TO_SURFACE_ANGLE_DEGREES: [f64; 12] = [0., 20., 23., 23., 23., 23., 23., 23., 23., 23., 23., 23.];```



### Discord Username (optional)

pythonist

### PR DESCRIPTION
**Pull request by Eagle941**
Fixes #10183

## Summary of Changes

This PR corrects the FPPU angles for the A380
Changes the FPPU angles implemented in #8651 (for reference)

Rust (pythonist):

- [x] Update `fn slat_flap_actual_position_word` with correct FPPU thresholds + update a380x simvar doc accordingly

TS (floridude): 

- [x] PFD update flapsPositionRaw / slatsPositionRaw for lower area display
- [x] Check FWS for flap conditions

FBW MATLAB (floridude):

- [x] Update actual flap/slat angles where ever used (only in PRIM FE)

## Screenshots (if necessary)

N/A

## References

ATA27-50

## Additional context

| CONF | Flap surface angle | Flap FPPU angle | Slat surface angle | Slat FPPU angle |
|------|--------------------|-----------------|--------------------|-----------------|
| 0    | 0                  | 0               | 0                  | 0               |
| 1    | 0                  | 0               | 20                 | 286.48          |
| 1+F  | 8                  | 215.68          | 20                 | 286.48          |
| 2    | 17                 | 259.28          | 20                 | 286.48          |
| 2*   | 17                 | 259.28          | 23                 | 327.39          |
| 3    | 26                 | 297.59          | 23                 | 327.39          |
| FULL | 33                 | 338.99          | 23                 | 327.39          |

Discord username (if different from GitHub): pythonist

## Testing instructions

This change impacts the A380 only and it doesn't introduce any additional feature.
The purpose of this testing is to check that the FAC, GPWS and PFD still work correctly.
- Execute a standard circuit and verify correct behaviour of the flaps/slats indication in the lower PFD
- Execute a standard circuit with engine out after takeoff. Engage the autopilot and verify correct rudder behaviour with different flaps extensions.
- Execute a standard circuit, on final set landing gear down with flaps 2 and 170kt. Verify the alert "TOO LOW FLAPS" is triggered below about 200ft AGL.

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo**, **flybywire-aircraft-a380-842 (4K)** or **flybywire-aircraft-a380-842 (8K)** download link at the bottom of the page

### CODE REVIEW

File: fbw-common/src/wasm/systems/systems/src/hydraulic/flap_slat.rs [hunk 1]
```diff
@@ -323,6 +324,16 @@ impl FlapSlatAssembly {
...
 
+        println!(
+            "Max Synchro angle {:.2} | synchro {:.2} | surface arm {:.2} | max surface arm {:.2} | speed {:.3}",
+            self.max_synchro_gear_position.get::<degree>(),
+            self.position_feedback().get::<degree>(),
+            self.surface_control_arm_position.get::<degree>(),
+            self.synchro_angle_to_surface_angle(self.max_synchro_gear_position)
+                .get::<degree>(),
+            self.speed.get::<radian_per_second>()
+        );
```
Comment (beheh) [inline fbw-common/src/wasm/systems/systems/src/hydraulic/flap_slat.rs]: I understand this is probably for debugging, but this should likely go before merging this. Flagging it now so we don't forget about this.

**Review by beheh — APPROVED** [review]

**Comment by BravoMike99** [comment]
Dev team QA report

Discord Username  : bruno_pt99
Object of testing : #10316 
Aircraft          : A380X
Simulator         : 2020
Tier of Testing   : 1
Date              : 15/11/2025

Testing Process: 
Checked multiple flap settings and verified PFD indication updates accordingly ✔️ 
Shutdown engine nr 4 during takeoff and checked autopilot rudder operation throughout multiple flap settings❌ Rudder was never applied by the autopilot.
Checked TOO LOW FLAPS mode still works on the GPWS. Logic seems wonky and its still using flap lever rather than angle so it works as before/out of scope ✔️ 

Testing Results: 
Not Passed 

Negatives:       
Autopilot does not apply rudder trim at all in case of an engine out situation. If it also occurs on master then disregard.

**Comment by flogross89** [comment]
@BravoMike99 I‘m pretty sure the A380X AP doesn’t handle any beta/rudder trim yet, or rudder beyond turn coordination for that matter I believe. 
@lukecologne would be able to clarify

**Comment by Eagle941** [comment]
@BravoMike99 There is no automatic rudder. The action was to verify no anomalies with the "FAC" changes

**Comment by BravoMike99** [comment]
> @BravoMike99 There is no automatic rudder. The action was to verify no anomalies with the "FAC" changes

gotcha, since the testing  instructions mentioned engine failure I thought it was supposed to apply rudder. Will test again with that in mind

**Comment by BravoMike99** [comment]
Dev team QA report

Discord Username  : bruno_pt99
Object of testing : #10316 
Aircraft          : A380X
Simulator         : 2020
Tier of Testing   : 1
Date              : 26/11/2025

Testing Process: 
Performed a quick pattern with engine out and verified no rudder anomalies with different flap settings.

Testing Results: 
Passed
