### PR TITLE
fix(a380x): SD WHEEL: Remove abnormal indications, add gear and gear door status

### LINKED ISSUE #8718: [A380X] SD/WHEELS page: Remove abnormal indications
### Aircraft Version

Development

### Description

WHEELS page shows abnormal indications, remove them as long as we don't have the full systems implemention (including failure states).

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

_No response_

### PR DESCRIPTION
**Pull request by flogross89**
**A380X only, no QA needed**

Fixes #8718 

## Summary of Changes
Very simple version of a cleaned up version of the SD WHEEL page
- Remove abnormal indications, as long as LGCIU etc. are not yet implemented
- Add gear and gear door status (rudimentary)

## Screenshots (if necessary)
Screenshot 2024-08-21 030431

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo** or **flybywire-aircraft-a380-842** download link at the bottom of the page

### CODE REVIEW

File: fbw-a380x/src/systems/instruments/src/SD/Pages/Wheel/WheelPage.tsx [hunk 1]
```diff
@@ -8,13 +8,16 @@ import { BrakingSupply } from './elements/BrakingSupply';
 import { ControlSystem, ControlSystemType } from './elements/ControlSystem';
 import { Accumulator } from './elements/Accumulator';
 
-export const WheelPage = () => (
+export const WheelPage = () => {
+    const moreActive = false;
+
+    return(
```
Comment (Benjozork) [inline fbw-a380x/src/systems/instruments/src/SD/Pages/Wheel/WheelPage.tsx:14]: Hmm, do we lint the 380 SD right now?

**Review by Benjozork — CHANGES_REQUESTED** [review]

File: fbw-a380x/src/systems/instruments/src/SD/Pages/Wheel/WheelPage.tsx (hunk 1 above)
Comment (flogross89) [reply fbw-a380x/src/systems/instruments/src/SD/Pages/Wheel/WheelPage.tsx:14]: No, but we can of course un-ignore it with a following PR (would prefer that we don't do it with this one)

**Review by Benjozork — APPROVED** [review]
