### PR TITLE
feat(a380x): Enabled gravityfeeding and fixed crossfeed fuel usage 

### LINKED ISSUE #9170: FADEC WASM needs modification to allow for correct crossfeed operations
### Aircraft Version

Development

### Build info

```json
Any
```

### Describe the bug

The fuel system and overhead pushbuttons for crossfeed operations are in place. Any engine can be fed by any feed tank through use of the crossfeed valves when the main and standby pumps of a feed tank are inoperative (failed or switched off in the overhead).  However, the fuel will still be taken from the feed tank normally associated with that engine (i.e., feed one for engine one, feed two for engine two, feed three for engine three, and feed four for engine four) rather than the feed tank that is actually being used for that engine through the crossfeed system.

The FADEC WASM (https://github.com/flybywiresim/aircraft/blob/master/fbw-a380x/src/wasm/fadec_a380x/src/Fadec/EngineControl_A380X.cpp) controls which feed tank the fuel is removed as each engine burns fuel. It is not currently set up to address crossfeed operation. The A32NX FADEC WASM is similar, but was modified to address crossfeed operations (https://github.com/flybywiresim/aircraft/blob/master/fbw-a32nx/src/wasm/fadec_a32nx/src/Fadec/EngineControlA32NX.cpp). The A380X version will be more complex since there are 4 tanks rather than 2 hooked into the crossfeed system. 

### Expected behavior

Fuel to be drawn from the correct tank during crossfeed operations.

### Steps to reproduce

Open at least 2 crossfeed valves using the overhead pushbuttons. Turn off both main and standby fuel pumps on one of the feed tanks for which you opened the crossfeed valves. Observe that fuel will continue to be drawn from that tank.

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

donbikes

### LINKED ISSUE #9483: Engine will not start unless feed tank pump number 4 on
### Aircraft Version

Stable

### Build info

```json
"built": "2024-11-09T16:34:34+00:00",
    "ref": "refs/tags/v0.12.3",
    "sha": "7c0bb7fee6051b07edd3435d923b7acf1cec2945",
    "actor": "FoxtrotSierra6829",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.12.3",
    "version": "a380x-v0.12.3-rel.7c0bb7f"
}
```

### Describe the bug

1) engine will not start within reasonable time period until at least 1(main/stby) fuel pump at ALL feed tank is on.
With addition on issue #2841 , the N2 & N3 hardly increase but do eventually engine become "avail" after 39minutes.

2) after engine shut down, N2 will remains on 0.7 and will not return to 0

### Expected behavior

1) able to start the powerplant as normal with normal increasing N1,N2,N3 speed

2) N2 returns to 0 eventually

### Steps to reproduce

1. start up aircraft as normal but not turning on fuel pump
2. by adjusting the sim rate, issue 1 should be able to reproduced
3. turn on main FEED TKS 1,2,3,4 pump on
4. engine would start at normal pace
5. after all engine become avail and verified responds to throttle input, switch engine masters to "off"
6. with aids of simrate, the N2 value would remain at 0.7 while N1.N3 returns 0

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

tangotea

### PR DESCRIPTION
**Pull request by Maximilian-Reuter**
Fixes #9483
Fixes #9170

## Summary of Changes

This PR sets up the fuel system to be able to gravity feed. It achieves this by adding separate fuel pump for each engine that is active when the tank has fuel. It is always on and therefore can supply fuel pressure for the engines to start.

Additionally this PR also fixes the cross feed fuel usage by adding an extra tank per engine that sits in-between the engine and the LP Valve as a tiny buffer that can get filled by the MSFS fuel system so we don't have to deal with the different states of cross feeding for each engine.

## Additional context

Discord username (if different from GitHub): \_chaoz_

## Testing instructions

1. start C/D
1. startup the aircraft till engines running but dont activate any of the fuel pumps
1. APU and Engines should start normally
1. Using the W/B Menu from MSFS you should be able to monitor the fuel in each of the feed tanks.
1. open crossfeed 1 and 2
1. nothing should change in the way fuel is consumed
1. enable tank pumps for feed tank 1
1. all fuel usage from feed tank 2 should cease and fuel draw from feed tank 1 should double
1. deactivate fuel pumps for feed tank 1
1. fuel should be drawn again from feed 2 for engine 2 and usage for feed 1 should return to normal
1. repeat process for each engine and combination of crossfeed partners so: 
1+3,1+4,2+1,2+3,2+4,3+1,3+2,3+4,4+1,4+2,4+3
1. Finally do a complete flight and monitor the fuel system for abnormalities

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo**, **flybywire-aircraft-a380-842 (4K)** or **flybywire-aircraft-a380-842 (8K)** download link at the bottom of the page

### CODE REVIEW

File: fbw-a380x/src/wasm/fadec_a380x/src/Fadec/FadecSimData_A380X.hpp [hunk 1]
```diff
@@ -50,6 +50,21 @@ class FadecSimData_A380X {
...
+  DataDefinitionVector fuelExtraTankDataDef = {
+      {"FUELSYSTEM TANK QUANTITY", 12, UNITS.Gallons}, //
+      {"FUELSYSTEM TANK QUANTITY", 13, UNITS.Gallons}, //
+      {"FUELSYSTEM TANK QUANTITY", 14, UNITS.Gallons}, //
+      {"FUELSYSTEM TANK QUANTITY", 15, UNITS.Gallons}, //
+  };
+  DataDefinitionVariablePtr<FuelExtraTankData> fuelExtraTankDataPtr;  // in Gallons
+
   // Fuel Feed Tank Data in one Data Definition as they are read and updated together
   struct FuelFeedTankData {
```
Comment (Gurgel100) [inline fbw-a380x/src/wasm/fadec_a380x/src/Fadec/FadecSimData_A380X.hpp]: I think we can remove this struct?

Comment (Maximilian-Reuter) [reply fbw-a380x/src/wasm/fadec_a380x/src/Fadec/FadecSimData_A380X.hpp]: Can we ? We still need to gather the feed tank qty for saving fuel levels and set it if we load the aircraft from C/D

Comment (Maximilian-Reuter) [reply fbw-a380x/src/wasm/fadec_a380x/src/Fadec/FadecSimData_A380X.hpp]: I guess I could fold it into the other fuel system definition for all the other tank qtys. Just didnt want to mess with too much of the cpp stuff as I dont have a working intellisense setup so everything is always red :D Wish there was a guide for how to set that up properly

**Review by Gurgel100 — APPROVED** [review]
LGTM

**Comment by Jonny23787** [comment]
Quality Assurance Tester Report

Discord Username  : jonny_23
Object of testing : #10225 
Aircraft          : A380X
Simulator         : 2020
Tier of Testing   : 2
Date              : 16/08/2025

Testing Process: 

1. Loaded in cold and dark.
2. Powered aircraft and APU, without fuel pumps on.
3. Started engines without fuel pumps on.
4. Opened crossfeed 1 and 2, no change in fuel consumption.
5. Enabled tank pumps for feed tank 1.
6. Fuel usage stopped from feed tank 2 and rate of consumption doubled for feed tank 1.
7. Deactivated fuel pumps for feed tank 1.
8. Fuel consumption returned to normal.
9. Repeated process for various tank and crossfeed configurations.
10. Flew a full flight and monitored fuel usage.

Testing Results: 
Passed

Media:
I know that tier 2 tests should have media but it is a bit difficult to take meaningful screenshots for this kind of test.
