### PR TITLE
fix(a380/nd): Fix TERR text position

### LINKED ISSUE #9687: A380X/ND: "TERR" text wrong position
### Aircraft Version

Stable

### Build info

```json
master
```

### Describe the bug

"TERR" text on the A380 ND has wrong position. The font size might also be slightly off (smaller)
[image](https://github.com/user-attachments/assets/df4bd235-496b-46e8-9f88-e55bfe1a364e)

### Expected behavior

TERR text to be aligned with the elevation box.

### Steps to reproduce

1) Turn on terrain on ND on the A380 and observe the text position and size.

### References (optional)

image

### Additional info (optional)

_No response_

### Discord Username (optional)

bruno_pt99

### PR DESCRIPTION
**Pull request by MrJigs7**
Fixes #9687 

## Summary of Changes

Added CSS class on TERR text
Updated A380 stylesheet to reposition text and increase font size as per reference pictures

## Screenshots (if necessary)

TERRafterchange

## References

TERRrefpic

## Additional context

Discord username (if different from GitHub): MrJigs.

## Testing instructions

1. Load flight with A380 on runway
2. Turn on TERR on ND
3. Observe TERR text in correct positioning
4. Load A32NX and observe no changes

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo**, **flybywire-aircraft-a380-842 (4K)** or **flybywire-aircraft-a380-842 (8K)** download link at the bottom of the page

### CODE REVIEW

File: fbw-common/src/systems/instruments/src/ND/TerrainMapThresholds.tsx [hunk 1]
```diff
@@ -70,7 +70,7 @@ export class TerrainMapThresholds extends DisplayComponent<TerrainMapThresholdsP
   render(): VNode | null {
     return (
       <g visibility={this.shown.map((v) => (v ? 'inherit' : 'hidden'))}>
-        <text x={688} y={612} font-size={23} fill="rgb(0,255,255)">
+        <text class="a380xTerr" x={688} y={612} font-size={23} fill="rgb(0,255,255)">
```
Comment (Benjozork) [inline fbw-common/src/systems/instruments/src/ND/TerrainMapThresholds.tsx:73]: I know there were already classes like this, but I don't like prefixing things with `a380x` when they are in common. I would just make the class (or id) describe what it is, like `TerrainMapThresholdsText`.

**Review by Benjozork — CHANGES_REQUESTED** [review]

File: fbw-common/src/systems/instruments/src/ND/TerrainMapThresholds.tsx (hunk 1 above)
Comment (MrJigs7) [reply fbw-common/src/systems/instruments/src/ND/TerrainMapThresholds.tsx]: Fixed

**Comment by Jaronics** [comment]
Quality Assurance Trainee Report

Discord Username  : Jaronics 
Object of testing : #9754  
Aircraft          : A380X 
Tier of Testing   : 1
Date              : 26/01/2025 

Testing Process: 
1. Loaded the a380
2. Turned on TERR display, new font size and position is correct
3. Observed no changes on the a320
 

Testing Results: 
Passed  

Negatives:       
None

Conclusions: 
None

Media:
None
