### PR TITLE
fix(a380x/sd): status elements remaining visible

### LINKED ISSUE #10552: STS page elements remain visible on other SD pages
### Simulator

2024

### Aircraft Version

Development (4k)

### Build info

```json
Master
```

### Describe the bug

Elements of the status page appear on other SD pages after the status page has had non normal status

### Expected behavior

All elements are hidden when STS page is no longer shown

### Steps to reproduce

1. Trigger a failure such as engine failure.
2. After status page appears, switch through other SD pages, note elements still remaining visible on other other pages.

### References (optional)

Image

### Additional info (optional)

_No response_

### Discord Username (optional)

jonny_23

### PR DESCRIPTION
**Pull request by BravoMike99**
Fixes #10552 

## Additional context

Discord username (if different from GitHub): bruno_pt99

## Testing instructions

Open the status page with some inoperative systems shown (bleed off for example) and then leave the page. Verify the linked issue does not occur.
Check that the SD cruise page works ok.

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo**, **flybywire-aircraft-a380-842 (4K)** or **flybywire-aircraft-a380-842 (8K)** download link at the bottom of the page

### CODE REVIEW

File: fbw-a380x/src/systems/instruments/src/SDv2/Pages/Status/StatusPage.tsx [hunk 1]
```diff
@@ -42,7 +42,7 @@ export class StatusPage extends DestroyableComponent<SdPageProps> {
 
   private readonly availChecker = new FwsSdAvailabilityChecker(this.props.bus);
 
-  private readonly topSvgVisibility = this.props.visible.map((v) => (v ? 'visible' : 'hidden'));
+  private readonly topSvgDisplay = this.props.visible.map((v) => (v ? 'inline' : 'none'));
```
Comment (FozzieHi) [inline fbw-a380x/src/systems/instruments/src/SDv2/Pages/Status/StatusPage.tsx]: Doesn't the status page use flex?
```suggestion
  private readonly topSvgDisplay = this.props.visible.map((v) => (v ? 'flex' : 'none'));
```

Comment (BravoMike99) [reply fbw-a380x/src/systems/instruments/src/SDv2/Pages/Status/StatusPage.tsx]: Good point, I didn't check the style before changing. Fixed

**Comment by stratavelo92** [comment]
Quality Assurance Tester/Trainee Report

Discord Username  : spottersim 
Object of testing : #10587  
Aircraft          : A380X 
Simulator         : 2024 
Tier of Testing   : 1
Date              : 16/03/2026 

Testing Process: 
Activated some ELEC failures and cleared them. STS page, SD pages, and CRUISE page behaved as expected.

Testing Results: 
Passed  

Negatives:       
Some flickers when using ALL p/b to skip cycle through SD pages

Media:


https://github.com/user-attachments/assets/075b0afb-c9b4-4e18-9557-3fb822883955

**Comment by FozzieHi** [comment]
@stratavelo92 Do you mind opening up a new issue with that ALL page flickering? I have noticed it before so it's not down to this PR
