### PR TITLE
fix(atsu): Fixed ATIS request not working for Australian airports

### LINKED ISSUE #10201: ATIS request doesn't work for Australian airports
### Simulator Version

2020

### Aircraft Version

Development

### Build info

```json
master
```

### Describe the bug

Requesting VATSIM ATIS for Australian airports either via the ATC or AOC menus returns D-ATIS NOT AVAILABLE even though the station is online in vatsim. Request ATIS from other stations work just fine. Tested with YSSY, YMML, YBBN with the same result.

Strangely, when using the API on the website, the ATIS returns just fine. This might indicate an issue with one of the modules in fbw-common or the api-client.

### Expected behavior

VATSIM ATIS should be retrievable from all online stations.

### Steps to reproduce

1. Check vatsim for an online australian airport for an ATIS via vatsim-radar or other vatsim tools
2. Request for ATIS via ATC -> D-ATIS or AOC -> ATIS
3. Observe a failure in the ATIS retrieval

### References (optional)

Image

### Additional info (optional)

_No response_

### Discord Username (optional)

Heclak

### PR DESCRIPTION
**Pull request by CLC0609**
Fixes #10201 

## Summary of Changes

- Added handling for ATIS without the `"INFORMATION"` or `"INFO"` keywords, that instead follow the `"ICAO ATIS LETTER"` e.g. `"ATIS EDDB H METAR 091950"`

## Additional context
ATIS stations without the `"INFORMATION"` or `"INFO"` keywords were getting returned without a information letter causing the `AtsuStatusCodes.NoAtisReceived` error message to be displayed. Australian ATIS stations use the format `ATIS YBBN K 092013` which is why they were not working previously.

I couldn't find an ATIS station that included the ICAO where the next word / letter was not the information letter.

Discord username (if different from GitHub): clc0609

## Testing instructions
1. Load into either the A32NX or the A380X
2. Set the departure and arrivals to an airport an Australian airport that has an online ATIS station
3. Request the ATIS via ATC -> D-ATIS or AOC -> ATIS
4. Observe the ATIS being returned correctly

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo**, **flybywire-aircraft-a380-842 (4K)** or **flybywire-aircraft-a380-842 (8K)** download link at the bottom of the page

ps. this is my first FBW pull request so there is a good chance I have missed something :)

### CODE REVIEW

File: fbw-common/src/systems/datalink/common/src/messages/AtisMessage.ts [hunk 1]
```diff
@@ -29,9 +29,9 @@ export class AtisMessage extends WeatherMessage {
     // this function is only relevant for the ATC updater
     this.Reports.forEach((report) => {
       report.report.split(' ').forEach((word) => {
-        // expect 'INFORMATION H' or 'INFORMATION HOTEL'
+        // expect 'INFORMATION H', 'INFORMATION HOTEL' or 'YBBN K'
         if (foundInfo === false) {
-          if (word === 'INFORMATION' || word === 'INFO') {
+          if (word === 'INFORMATION' || word === 'INFO' || word === this.Reports[0].airport.toUpperCase()) {
```
Comment (FoxtrotSierra6829) [inline fbw-common/src/systems/datalink/common/src/messages/AtisMessage.ts]:
```suggestion
          if (word === 'INFORMATION' || word === 'INFO' || word === report.airport.toUpperCase()) {
```

File: .github/CHANGELOG.md [hunk 2]
```diff
@@ -36,7 +36,7 @@
 1. [A32NX/FMS] Adjusted TRANS ALT allowed entry range - @Jonny23787 (Jonathan)
 1. [A32NX/FMS] Add - sign to slope value on RAD NAV page - @Jonny23787 (Jonathan)
 1. [A32NX/FMS] Fix "NOT ALLOWED IN NAV" when sequencing TO waypoint while in LOC mode - @BravoMike99 (bruno_pt99)
-
+1. [ATSU] Fix certain aerodromes ATIS letter not being retrieved correctly - @clc0609 (Coby)
```
Comment (FoxtrotSierra6829) [inline .github/CHANGELOG.md:49]:
```suggestion
1. [ATSU] Fix certain aerodromes ATIS letter not being retrieved correctly - @clc0609 (Coby)

```
Small change, pls add back the empty line :D

**Review by FoxtrotSierra6829 — CHANGES_REQUESTED** [review]

**Comment by johbri1** [comment]
Trainee Report

Discord Username  : _jb321 
Object of testing : #10431 
Aircraft          : A32NX 
Simulator         : 2024 
Tier of Testing   : 1
Date              : 25/12/2025 

Testing Process: 
-Loading into A32NX in MSFS2024
-Entering flightplan from YSSY-YMML (altn: YSCB) into FMC
-Requesting ATIS for all stations (dep, arr, altn)
->received ATIS from YSSY (only Station online)

Testing Results: 
Passed  

Notes
request took longer than usual 
(requested ATIS for EDDF in 2nd testing at he same time, EDDF was About 5sec faster

Conclusions: 
working fine, however request took longer than usual

**Comment by calarandir** [comment]
Quality Assurance Trainee Report

Discord Username  : shadowca_
Object of testing : #10431
Aircraft          : A32NX
Simulator         : 2020
Tier of Testing   : 1
Date              : 25/12/2024

Testing Process: 
Starting the official FBW A20N development Version first to see the actual wrong behavior. Using Airport YBCS for Departure. ATC and ATIS are online. Requesting ATIS via ATC->D-ATIS. Result: "No ATIS Report received". Requesting ATIS via AOC -> ATIS. The ATIS is received and printed correctly.
Now starting with the PR build. Same Airports, same way to request the ATIS. ATIS is received correctly for YBCS in both cases (AOC/ATC) now.

Testing Results: 
Passed

Conclusions: 
Testing Instructions say "Request the ATIS via ATC -> D-ATIS or AOC -> ATIS" but the bug is only reproducible with ATC -> D-ATIS for me.

**Comment by heclak** [comment]
Thanks for fixing this! @CLC0609 I've set this to merge.
