### PR TITLE
fix(a380x/fws): Fix fuel pump sensing logic for PARKING normal procedure

### LINKED ISSUE #9941: Parking Checklist Incompletable
### Simulator

2020

### Aircraft Version

Stable (8k)

### Build info

```json
{
    "built": "2025-03-21T10:21:03+00:00",
    "ref": "refs/heads/master",
    "sha": "d110e51d2b56917c64f2e7c03c1d7a7d70fda228",
    "actor": "tracernz",
    "event_name": "manual",
    "pretty_release_name": "master:d110e51d",
    "version": "a380x-v0.13.0-dev.d110e51"
}
```

### Describe the bug

- The parking checklist is incompletable
- The checklist says to switch all fuel pumps off, doing so does not check the item
- The step does not have a tick box meaning that the item must be sensed
- The checklist must be manually overridden to be completed

### Expected behavior

Once all the fuel pumps are switched off the step is completed and marked in green

### Steps to reproduce

1. After landing, open the parking checklist and attempt to complete
2. Switch all fuel pumps off and observe no change on the checklist page

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

_No response_

### PR DESCRIPTION
**Pull request by flogross89**
Fixes #9941 
"FUEL PMPs OFF" on PARKING checklists is now properly sensed

## Summary of Changes

Also remove unused code from MEMOs code. 

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo**, **flybywire-aircraft-a380-842 (4K)** or **flybywire-aircraft-a380-842 (8K)** download link at the bottom of the page

### CODE REVIEW

File: fbw-a380x/src/systems/systems-host/systems/FlightWarningSystem/FwsCore.ts [hunk 1]
```diff
@@ -3379,26 +3370,12 @@ export class FwsCore {
...
-        !this.centerFuelPump1Auto.get() &&
-        !this.centerFuelPump2Auto.get() &&
-        !this.leftFuelPump1Auto.get() &&
-        !this.leftFuelPump2Auto.get() &&
-        !this.rightFuelPump1Auto.get() &&
-        !this.rightFuelPump2Auto.get() &&
-        this.allEngineSwitchOff.get(),
+        !this.engine4ValueSwitch.get(),
     );
+    this.allFuelPumpsOff.set(!this.feedTankPumps.some((v) => v.get()) && this.allEngineSwitchOff.get());
```
Comment (BravoMike99) [inline fbw-a380x/src/systems/systems-host/systems/FlightWarningSystem/FwsCore.ts:3378]: Perhaps it would be better to have the all pumps on condition on a mappable subject so the array does not have to be checked on every update?

Comment (flogross89) [reply fbw-a380x/src/systems/systems-host/systems/FlightWarningSystem/FwsCore.ts]: indeed, updated

**Review by BravoMike99 — APPROVED** [review]

**Comment by flogross89** [comment]
Quick QA
image

image

works
