### PR TITLE
fix(pfd): Improve FMA font size, mode change box & positions

### LINKED ISSUE #8218: FMA: CLB armed position
### Aircraft Version

Development

### Build info

```json
{
    "built": "2023-09-16T06:20:39+00:00",
    "ref": "refs/heads/master",
    "sha": "4783ebcadace8462bc71af4f8c1bb4c1ebdb322c",
    "actor": "2hwk",
    "event_name": "manual",
    "pretty_release_name": "master:4783ebca",
    "version": "v0.11.0-dev.4783ebc"
}
```

### Describe the bug

The CLB (armed) that appears on Line 2 of the FMA is aligned to the left.

### Expected behavior

With newer EIS standards (can't find the exact standard where the change occured but I think it's the same that replaced "SIGNS" with "SEAT BELTS" in the ECAM Memos) the CLB (armed) appears aligned to the center, just like NAV (armed).

### Steps to reproduce

1. Arm climb mode

### References (optional)

image

image

### Discord Username (optional)

Bernardo R

### PR DESCRIPTION
**Pull request by BravoMike99**
Fixes #8218 

## Summary of Changes

* Reduce armed FMA font size
* Adjust CLB armed position in accordance with newer DMC standards
* Adjust mode change FMA box for first, second and third column FMAs
* Adjust THR IDLE and V/S FPA FMA active font size
* Hide '+' sign on V/S & FPA FMAs if selected value is zero
* Reworked FLX FMA and "MAN" text position in MAN THR/MAN MCT/MAN TOGA
## Screenshots (if necessary)

Left = new, right = old
oldNew
newold2
newold3
oldnew4
oldnew5
newold7
VS
FPA

## References

Provided in the original issue, youtube videos and some others in private provided by @becas22 .
image
image
image
image
image
image
image

## Additional context

Initially this PR was only aimed to fix #8218 but during development a few issues were spotted in the FMA with @becas22 help. 
I also spotted some other FMA issues while working in this PR (AB armed position for e.g., vertical positioning on some etc. ) which I might touch on another PR. As such, the main idea of this PR was to improve some stuff while not making any big regressions as a direct result of these changes.

Discord username (if different from GitHub):
bruno_pt99
## Testing instructions

Fly around testing multiple FMA changes (lateral, vertical and thrust) and make sure nothing looks weird/out of place.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by BravoMike99** [comment]
Keeping this PR as a draft at the moment as I would like some thoughts on the position of the CLB FMA and font size of the armed modes.
This is how it currently it in the PR with a fontsize of 5.3px and eyeballing the CLB FMA position
image
With a size of 5.2 and 5.4 it looks like the following:
image
image

**Comment by beheh** [comment]
Hey there, thanks for the PR! While I don't have a specific issue, I do want to point out that the FMA layouts can vary from aircraft to aircraft due to different EIS versions, and of course it can be very different on other aircraft like A330s. So when gathering photos and references you will need to double-check that you're gathering consistent refs from a modern A320 EIS version.

I'll also /cc @lukecologne because I believe he's taken a close look at these in the past.

**Comment by beheh** [comment]
Hey there, thanks for the PR! While I don't have a specific issue, I do want to point out that the FMA layouts can vary from aircraft to aircraft due to different EIS versions, and of course it can be very different on other aircraft like A330s. So when gathering photos and references you will need to double-check that you're gathering consistent refs from a modern A320 EIS version.

For the CLB specifically it looks like #8218 indeed points out a new behaviour, so nice find & fix!

I'll also /cc @lukecologne because I believe he's taken a close look at these in the past.

**Comment by lukecologne** [comment]
I think that in the same versions where the CLB was centered, the armed mode font size was increased to be identical to the active modes (earlier it was much smaller), so I don't think reducing the font size is correct here. Not sure about the other changes, I'd have to compare to some more refs.

**Comment by BravoMike99** [comment]
> I think that in the same versions where the CLB was centered, the armed mode font size was increased to be identical to the active modes (earlier it was much smaller), so I don't think reducing the font size is correct here. Not sure about the other changes, I'd have to compare to some more refs. As @beheh already said, you have to be careful which EIS version is installed in your refs.

Hi there, thank you and @beheh for the comments. I am aware of the differences that there may be with EIS/DMC versions just like how it happens on other systems (FWS/FMGS etc,), as such, I tried to make sure the changes are applicable to the target EIS standard, however, there's always the possibility of some misinterpretation. Also feel free to ping me on discord regarding any questions, I'd be glad to discuss this further.

**Comment by tracernz** [comment]
I updated the changelog to 0.12, and took the liberty of reducing it down to a couple of lines. In general the changelog doesn't need to be super-detailed... git commit history records that. It's just for users to quickly see what new features and fixes might be relevant to them.

**Comment by beheh** [comment]
@BravoMike99 I'm following up with somebody, I might have another ref for you. Are you targeting a specific EIS version? At this level of detail it probably makes sense to just pick one (and also update README.md with it).

**Comment by BravoMike99** [comment]
> @BravoMike99 I'm following up with somebody, I might have another ref for you. Are you targeting a specific EIS version? At this level of detail it probably makes sense to just pick one (and also update README.md with it).
> 
> I think so far we have at least S15 if not higher, as that introduces the Auto Brake FMA (I believe). S16 I think is also pretty common.

Hi there. The CLB armed was introduced after S15, however, its hard for me to know which specific version introduced it due to airlines jumping versions and it not being documented in the DMC MODs provided by airbus for S15.2/16/17 & S18. S16 and S17 seem to be the more common ones indeed due to the Safety Beyond Standard retrofits going on.

**Comment by beheh** [comment]
I'm all for proceeding on this PR! The only enhancement that would be nice is picking an EIS version and adding it to README.md, for future consistency.

**Review by beheh — APPROVED** [review]

**Comment by auroraisluna** [comment]
QA Report

Discord: alepouna
Object of testing: #8235
Tier of Testing : 1
Date : 18/11/2023

Testing Process:
- Fly around testing multiple FMA changes (lateral, vertical and thrust) and make sure nothing looks weird/out of place.
- Notice for any issues 
- Notice changes look as described

Testing Results:
Passed

File: fbw-a32nx/src/systems/instruments/src/PFD/FMA.tsx [hunk 1]
```diff
@@ -925,17 +938,19 @@ class B2Cell extends DisplayComponent<CellProps> {
                 text2 = '';
             }
 
+            // CLB armed should be centered, other modes are aligned to the left on newer DMCs
+            this.xposSub.set(clbArmed ? 50.801795 : 40.777474);
```
Comment (lukecologne) [inline fbw-a32nx/src/systems/instruments/src/PFD/FMA.tsx:942]: Sorry for the late review, but I feel like this could be handled easier by just adding spaces to the text for CLB

Comment (BravoMike99) [reply fbw-a32nx/src/systems/instruments/src/PFD/FMA.tsx:949]: Good idea, I didn't think of that when I first made the change. I've changed it to use spaces and looks fine too. 
image

**Comment by lukecologne** [comment]
Just checked the TCAS armed mode, looks like it was shifted due to the changed font size:
Before: grafik
After: grafik

**Comment by lukecologne** [comment]
I took the liberty to add a small fix for this myself, hope that was ok for you:
grafik

**Comment by lukecologne** [comment]
Ok, I think we are good to go if you are ready @BravoMike99

**Comment by BravoMike99** [comment]
> Ok, I think we are good to go if you are ready @BravoMike99

All good from my side but perhaps we should bump the EIS version to something you find adequate as per beheh suggestion since the CLB centered is newer than S15. I've also been suggested by becas to touch #8217 in this PR considering there has been no more development in #8230 for a while. What do you think?

**Comment by lukecologne** [comment]
Ok, we just got a new ref where TCAS armed is centered. My theory is that this was actually done in the same update where CLB was also centered, since the EIS standard where the AP/FD TCAS mode was introduced is already rather old (EIS S8). I'm gonna push a quick fix for that, sorry about that. About #8230, if you want to take that PR over, it should still be in a new PR, and you should ask in the old PR if they plan on working on that further. And finally, we haven't made a decision in the team about the target EIS standard yet, but I mean, that can be easily updated in another PR so I wouldn't consider it a blocker

**Comment by lukecologne** [comment]
Fix is pushed, this is how it looks now: 
grafik

**Comment by beheh** [comment]
Just because I brought it up, I agree. If we can't easily agree on an EIS standard let's merge as-is, as there's a bunch of really nice fixes in here. Thanks for your contributions!

**Comment by BravoMike99** [comment]
> Ok, we just got a new ref where TCAS armed is centered. My theory is that this was actually done in the same update where CLB was also centered, since the EIS standard where the AP/FD TCAS mode was introduced is already rather old (EIS S8). I'm gonna push a quick fix for that, sorry about that. About #8230, if you want to take that PR over, it should still be in a new PR, and you should ask in the old PR if they plan on working on that further. And finally, we haven't made a decision in the team about the target EIS standard yet, but I mean, that can be easily updated in another PR so I wouldn't consider it a blocker. I don't think the cented CLB is newer than S15, I'm reasonably sure that it's actually at S13 or possibly earlier than that

No worries. I think its newer than S15 as I have seen some planes with the autobrake FMA on the 3rd line but the CLB not centered(e.g. https://youtu.be/0B1yu7Ju7fM?t=733) . Since those were the only doubts I had remaining, all good from my side to merge then 😃
