### PR TITLE
fix(a380x): allow CI 0 to be accepted by PERF pages

### LINKED ISSUE #9939: Cost Index 0 not being considered by PERF pages
### Simulator

2020

### Aircraft Version

Development (4k)

### Build info

```json
{
    "built": "2025-03-21T10:24:43+00:00",
    "ref": "refs/heads/master",
    "sha": "d110e51d2b56917c64f2e7c03c1d7a7d70fda228",
    "actor": "tracernz",
    "event_name": "manual",
    "pretty_release_name": "master:d110e51d",
    "version": "a380x-v0.13.0-dev.d110e51"
}
```

### Describe the bug

When setting cost index 0 in the INIT page, PERF pages display -- (dashes) for CI field.
Other CIs work as expected.

### Expected behavior

I would expect the PERF page to display the selected CI in the INIT page, even though it is 0.

### Steps to reproduce

1. Load a route
2. Put CI 0
3. Check PERF pages CI field

### References (optional)

Image~

Image

Image

Image

### Additional info (optional)

_No response_

### Discord Username (optional)

_No response_

### PR DESCRIPTION
**Pull request by Jonny23787**
Fixes #9939 

## Summary of Changes
Changed CI if statement to allow 0 to be entered in PERF pages

## Screenshots (if necessary)
Before
Screenshot 2025-03-24 183952
After
Screenshot 2025-03-24 182542

## References
FCOM

## Additional context

Discord username (if different from GitHub):
jonny_23

## Testing instructions
A380X Only

1. Load into aircraft and insert route either manually or via SimBrief.
2. On FMS INIT, set cost index to 0.
3. Check that cost index 0 is visible on PERF CLB, CRZ and DES page.
4. On FMS INIT set cost index to any other value (e.g. 100).
5. Confirm that cost index (e.g. 100) is visible on PERF CLB, CRZ and DES page.

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo**, **flybywire-aircraft-a380-842 (4K)** or **flybywire-aircraft-a380-842 (8K)** download link at the bottom of the page

### CODE REVIEW

File: fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/MfdFmsPerf.tsx [hunk 1]
```diff
@@ -535,7 +535,7 @@ export class MfdFmsPerf extends FmsPage<MfdFmsPerfProps> {
       (this.props.fmcService.master?.fmgc.getFlightPhase() ?? FmgcFlightPhase.Preflight) < FmgcFlightPhase.Descent,
     );
 
-    if (pd.costIndex) {
+    if (pd.costIndex !== null && pd.costIndex !== undefined) {
```
Comment (tracernz) [inline fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/MfdFmsPerf.tsx:538]: @flogross89 If the perf data is reset while this page exists, it will still show the old data with all these conditional sets?

Comment (flogross89) [reply fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/MfdFmsPerf.tsx:538]: @tracernz Good point, most likely yes. We would have to only check for `!== undefined` then, as null is used for the intentional non-set value here

Comment (tracernz) [reply fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/MfdFmsPerf.tsx:538]: I think we could accept this PR as it is, and adjust the whole onNewData in another one just to keep things simple for Jonny23787's first PR 😄 .

Comment (flogross89) [reply fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/MfdFmsPerf.tsx:538]: 100% agree, will write an issue for it

Comment (Jonny23787) [reply fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/MfdFmsPerf.tsx:538]: I'm happy to change my code to make it easier for you guys, you will just have to tell me what bit needs changing haha.

Comment (flogross89) [reply fbw-a380x/src/systems/instruments/src/MFD/pages/FMS/MfdFmsPerf.tsx:538]: > I'm happy to change my code to make it easier for you guys, you will just have to tell me what bit needs changing haha.

I guess it would require potentially a lot of changes in a few places, wouldn't be wise to tackle this in this PR. But thanks for the offer!

File: .github/CHANGELOG.md [hunk 2]
```diff
@@ -6,7 +6,7 @@
 <!--  1. [Changed Area] Title of changes - @github username (Name)  -->
 
 ## 0.13.0
-
+1. [A380X/PERF] Fixed issue where 0 was not allowed as cost index - @Jonny23787 (Jonny_23)
```
Comment (tracernz) [inline .github/CHANGELOG.md:9]: Please put new changes at the end of the 0.13.0 list, and also don’t remove the blank lines around headings.

**Review by tracernz — APPROVED** [review]
Thanks!

**Comment by Jaronics** [comment]
Quality Assurance Trainee Report

Discord Username  : Jaronics 
Object of testing : #9944  
Aircraft          : A380X 
Tier of Testing   : 1
Date              : 25/03/2025 

Testing Process: 
1. Loaded up a flightplan via simbrief.
2. Inserted CI 0. Observed it was displayed on CLB, CRZ and DES pages
3. Changed the cost index back to 60. Observed it was changed on CLB, CRZ and DES pages.
4. Tested further by changing the cost index on all the PERF pages and INIT. Everything behaved as expected.
 

Testing Results: 
Passed  

Negatives: 
None      


Conclusions: 
None


Media:
None
