### PR TITLE
fix(a380x): Various fixes for FCU, MFD, ND, lighting

### LINKED ISSUE #8822: [A380X] Ambient Light knob only activates at 50% position
### Aircraft Version

Development

### Build info

```json
"built": "2024-08-20T12:56:41+00:00",
"version": "a380x-v0.12.0-a380x-experimental.0190ede"
```

### Describe the bug

The ambient light knob only starts increasing brightness once it reaches the 50% position, meaning the light remains off until the knob is halfway turned

### Expected behavior

The ambient light brightness should begin increasing from 0% as soon as the knob is turned from its starting position

### Steps to reproduce

Turn ambient LT knob 

### References (optional)

_No response_

### Additional info (optional)

_No response_

### Discord Username (optional)

Letreiv

### PR DESCRIPTION
**Pull request by flogross89**
Fixes #8822 

## Summary of Changes

- Change FCU color to match references
- Add INTEG LT dimming for KCCU and ECAM CP keys
- RMP: Fix power supply for RMP 3
- ND: Fix bright background caused by TERR ON ND code
- Went over all INTEG LTs and improved XML where necessary
- Fix AMBIENT LT 50% potentiometer jump
- Tried fixing HOLDs in the FMS

## Additional context

Discord username (if different from GitHub): floridude

## Testing instructions

A32NX: 
1. Perform normal A-B flight with FMS. Make sure FMS including LNAV & VNAV & predictions still work as expected (either it works as before, or nothing at all - quick test)
2. ND instrument should still have a dark grey background, around #040404 (can be checked with docked out instrument and color picker, e.g. from IrfanView)

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo** or **flybywire-aircraft-a380-842** download link at the bottom of the page

### CODE REVIEW

File: fbw-a380x/src/systems/instruments/src/MFD/FMC/FmcAircraftInterface.tsx [hunk 1]
```diff
@@ -473,6 +473,129 @@ export class FmcAircraftInterface {
...
+
+    // apply icao limits
+    if (alt < 14000) {
+      kcas = Math.min(230, kcas);
+    } else if (alt < 20000) {
+      kcas = Math.min(240, kcas);
+    } else if (alt < 34000) {
+      kcas = Math.min(265, kcas);
+    } else {
+      kcas = this.fmgc.guidanceController?.atmosphericConditions.computeCasFromMach(alt, 0.83);
```
Comment (tracernz) [inline fbw-a380x/src/systems/instruments/src/MFD/FMC/FmcAircraftInterface.tsx:503]: This is getting well beyond the Law of Demeter 😬 .

**Review by tracernz — APPROVED** [review]

File: fbw-a380x/src/systems/instruments/src/MFD/FMC/FmcAircraftInterface.tsx (hunk 1 above)
Comment (flogross89) [reply fbw-a380x/src/systems/instruments/src/MFD/FMC/FmcAircraftInterface.tsx:503]: Indeed, but I didn't find a good alternative. Duplicating the code like in the original code is error prone, and creating an interface at the top of the chain just clutters the classes. Any idea?

**Comment by nebj00la** [comment]
Quality Assurance Trainee Report

Discord Username  : nebj00la
Object of testing : #8901
Aircraft          : A32NX
Tier of Testing   : 2
Date              : 15/09/2024

Testing Process: 

1. Loaded flight plan from KPVD->KBOS.
2. Verified various LNAV/VNAV predictions work as expected.
3. Verified ND instrument background very close to #040404. GIMP shows #050404, attached image for comparison.

Testing Results: 
Passed

Media:
8901-lnav-1
8901-vnav-1
8901-vnav-2
8901-vnav-3
