### PR TITLE
fix(a32nx/fms): fix preselected cruise speed/mach value showing in the descent phase

### LINKED ISSUE #9854: Blue MACH SEL stuck to PFD regardless of active phase
### Simulator Version

2020

### Aircraft Version

Development

### Build info

```json
{
    "built": "2025-02-12T03:17:17+00:00",
    "ref": "refs/heads/master",
    "sha": "945fc260da4f8deea891d284ab0f609e7147f7b2",
    "actor": "tracernz",
    "event_name": "manual",
    "pretty_release_name": "master:945fc260",
    "version": "a32nx-v0.13.0-dev.945fc26"
}
```

### Describe the bug

When I set intended cruise speed / mach number to CRZ page during climb phase, after reaching cruise level aircraft accelerates to selected mach but blue MACH SEL: 0.xx remains in PFD. When closing to TOD, after clicking speed knob to switch back to Managed mode, or after pushing altitude knob for Managed descend, blue MACH SEL: 0.xx still remains in PFD and is stuck there for rest of the flight.

### Expected behavior

Blue MACH SEL: 0.xx should disappear when reaching cruise level and starting acceleration towards selected speed/mach.

### Steps to reproduce

1. During climb, insert pre-selected speed / mach number to CRZ page
2. When closing to TOD, push speed knob for Managed mode
3. At TOD push altitude knob for Managed descend

### References (optional)

Image

Image

### Additional info (optional)

_No response_

### Discord Username (optional)

mipepe82

### PR DESCRIPTION
**Pull request by BlueberryKing**
Fixes #9854

## Summary of Changes

Fixes an issue where the preselected cruise speed/mach value was shown during the descent phase. This happened because the value was not properly reset.

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Go through the steps to reproduce the linked issue. Ensure the issue no longer occurs.

## How to download the PR for QA

Every new commit to this PR will cause new A32NX and A380X artifacts to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, find and click on the **PR Build** tab
1. Click on either **flybywire-aircraft-a320-neo**, **flybywire-aircraft-a380-842 (4K)** or **flybywire-aircraft-a380-842 (8K)** download link at the bottom of the page

### CODE REVIEW

File: fbw-a32nx/src/systems/instruments/src/MCDU/legacy/A32NX_FMCMainDisplay.ts [hunk 1]
```diff
@@ -1321,7 +1309,7 @@ export abstract class FMCMainDisplay implements FmsDataInterface, FmsDisplayInte
     }
   }
 
-  private updatePreSelSpeedMach(preSel) {
+  private updatePreSelSpeedMach(preSel: number | undefined) {
     // The timeout is required to create a delay for the current value to be read and the new one to be set
```
Comment (lukecologne) [inline fbw-a32nx/src/systems/instruments/src/MCDU/legacy/A32NX_FMCMainDisplay.ts:1313]: I don't really understand why this delay is there, is this still necessary or could it be removed?

Comment (BlueberryKing) [reply fbw-a32nx/src/systems/instruments/src/MCDU/legacy/A32NX_FMCMainDisplay.ts:1313]: I haven't tested it without the delay. The idea is that when a new flight phase activates, we need to give the AP code time to set the preselected speed before we unset/re-set it. From the FMS, we have no control over when the FG activates the preselected speed after we fire the `K:A32NX.FMS_PRESET_SPD_ACTIVATE` event.

File: fbw-a32nx/src/systems/instruments/src/MCDU/legacy/A32NX_FMCMainDisplay.ts [hunk 2]
```diff
@@ -824,8 +821,7 @@ export abstract class FMCMainDisplay implements FmsDataInterface, FmsDisplayInte
         }
 
         /** Arm preselected speed/mach for next flight phase */
```
Comment (tracernz) [inline fbw-a32nx/src/systems/instruments/src/MCDU/legacy/A32NX_FMCMainDisplay.ts:823]:
```suggestion
        /** Disarm preselected speed/mach for next flight phase */
```

**Review by tracernz — APPROVED** [review]

**Comment by Jonny23787** [comment]
Quality Assurance Trainee Report

Discord Username  : jonny_23
Object of testing : #9860 
Aircraft          : A32NX
Tier of Testing   : 1
Date              : 08/04/2025 

Testing Process: 

1. Set preselected mach value during climb, confirmed mach preselect displayed on PFD.
2. Confirmed mach select disappeared from PFD, aircraft increase mach value to preselected value.
3. Near TOD, selected managed speed, aircraft decelerated to computed value, confirmed mach select text was not displayed.
4. Selected managed decent, confirmed mach select text was not displayed.

Testing Results: 
Passed
