### PR TITLE
fix: fix ETA of TO waypoint display on ND

### LINKED ISSUE #8200: ND: ETA of TO waypoint displayed prior to takeoff
### Aircraft Version

Development

### Build info

```json
{
    "built": "2023-09-04T02:30:14+00:00",
    "ref": "refs/heads/master",
    "sha": "12c8e357bccc95d58b6fab4d2e2051ca6b9940fb",
    "actor": "Benjozork",
    "event_name": "manual",
    "pretty_release_name": "master:12c8e357",
    "version": "v0.11.0-dev.12c8e35"
}
```

### Describe the bug

ETA of TO waypoint is displayed on the ND prior to takeoff.
estimates
NDpredictions

### Expected behavior

ETA should only be displayed on ND after the FMS transitions to takeoff phase

### Steps to reproduce

1) Program the FMS as usual and observe that a time estimate is displayed on the top right of the ND:

### References (optional)

Looking at these Honeywell videos, it looks like it only shows the ETA shortly after takeoff phase is active (visible by the green text on the PERF page/disappearance of UPLINK TAKEOFF DATA prompt)
https://youtu.be/n0FLWxSy29U?t=519
https://youtu.be/knjzdnjEtTQ?t=1252
https://youtu.be/e-Inb_g06Ec?t=955

### Additional info (optional)

_No response_

### Discord Username (optional)

bruno_pt99

### PR DESCRIPTION
**Pull request by alexmilshtein**
* fix: ETA of TO waypoint is not displayed prior to takeoff and after landing in real aircraft
* doc: changelog

Fixes #8200 

## Summary of Changes

Fixes an issue where ETA of TO waypoint is visible on the ND prior to take-off and landing.
I decided to display it when the aircraft is detected to be off the ground and turn it off when it's on the ground (nose wheel pressure detected).
## Screenshots (if necessary)

On the ground before the flight plan entered
Screenshot 2023-10-14 225607
On the ground after the flight plan entered
Screenshot 2023-10-14 225825
Take-off before rotation
Screenshot 2023-10-14 230305
Take-off after rotation
Screenshot 2023-10-14 230337
Approach
Screenshot 2023-10-15 000527
Roll-out with main gear on the ground
Screenshot 2023-10-15 000725
Roll-out with nose wheel on the ground
Screenshot 2023-10-15 000751

## References

Take-off
https://www.youtube.com/watch?v=8DLYoj6S_lw&t=884s
Landing
https://youtu.be/rhI5XGwlnaI?t=269

## Additional context

Discord username (if different from GitHub):
alexm1987
## Testing instructions

1. Start Cold and Dark
2. Complete IRS alignment, observe PPOS is displayed on the ND but not ETA to TO and bearing. Before the change it was showing ETA 00:00 and bearing 000°.
3. Enter the flight plan, observe that there's still no ETA displayed on the ND, but bearing and distance are visible now.
4. Take-off as usual, as soon as GS (ground speed) goes above 100kts ETA becomes visible on the ND.
5. Upon landing when there's no more active legs in the flight plan left, ND switches to PPOS: ETA, bearing and distance are not visible. Another possibility if you manage to slow down to 100kts GS when the active leg is still active, ETA becomes unavailable.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

### CODE REVIEW

**Comment by BravoMike99** [comment]
Hi, on the Honeywell aircraft which the FBW is targeting the ETA becomes available as soon as the FMS transitions to the takeoff phase (GS greater than 90kts assuming takeoff power is set) while on rollout it seems to disappear somewhere below 100kts. The behavior you implemented seems to be the one of the Thales FMS which is the case on the videos you provided. In case you want to change that, here are a few videos with Honeywell: https://youtu.be/8EHTmIsz1oI https://youtu.be/UQE-g7yrY3w https://youtu.be/A1D2X9KELkM

**Comment by tracernz** [comment]
Additionally, the value transmitted from the FMS should be changed rather than the ND code (it already transmits -1 when some other conditions that make the ETA not computed are present).

**Comment by pinatacolada** [comment]
PPOS and MANUAL shouldn't have any predictions too, so no bearing track or distance.

**Comment by alexmilshtein** [comment]
> PPOS and MANUAL shouldn't have any predictions too, so no bearing track or distance.

@pinatacolada  Can you, please, explain what MANUAL is in this context?

**Comment by pinatacolada** [comment]
It's when the current leg is a MANUAL leg, the to waypoint is displayed as MANUAL without any prediction

**Comment by tracernz** [comment]
FM/VM legs.

**Comment by alexmilshtein** [comment]
Hey all, I've refactored a bit:
- ETA, distance, bearing is not shown when there no active leg, e.g. PPOS
- Once flight plan is there on the ground, bearing and distance is visible
- On take-off, once the ground speed reached 95kt, eta becomes visible
- On landing, without Go-Around (missed approach) support, one cannot actually see ETA going away once the speed is below certain threshold because. The reason being that once you lend there are no more active legs and ND switches to PPOS so distance, bearing and eta are gone right away.

**Comment by auroraisluna** [comment]
QA Report

Discord: alepouna
Object of testing: #8252
Tier of Testing : 1
Date : 30/10/2023

Testing Process:
- Start Cold and Dark
- [PASS] Complete IRS alignment, observe PPOS is displayed on the ND but not ETA to TO. Before the change it was showing 00:00.
- [PASS] Enter the flight plan, observer that there's still no ETA displayed on the ND.
- [PASS] Take-off as usual, as soon as rotation happens and nose wheel lifts off the ground ETA is displayed.
- [PASS] Land and observe that as soon as the nose wheel touches the runway ETA is gone.

Testing Results:
Passed

File: fbw-a32nx/src/systems/fmgc/src/guidance/GuidanceController.ts [hunk 1]
```diff
@@ -112,6 +115,8 @@ export class GuidanceController {
 
     verticalProfileComputationParametersObserver: VerticalProfileComputationParametersObserver;
 
+    lastActiveLeg: Leg | null;
```
Comment (BlueberryKing) [inline fbw-a32nx/src/systems/fmgc/src/guidance/GuidanceController.ts:118]: What is this used for?

Comment (alexmilshtein) [reply fbw-a32nx/src/systems/fmgc/src/guidance/GuidanceController.ts:118]: This is used to update efis with the data based on the active leg computed by the LnavDriver.
If there's no more active leg, ETA, bearing and distance will be updated not to appear on the ND.

Comment (BlueberryKing) [reply fbw-a32nx/src/systems/fmgc/src/guidance/GuidanceController.ts:118]: Ah, my apologies, I missed that somehow 😄. Nevertheless, I think the property is redundant because we already store `activeGeometry` and `activeLegIdx` in the `GuidanceController`, so we can just derive the active leg there, rather than having it set in `LnavDriver`. This is just a minor thing though, so let me know if you have a different opinion.

Comment (alexmilshtein) [reply fbw-a32nx/src/systems/fmgc/src/guidance/GuidanceController.ts]: no worries, probably you're right on this one.
I've made the change, have a look.

File: fbw-a32nx/src/systems/fmgc/src/guidance/GuidanceController.ts [hunk 2]
```diff
@@ -209,6 +211,40 @@ export class GuidanceController {
         }
     }
 
+    private updateEfisData() {
+        const gs = SimVar.GetSimVarValue('GPS GROUND SPEED', 'Knots');
+        const flightPhase = getFlightPhaseManager().phase;
+        const etaComputable = flightPhase >= FmgcFlightPhase.Takeoff && gs > 100;
+        const activeLeg = this.activeGeometry.legs.get(this.activeLegIndex);
```
Comment (BlueberryKing) [inline fbw-a32nx/src/systems/fmgc/src/guidance/GuidanceController.ts:218]: Sorry for being a pain, but just to make sure if `activeGeometry` is null.

```suggestion
        const activeLeg = this.activeGeometry?.legs.get(this.activeLegIndex);
```

**Review by BlueberryKing — APPROVED** [review]
Nice work!

**Comment by auroraisluna** [comment]
QA Report

Discord: alepouna
Object of testing: https://github.com/flybywiresim/aircraft/pull/8252
Tier of Testing : 1
Date : 02/11/2023

Testing Process:
- Start Cold and Dark
- [FAIL] Complete IRS alignment, observe PPOS is displayed on the ND but not ETA to TO. Before the change it was showing 00:00.
image

Negatives:
See above

Testing Results:
Not Passed

**Comment by alexmilshtein** [comment]
> QA Report
> 
> Discord: alepouna Object of testing: #8252 Tier of Testing : 1 Date : 02/11/2023
> 
> Testing Process:
> 
> * Start Cold and Dark
> * [FAIL] Complete IRS alignment, observe PPOS is displayed on the ND but not ETA to TO. Before the change it was showing 00:00.
>   image
> 
> Negatives: See above
> 
> Testing Results: Not Passed

There's some confusion here :) 
Not showing any ETA and bearing when it's PPOS is intentional. This is implemented to take on-board the feedback https://github.com/flybywiresim/aircraft/pull/8252#issuecomment-1763418514
ETA  to TO is visible only when:
- Flight plan is active
- GS > 100 kts during take-off and later phases, not pre take-off
Bearing and distance are visible only when there's an active leg in the flight plan.

**Comment by alexmilshtein** [comment]
I tested this out for the preflight phase:
Before alignment no bearing, distance and prediction on ND.
Screenshot 2023-11-03 194806
After alignment before flight plan is entered
Screenshot 2023-11-03 194920
After flight plan is entered bearing and distance are visible, but not ETA
Screenshot 2023-11-03 195007

Please, try building with `--no-cache`

**Comment by BravoMike99** [comment]
It might also be a good idea to update the testing instructions to the honeywell behavior (GS based) as they still refer the Thales behavior/before the changes.

**Comment by alexmilshtein** [comment]
> It might also be a good idea to update the summary of changes & testing instructions to the honeywell behavior (GS based) as they still refer the Thales behavior/before the changes.

You're right, I should've updated instructions.
The steps are now updated to reflect Honeywell specific behaviour.

**Comment by auroraisluna** [comment]
> Please, try building with `--no-cache`

I have downloaded the artifact provided by the GitHub action as it is the same (to my knowledge) artifact that is provided to the end users. I have re-downloaded the artifact and still can reproduce the issue. 

PS: My mistake earlier for the confusion on the issue, I "ate" a step on the testing instruction report. Have updated my comment.

**Comment by alexmilshtein** [comment]
> > Please, try building with `--no-cache`
> 
> I have downloaded the artifact provided by the GitHub action as it is the same (to my knowledge) artifact that is provided to the end users. I have re-downloaded the artifact and still can reproduce the issue.
> 
> PS: My mistake earlier for the confusion on the issue, I "ate" a step on the testing instruction report. Have updated my comment.

Can you, please, provide the flight plan you’re using? I’ll try to replicate it. I’m not sure why it’s not working for you.

**Comment by alexmilshtein** [comment]
I honestly don't know what's going on here.
I've downloaded the artifact myself and checked, it's not showing ETA when on the ground.
Screenshot 2023-11-10 003218
Screenshot 2023-11-10 003236

**Comment by Mack674** [comment]
Quality Assurance Tester Report

Discord: Mack674#2274
Object of testing: #8252
Tier of Testing: 1
Date: 11/02/2024

Testing Process: 
(Full flight EGLL - EGCC)
- Powered up from C&D at LHR
- Did a routine flight according to procedures
- Observed ND indications behaviour 
- Logged off at gate at MAN


Negatives: N/A 

Testing Results: Passed

Conclusions: Works as intended, great job!

Media:
8252-1gatel
8252-2taxi
8252-3roll1
8252-4roll2
8252-5crz
8252-6gatem
